### ISSUE TITLE
Error: `Decoded.swift` missing module "Box"

### ISSUE THREAD

**Issue by joelparkerhenderson** [thoughtbot/Argo#102]
When I upgrade an Xcode 6.2 project to 6.3 beta, and update the Podfile to point Argo to GitHub, then I get the error about missing module Box. 

In case it's helpful to know, I also have a Podfile entry for Runes, also updated to point to GitHub.

I don't see any definition for "Box" in the Argo source, nor in the Runes source.

Any ideas for a solution?

**Comment by tonyd256** [comment]
You will also need to import Rob Rix `Box` https://github.com/robrix/Box framework into your project. It is a dependency of Argo but is not embedded in the framework.

**Comment by gfontenot** [comment]
`Box` is used as part of the implementation of `Decoded`: https://github.com/thoughtbot/Argo/blob/master/Argo/Types/Decoded.swift#L5

If you're pointing your podspec at `master`, you're going to have a bad time in general. The code on `master` is in prerelease state. You should really be using one of the official releases, in this case version 0.4.3. You shouldn't have this problem at that point. Once we release Argo 1.0 (soon), we'll update the podspec to include `Box`.

**Comment by joelparkerhenderson** [comment]
Thanks @tonyd256 & @gfontenot. I have Box working successfully now. For what it's worth, if there's a way to namespace Box within Argo (or some other way) that will be helpful because the app I'm building is already using a different Box class implementation.

**Comment by gfontenot** [comment]
We're using robrix/Box as our dependency, so our Box implementation is already namespaced as `Box.Box`.

Side note: it would _probably_ be better for y'all to avoid reimplementing and to use a common dependency.
