### ISSUE TITLE
Map JSON key name

### ISSUE THREAD

**Issue by bonebox** [thoughtbot/Argo#103]
Is it possible to map a JSON key name to a value with Argo?  For example, say I have the following objects I want to map JSON into...

```
struct Model {
   ...
   let properties: [Property]
}

struct Property {
   let label: String
   let type: String
   let required: Bool
}
```
...and the corresponding JSON...

```
    ...   
     "model": {
            "identifier": {
                "type": "Dental",
                "version": "1.0"
            },
            "properties": {
                "patient": {
                    "type": "string",
                    "required": true
                },
                "historyOfPresentIllness": {
                    "type": "string"
                },
                "medicalSurgicalHistory": {
                    "type": "string"
                },
                "physicalExam": {
                    "type": "string"
                },
                ...
            }
        },
       ...
```
I know I can map the nested `type` and `required` values, but since the property keys are dynamic in the JSON (i.e., `patient`, `historyOfPresentIllness`, `medicalSurgicalHistory`, etc, can potentially be any string and are referenced in a different part of the JSON) I want to map them to the `label` property on the `Property` object.

**Comment by tonyd256** [comment]
So I think it could be possible but not very easy. The easiest solution would be to make `properties` an array and move the dynamic key into the object. For example:

```
            "properties": [
                {
                    "label": "patient",
                    "type": "string",
                    "required": true
                },
                {
                    "label": "historyOfPresentIllness",
                    "type": "string"
                },
                {
                    "label": "medicalSurgicalHistory",
                    "type": "string"
                },
                // etc...
             ],
...
```

That would be very easy to decode into your `Property` model.

The hard way would be to have the decode function of `Model` type to get the JSON object from the properties key then manually iterate through it and create your `Property` models.

Also see Issue #25
