### ISSUE TITLE
readme.md examples don't match the code

### ISSUE THREAD

**Issue by edwardaux** [thoughtbot/Argo#104]
Hi... first time Argo user, so apologies if I'm misinterpreting things.

The example shown in Argo's [readme.md](https://github.com/thoughtbot/Argo/blob/master/README.md) has the following example:

    static func decode(j: JSONValue) -> User? {
        return User.create
          <^> j <| "id"
          <*> j <| "name"
          <*> j <|? "email" // Use ? for parsing optional values
          <*> j <| "role" // Custom types that also conform to JSONDecodable just work
          <*> j <| ["company", "name"] // Parse nested objects
          <*> j <|| "friends" // parse arrays of objects
    }

However, `JSONDecodable`'s definition is as follows:

    static func decode(json: JSON) -> Decoded<DecodedType>
 
I assume that the correct code is:

    static func decode(j: JSON) -> Decoded<User>

Is that correct?  I'd submit a pull request, except that as a novice, it is possible (likely?) that I have no clue what I'm doing :smile:

**Comment by tonyd256** [comment]
@edwardaux The code on master has been moving forward to prepare for a 1.0 release along with Swift 1.2. We'll be making that release soon and update all the docs. For now, the readme still corresponds to Argo 0.3.x and 0.4.x versions. Check out which version you're using and then look at that tag on Github to see the relevant code. If you're working with the new Xcode 6.3 and Swift 1.2 then hang tight. Argo 1.0 will be released/announced very soon!
