### ISSUE TITLE
`decode` function comparison without Argo

### ISSUE THREAD

**Issue by paulyoung** [thoughtbot/Argo#109]
I **love** Argo but am currently considering whether adding it and its dependencies is appropriate for a framework.

The README says this:

```swift
extension User: JSONDecodable {
  static func decode(j: JSONValue) -> User? {
    return User.create
      <^> j <| "id"
      <*> j <| "name"
  }
}
```

For comparison, this same function without Argo would look like so:

```swift
extension User {
  static func decode(j: NSDictionary) -> User? {
    if let id = j["id"] as Int {
      if let name = j["name"] as String {
        return User(id: id, name: name)
      }
    }

    return .None
  }
}
```

Am I correct in thinking that a full comparison would be something like the following?

***

```swift
struct User {
  let id: Int
  let name: String
  let email: String?
  let role: Role
  let companyName: String
  let friends: [User]
  let teamName: String?
  let teamMembers: [User]?
}

extension User: JSONDecodable {
  static func decode(j: JSONValue) -> User? {
    return User.create
      <^> j <| "id"
      <*> j <| "name"
      <*> j <|? "email"
      <*> j <| "role"
      <*> j <| ["company", "name"]
      <*> j <|| "friends"
      <*> j <|? ["team", "name"]
      <*> j <||? ["team", "members"]
  }
}
```

For comparison, this same function without Argo would look like so:

```swift
extension User {
  static func decode(j: NSDictionary) -> User? {
    if let id = j["id"] as? Int,
      name = j["name"] as? String,
      email = j["email"] as? String?
      role = j["role"] as? Role,
      companyName = j["company"]["name"] as? String,
      friends = j["friends"] as? [User],
      teamName = j["team"]["name"] as? String?,
      teamMembers = j["team"]["members"] as? [User]? {
        return User(
          id: id,
          name: name,
          email: email,
          role: role,
          companyName: companyName,
          friends: friends,
          teamName: teamName,
          teamMembers: teamMembers
        )
      }

    return .None
  }
}
```

**Comment by MichaelMcGuire** [comment]
I notice you conspicuously left out "Role" in your translation :wink: 

For the model you have, that looks about right.  But when you're dealing with types not handled by `NSJSONSerialization`, including arrays of those types, you get a lot more help from Argo.

**Comment by gfontenot** [comment]
Totally valid concern. In addition to what you posted, you'd also need to add the `create` function to your user models.

Also, keep in mind that pulling Argo in as a dependency of your framework would require users to link Argo (and Runes, and soon Box as well) to your user's apps (assuming they are using frameworks. CocoaPods will do this for them). That _might_ be a deal breaker.

**Comment by paulyoung** [comment]
> I notice you conspicuously left out "Role" in your translation

:see_no_evil: - updated to add that and fix one other issue.

**Comment by paulyoung** [comment]
> In addition to what you posted, you'd also need to add the create function to your user models.

Aware of that if using Argo, thanks. I've written too many curried `create` functions to be able to forget!

**Comment by paulyoung** [comment]
> when you're dealing with types not handled by `NSJSONSerialization`, including arrays of those types, you get a lot more help from Argo

@MichaelMcGuire could you elaborate on that?

**Comment by MichaelMcGuire** [comment]
Sure, the line:
``` swift
role = j["role"] as Role,
```
probably won't do what you want it to do.  It is probably another `NSDictionary` that contains the key/values for the `Role` that will need to be properly mapped, so you would need code to do that also.  Of course, you don't get that "for free" from Argo, as you would need to implement `JSONEncodable` for that also.  But if you do that, then you get handling an array of them.

**Comment by gfontenot** [comment]
yep. @MichaelMcGuire is exactly right. You'd have to do something like:

```swift
role = Role.decode(j["role"])
```

**Comment by paulyoung** [comment]
Yeah, I realized that as soon as I'd asked. That seems totally reasonable though.

Any other concerns or gotchas?

**Comment by paulyoung** [comment]
As for arrays?

```swift
friends = j["friends"].map { User.decode($0) }
```

**Comment by gfontenot** [comment]
Yes, _but_ you'd also need to bring in [`sequence`](https://github.com/thoughtbot/ExtendedArray/blob/master/Source/Sequence.swift) to get the same behavior of Argo (when one decode fails, the entire array fails)

**Comment by gfontenot** [comment]
You example also probably won't handle the case of _actual_ optional values. The `if let` will fail if it's `.None`, where as you'd want to let that succeed. You might want to confirm this.

**Comment by paulyoung** [comment]
> when one decode fails, the entire array fails

TIL.

It looks like `map` succeeds until the first decode fails rather than all or nothing. In some cases it might actually be desirable to do:

```swift
friends = j["friends"].reduce([], combine: { accum, elem in
  if let user = User.decode(elem) {
    return accum + [user]
  } else {
    return accum
  }
})
```

(specialized for `User`, could be made generic)

**Comment by paulyoung** [comment]
> You example also probably won't handle the case of _actual_ optional values. The if let will fail if it's .None, where as you'd want to let that succeed. You might want to confirm this.

@gfontenot do you mean if a key is missing from the JSON dictionary? If so, this works:

```swift
let j: NSDictionary = [
    "id": 123
]

// prints "success"
if let name = j["name"] as? String?, id = j["id"] as? Int {
    println("success")
} else {
    println("failure")
}
```

Sorry for the detour. This all helps in weighing things up.

**Comment by gfontenot** [comment]
Good to know that using `as? Foo?` works as I'd hope. I hadn't ever tried it, so was taking the more pessimistic route.

re: your map/reduce question, `map` should return `[User?]` and your `reduce` version should return `[User]`. We chose to go with `[User]?` (using `map`/`sequence`) because it fits in line with the behavior of the rest of the lib (we _never_ fail silently). I think it's probably fine for you to use `reduce` to get `[User]`, but if you were trying to replicate Argo's behavior exactly, you'd want to use `map`/`sequence`.

**Comment by paulyoung** [comment]
In addition to all of this, Argo also does JSON parsing which I'd need to handle.

I think there's a pretty compelling case for me to continue to use it.

Thanks @MichaelMcGuire @gfontenot!

**Comment by gfontenot** [comment]
Argo doesn't actually parse JSON itself, to be clear. We rely on `NSJSONSerialization` to do the `NSData -> AnyObject` transformation. We just then turn it into an enum for performance/type safety reasons.
