### ISSUE TITLE
Handling [String:String] dictionaries

### ISSUE THREAD

**Issue by edwardaux** [thoughtbot/Argo#114]
Hi, I've been using Argo in a new Swift project and am loving it so far - it is my first real foray into functional programming so pretty much everything is a learning curve :-)

I've managed to create my own model objects and can successfully parse my JSON except for one last thing - handling `[String:String]` data. Imagine that my (simplified) model object looks something like this:

	struct User {
		let name: String
		let age: Int
		let metadata: [String:String]
	}
	
My JSON would look like this:

	{
		"name" : "John Smith",
		"age"  : 42,
		"metadata" : {
			"field1" : "some value",
			"otherField" : "foo bar"
		}
	}
	
The `metadata` property is really just a collection of random name/value pairs. There could be none, or there could be 50 and I don't know ahead of time what the keys are (hence it is modelled as a `[String:String]`)

Unfortunately, `Decoded<[String:String]>` is not a supported return type for the `<|` operator. At the moment, my half-baked solution is to create an object that represents this type of dictionary and then traverse over the `JSON` values (see below). But it just doesn't feel right. Just curious if there is a better way?  Any thoughts or guidance would be much appreciated.  Thanks.

	struct StringDictionary {
		let values: [String:String]
		init(_ values: [String:String]) {
			self.values = values
		}
	}
	extension StringDictionary : JSONDecodable {
		static func decode(j: JSON) -> Decoded<StringDictionary> {
			switch j {
			case .Object(let s):
				var values = [String:String]()
				// TODO not sure how to traverse a list of un-named keys
				return .Success(Box(StringDictionary(values)))
			default: return .TypeMismatch("\(j) is not a valid [String:String] dictionary")
			}
		}
	}

**Comment by gfontenot** [comment]
This is actually something that we (accidentally) implemented in the SOON TO BE RELEASED WE PROMISE Argo 1.0. Decoding to dictionaries (of they type `[String: T: JSONDecodable]`) Just Works™ like any other decodable type.

**Comment by edwardaux** [comment]
Thanks for the quick reply @gfontenot. Is that code in a private branch, or is something I can merge to my fork in the meantime?

**Comment by gfontenot** [comment]
The change is in `master` now. It's also a significant change from `0.4.3` in terms of API. You might want to look over the diff in #112 if you want to get a sense of the changes. The code on `master` is _probably_ what we'll be shipping for 1.0, although I can't make that guarantee, and likewise can't make any guarantee about any non-official release.

Take that as you will.

**Comment by edwardaux** [comment]
Perfect, thanks for pull request reference. I'm looking it over now and will almost certainly pull it in and just deal with the API changes.  Thanks for a great library!

**Comment by edwardaux** [comment]
Hmm... I finally had a chance to pull in the latest code (`3a0d057`). Unless I am missing soemthing, there are no new operators to support decoding to dictionaries.

For example, the following code still doesn't compile:

	extension User : Decodable {
		static func create(name: String)(age: Int)(metadata: [String:String]) -> User {
			return User(name, age, metadata)
		}
	
		static func decode(j: JSON) -> Decoded<User> {
			return User.create
				<^> j <|  "name"
				<*> j <|  "age"
				<*> j <|| "metadata"
		}
	}

It gives me an error saying `Could not find an overload for <*> that accepts the supplied arguments`. Same error whether I use the `<|` or `<||` operator.

**Comment by gfontenot** [comment]
Oh, right, we don't have it set up with a custom operator. But if you do `j <| "metadata" >>- decodeObject` it should work. You might need parens around the `<|` part, I can never remember.

**Comment by edwardaux** [comment]
Thansk @gfontenot. That worked perfectly.  Started to get a bit hairier when one of my parameters was optional dictionary, but in the finish I just created my own `<|~` and `<|~?` operators and everything works + looks nice and neat.

Thanks again for your help.

**Comment by gfontenot** [comment]
Optional dictionaries are easy enough with our syntax: `.optional(j <| "metadata" >>- decodeObject)` would give you what you want.

**Comment by edwardaux** [comment]
Ahh... so that makes sense. I tried various incantations like `(j <|? "headers") >>- { decodeObject($0) }` but obviously that doesn't work.  I'm ever so slowly putting it all together... 

Thanks again for your patience.

**Comment by gfontenot** [comment]
No worries. There's literally no documentation around this stuff yet. We're working on writing it. We'll get there at some point.

**Comment by Torsph** [comment]
Did you have an example to use the decodeObject in the user example?

```
struct User {
    let name: String
    let age: Int
    let metadata: [String: String]
}

extension User : Decodable {
    static func create(name: String)(age: Int)(metadata: [String:String]) -> User {
        return User(name: name, age: age, metadata: metadata)
    }
    
    static func decode(j: JSON) -> Decoded<User> {
        return User.create
            <^> j <|  "name"
            <*> j <|  "age"
            <*> (j <| "metadata") >>- decodeObject
    }
}
```

I Just keep getting "Could not find an overload for <*> that accepts the supplied arguments"

**Comment by alskipp** [comment]
I think moving the closing parens might fix it. Try the following:
```swift
<*> (j <| "metadata" >>- decodeObject)
```
I'm unable to test that at the minute, but I think it should work.

**Comment by Torsph** [comment]
@alskipp That did work. Thanks :)

**Comment by alskipp** [comment]
@Torsph I'm not sure about the answer to that question. If the dictionary you're dealing with has a regular and known structure it would make sense to decode it into a struct value too. If you don't know the dictionary keys in advance, then that won't be a plausible solution.

**Comment by Torsph** [comment]
@alskipp The hope was to not know. And just have an dict with key an values.

**Comment by paulyoung** [comment]
What's the correct way to do this using the version on `master`?

I'm getting `Use of unresolved identifier 'decodeObject'` when doing:

```
<*> .optional(j <| "metadata" >>- decodeObject)
```

**Comment by paulyoung** [comment]
My mistake! I was using the Swift 2 branch.

**Comment by edwardaux** [comment]
For the `td-swift-2` branch, I've been using the following:

	infix operator <|~ { associativity left precedence 150 }
	infix operator <|~? { associativity left precedence 150 }

	// Pull dictionary from JSON
	public func <|~ <A where A: Decodable, A == A.DecodedType>(json: JSON, key: String) -> Decoded<[String:A]> {
		return json <|~ [key]
	}

	// Pull optional dictionary from JSON
	public func <|~? <A where A: Decodable, A == A.DecodedType>(json: JSON, key: String) -> Decoded<[String:A]?> {
		return .optional(json <|~ [key])
	}

	// Pull embedded dictionary from JSON
	public func <|~ <A where A: Decodable, A == A.DecodedType>(json: JSON, keys: [String]) -> Decoded<[String:A]> {
		return flatReduce(keys, initial: json, combine: decodedJSON) >>- Dictionary<String,A>.decode
	}

	// Pull embedded optional dictionary from JSON
	public func <|~? <A where A: Decodable, A == A.DecodedType>(json: JSON, keys: [String]) -> Decoded<[String:A]?> {
		return .optional(json <|~ keys)
	}
