### ISSUE TITLE
TypeMismatch: "Null is not a Int"

### ISSUE THREAD

**Issue by marcelofabri** [thoughtbot/Argo#116]
I just updated Argo to 1.0.0 and I'm seeing a regression:

I have a model with some optional values and when I try to parse a JSON containing a `null` value (an `NSNull`), I'm getting a TypeMismatch: "Null is not a Int" in runtime.

Here's the model:

```swift
public struct Identifiers {
    public let trakt: Int
    public let tvdb: Int?
    public let imdb: String?
    public let tmdb: Int?
    public let tvrage: Int?
    public let slug: String?
}

extension Identifiers: Decodable {
    static func create(trakt: Int)(tvdb: Int?)(imdb: String?)(tmdb: Int?)(tvrage: Int?)(slug: String?) -> Identifiers {
        return Identifiers(trakt: trakt, tvdb: tvdb, imdb: imdb, tmdb: tmdb, tvrage: tvrage, slug: slug)
    }
    
    public static func decode(j: JSON) -> Decoded<Identifiers> {
        return Identifiers.create
            <^> j <| "trakt"
            <*> j <|? "tvdb"
            <*> j <|? "imdb"
            <*> j <|? "tmdb"
            <*> j <|? "tvrage"
            <*> j <|? "slug"        
    }
}
```

And the parse itself:

```swift
let json: NSDictionary = [
            "trakt": 36440,
            "tvdb": 3254641,
            "imdb": "tt1480055",
            "tmdb": 63056,
            "tvrage": NSNull()
        ]
        
let value = JSON.parse(json)
 let id = Identifiers.decode(value)
```

Any thoughts? I could remove the keys with `NSNull` values from the dictionary, but I think Argo should handle it (as it was before 1.0.0).

**Comment by tonyd256** [comment]
@marcelofabri Thanks for submitting the issue. This is a regression that we weren't aware of. When we switched to the `Decoded` type we treated `.Null` cases as `.TypeMismatch` which will throw the errors. We need to change that to return `.MissingKey` and it will work. I'll work on this soon and get back to you.

**Comment by tonyd256** [comment]
We're working on a fix here: #117

**Comment by tonyd256** [comment]
@marcelofabri This issues is fixed. Use version 1.0.1 and let us know if you have any more issues.

**Comment by marcelofabri** [comment]
Thanks! It works now. Could you please push the Podspec to trunk too?

**Comment by gfontenot** [comment]
@marcelofabri Should be all set now!
