### ISSUE TITLE
Examples for decoding json array to list?

### ISSUE THREAD

**Issue by levinotik** [thoughtbot/Argo#118]
I can't find any examples of how to decode into an array/list of values. For instance, if I had a json array 

```
[{"foo":"bar"}, {"foo":"bar"}]
```

and wanted to decode:

```
let foos: [Foo] = decode(j)
```

**Comment by levinotik** [comment]
Looks like I can just do 

`let foos: [Foo]? = decode(j)`?

**Comment by tonyd256** [comment]
@levinotik Yup that's correct. You can use the `decode` function to get an optional array of objects or a single object. You can also use it to get your model (or array of models) wrapped in the `Decoded` type. This would give a bit of context if the decoding fails.

```swift

**Comment by tonyd256** [comment]
If you think an example in the tests would help explain this better I would love to have a PR to add it :)
