### ISSUE TITLE
Thanks!

### ISSUE THREAD

**Issue by sgoodwin** [thoughtbot/Argo#119]
I was debating with myself if I should change the previous Optional-based implementation to use some kind of custom type with more info than just "it didn't work", but I thought y'all might be working on that anyway. Turns out you are! Upgraded today, things are much nicer now. Thanks! :+1:

**Comment by gfontenot** [comment]
Awesome, thanks for the feedback! It means a lot. Glad that you're enjoying 1.0 as much as we enjoyed making it. Feel free to open issues if you have any questions or run into any problems.
