### ISSUE TITLE
framework search paths issue when using submodules

### ISSUE THREAD

**Issue by tonyd256** [thoughtbot/Argo#121]
When using the Carthage flag `--use-submodules` and `--no-build` in a project that depends on Argo, Argo's framework search paths do not exist because they point to the Carthage build directory. However, removing these breaks the build when not using those flags.

This issue can be a discussion on how to fix this.

@paulyoung Please add any info to this issue that I might have missed above.

**Comment by paulyoung** [comment]
We can always refer to #111 and this project: https://github.com/paulyoung/ArgoCarthageIssue

**Comment by gfontenot** [comment]
This should be fixed with #123.
