### ISSUE TITLE
Returning some of a JSON array

### ISSUE THREAD

**Issue by sgoodwin** [thoughtbot/Argo#124]
Let's say the server returns a JSON array of photos. Each photo should have an ID, a URL, and maybe the name of the person who took it.

```swift
struct Photo {
   let id: String
   let authorName: String
   let URL: NSURL
}
```

Now, we don't wanna show a photo in the app if info is missing. A photo without the author's name breaks things, so I don't wanna mark it as optional. However, in it's current form, the decode function would return nil if one photo out of 20 were missing the name.

How complicated would it be to make decode return the 19 valid photos and maybe have information somewhere to say "this one photo was invalid" instead of showing 0 photos in the app when 19 are totally fine to show?

**Comment by gfontenot** [comment]
you could write your own parser to handle this. It would look a lot like the built in Array parser, but with `catOptionals` instead of `sequence`:

```swift
public func decodePartialArray<A where A: Decodable, A == A.DecodedType>(value: JSON) -> Decoded<[A]> {
  switch value {
  case let .Array(a): return catOptionals(A.decode <^> a)
  default: return .TypeMismatch("\(value) is not an Array")
  }
}

func catOptionals<T>(xs: [T?]) -> [T] {
    return xs.reduce([]) { accum, elem in
        return elem.map { accum + [$0] } ?? accum
    }
}
```

Then, in your `decode` function:

```swift
j <| "photos" >>- decodePartialArray
```

**Comment by tonyd256** [comment]
Yes, it's doable, but you might want to look into why you have partial information about a photo. If it's just because you're dealing with bad data that you don't have control over then that's one thing but if you do control that then fixing the data source to return full or no data for an image might be easier and more reliable.

**Comment by gfontenot** [comment]
You'll need to wrap that successful `return` statement in `pure`, too.

**Comment by sgoodwin** [comment]
Ah yes, that would work.

Tony: In this one case I have control over the API, but on most client projects I don't so I was curious.

Thanks again!
