### ISSUE TITLE
Converting Strings to different Types during decoding

### ISSUE THREAD

**Issue by lorlab** [thoughtbot/Argo#131]
Hi! Thanks for this great library! I have a question about transforming values while decoding. Someone has asked the same question before but I still don't understand... And the RoleType example in the docs in not clear to me... Also I read that things might have changed in 1.0 so I thought I'd ask the same question again. Sorry if I missed the explanation somewhere.

Say I have a basic Photo model like below (this doesn't compile), how would I convert a String in the JSON to a NSURL, or a String into a NSDate with a certain format? 

```
struct Photo {
    let id: Int
    let url: NSURL
    let date: NSDate
}

extension Photo: Decodable {
    
    static func create(id: Int)(url: NSURL)(date: NSDate) -> Photo {
        return Photo(id: id, url: url, date: date)
    }
    
    static func decode(j: JSON) -> Decoded<Photo> {
        return Photo.create
            <^> j <| "id_photo"
            <*> j <| "url"
            <*> j <| "date"
    }
}
```

**Comment by MichaelMcGuire** [comment]
There are multiple ways to do this, but what I've ended up doing was adding `Decoable` protocol compliance to existing types using extensions.  Here is an example for `NSDate` that converts from a `yyyy-MM-dd` format using the Objective-C runtime to hold an instance of an `NSDateFormatter` alongside the class to avoid costly creation for each decode:

```
import Foundation
import ObjectiveC
import Argo

private var jsonFormatterAssociatedKey: UInt8 = 0

extension NSDate: Decodable {
    
    class var jsonFormatter: NSDateFormatter {
        
        if let jsonFormatter = objc_getAssociatedObject(self, &jsonFormatterAssociatedKey) as? NSDateFormatter {
            return jsonFormatter
        } else {
            let jsonFormatter = NSDateFormatter()
            jsonFormatter.dateFormat = "yyyy-MM-dd"
            objc_setAssociatedObject(self, &jsonFormatterAssociatedKey, jsonFormatter, objc_AssociationPolicy(OBJC_ASSOCIATION_RETAIN))
            return jsonFormatter
        }
    }
    
    public static func decode(j: JSON) -> Decoded<NSDate> {
        switch j {
        case let .String(s):
            if let date = self.jsonFormatter.dateFromString(s) {
                return pure(date)
            } else {
                return .TypeMismatch("\(j) is not a date")
            }
        default: return .TypeMismatch("\(j) is not a date")
        }
    }
}
```

**Comment by siemensikkema** [comment]
Nice idea to extend the existing types. For the date formatter, why not use a private global immutable variable instead? Ie.:
```swift
private let jsonDateFormatter: NSDateFormatter = {
    let dateFormatter = NSDateFormatter()
    dateFormatter.dateFormat = "yyyy-MM-dd"
    return dateFormatter
}()
```
By the way, my solution was:
```swift
...
import Runes
...
<*> j <| "time" >>- toNSDate
...
```
Where:
```swift
private func toNSDate(dateString: String) -> Decoded<NSDate> {
    return Decoded<NSDate>.fromOptional(iso8601DateStringToDate(dateString))
}
```
This _could_ be handy if you have multiple ways to convert strings to dates or if want to specify extra parameters to the conversion function with the help of currying:
```swift
...
<*> j <| "date" >>- toNSDate(extraParameter: 1)
...
private func toNSDate(#extraParameter: Int)(dateString: String) -> Decoded<NSDate> {
    return ...
}
```
I used to do this for specifying a fallback date in case of a missing key but since realized I could pass an optional NSDate to the `create` function.
See [TimeStringToDate.swift](https://gist.github.com/siemensikkema/86f19f48d4306e4fa85d) for my _prematurely_ :innocent: optimized date parsing functions

**Comment by MichaelMcGuire** [comment]
Awesome solution @siemensikkema.  The private global immutable variable is a much cleaner and more Swift-like solution. 

I think I also prefer separating out parsing certain types like `NSDate`s to a separate function and having the flexibility of different date types (some JSON API's are just cray-cray).

**Comment by lorlab** [comment]
Thanks guys! 
I'm just a bit confused.. Does @siemensikkema 's solution still rely on the NSDate extension?

**Comment by siemensikkema** [comment]
Mine does not depend on the NSDate extension. I made a suggestion to swap out the computed class var with a private global immutable variable _and_ I demonstrated how I did it without an extension. My alternative solution does depend on another function that was specific to my use case (`iso8601DateStringToDate`).

Combining my suggested formatter with the `toNSDate` function would look something like:

```
private let jsonDateFormatter: NSDateFormatter = {
    let dateFormatter = NSDateFormatter()
    dateFormatter.dateFormat = "yyyy-MM-dd"
    return dateFormatter
}()

private func toNSDate(dateString: String) -> Decoded<NSDate> {
    return Decoded<NSDate>.fromOptional(jsonDateFormatter.dateFromString(dateString))
}
```

**Comment by gfontenot** [comment]
PROTIP: you could actually omit the type in the `toNSDate` function:

```swift
private func toNSDate(dateString: String) -> Decoded<NSDate> {
    return .fromOptional(jsonDateFormatter.dateFromString(dateString))
}
```

(Love this thread, folks. Great suggestions all around.)

**Comment by siemensikkema** [comment]
Oooh! I like that.

**Comment by siemensikkema** [comment]
I just found out that after the latest `carthage update` I have to wrap the conversion expression in parentheses, like so:
```swift
<*> (j <| "time" >>- toNSDate)
```
As a result from [this commit](https://github.com/thoughtbot/Runes/commit/d3a7d6352339a45ce307f4c579bf4e0048df334b).

**Comment by lorlab** [comment]
Thanks @siemensikkema ! I went with your solution, only I moved the `toNSDate` function to a separate "helpers" file so that all my Models can use it.

**Comment by tonyd256** [comment]
Great discussion everyone! Glad to see others actively helping out! :smile:

**Comment by sammy-SC** [comment]
@siemensikkema +1 thank you.

**Comment by kayvink** [comment]
+1 This is great! Thanks a lot guys.

**Comment by terhechte** [comment]
Small addendum to this: If you also need default values, you can use currying for that:

```
private func toInt(defaultValue: Int = 0)(number: String) -> Decoded<Int> {
    return .fromOptional(Int(number) ?? defaultValue)
}
```

```<*> (js <| "identifier" >>- toInt(-1))```

**Comment by tonyd256** [comment]
@terhechte We also provide Alternative `<|>` for defaults. It can be used like this
`<*> (js <| "identifier" >>- toInt) <|> .Success(-1)`

**Comment by terhechte** [comment]
@tonyd256 thanks! ... https://github.com/thoughtbot/Argo/commit/4f0065a2186d8f9f439d49415ac4d1ecd77a072f ;) I totally missed using it with `.Success`

**Comment by tonyd256** [comment]
No worries ... otherwise I don't think the default value of 0 would have worked. you couldn't flatMap to `toInt` if you didn't provide the defaultValue.

**Comment by timcloss** [comment]
I know this issue is closed, but I am pasting here because I'm having a problem with the code provided.

I am trying to curry NSDate and can't get the solution above to work. Here's my code:

> 
class ActivityProgressRecord : Decodable
{
    let timestamp: NSDate
    let activityId: String
    let type: ActivityProgressRecordType
    let properties: [String:String]

    private let jsonDateFormatter: NSDateFormatter = {
        let dateFormatter = NSDateFormatter()
        dateFormatter.dateFormat = "yyyy-MM-dd"
        return dateFormatter
    }()
    private func toNSDate(dateString: String) -> Decoded<NSDate> {
        return .fromOptional(jsonDateFormatter.dateFromString(dateString))
    }
    
    init(timestamp: NSDate, activityId: String, type: ActivityProgressRecordType, properties: [String:String])
    {
        self.timestamp = timestamp
        self.activityId = activityId
        self.type = type
        self.properties = properties
    }
    
    static func decode(j: JSON) -> Decoded<ActivityProgressRecord>
    {
        return curry(ActivityProgressRecord.init)
            <^> (j <| "timestamp" >>- toNSDate)
            <*> j <| "activityId"
            <*> j <| "type"
            <*> (j <| "properties" >>- { [String:String].decode($0) })
    }
}

> 

The compiler complains with the usual 'Cannot invoke 'curry' with an argument list'. I know this is directly related to the timestamp currying. Any ideas?

**Comment by tonyd256** [comment]
It looks pretty good. I'm worried that it's actually having trouble with the last statement. What if you tried typing that closure to take in a `JSON` type?
