### ISSUE TITLE
Is dynamic typing possible?

### ISSUE THREAD

**Issue by Torsph** [thoughtbot/Argo#143]
Hi!

Im new to the lib and new to swift (but have done a lot of objective-c). I Like the lib very much, but its some things I cannot get to work.

Is it possible to handle dynamic types? Example when you get filters from the API
```
struct Filter {
    let currentValue: AnyObject
    let validValues: [AnyObject]
}
```
You may have q="Some string value", page=2 and sort="new".
Sort will have "currentValue="new"" and validValues=["old", "popular", "new"]

Thanks in advance!

**Comment by tonyd256** [comment]
@Torsph, short answer, no you can't go to an `AnyObject`. However, I don't think you want that. If you just type those as `String` instead of `AnyObject` you should be fine. Do you have a use case where you need different types in that array?

**Comment by Torsph** [comment]
It can be of type ```String```and ``Ìnt```. But I think I rather try to change the ``Ìnt```to ```String```instead :) Thanks!

**Comment by jferris** [comment]
You could also get an instance of `Decoded<JSON>`, and then `switch` on that, right?
