### ISSUE TITLE
Class cluster?

### ISSUE THREAD

**Issue by marcelofabri** [thoughtbot/Argo#144]
Is there a way to do class cluster like [Mantle](https://github.com/Mantle/Mantle) does via `+classForParsingJSONDictionary:`?

Or would you suggest a different approach? Maybe an `Either<T, U>` struct (with `T` and `U` being `Decodable`)?

**Comment by tonyd256** [comment]
I don't see why class clusters wouldn't work. As long as your common class implements `decode` in a way that checks to see which class to use then calls down to that class' `decode` function. Do you have a specific example?

**Comment by marcelofabri** [comment]
Yeah, I see it now. Maybe it was late at night :)
