### ISSUE TITLE
Argo doesn't work with subclasses, neither in Swift 1.2 or 2.0.

### ISSUE THREAD

**Issue by NicholasTD07** [thoughtbot/Argo#145]
When both super class and subclass conforms to the `Decodable` protocol,
neither Swift 1.2 or 2.0 can find the overload for the `decode` function in the subclass.

I think this is more of an issue of the Swift compiler, rather than Argo itself. But still, it would be better if this is documented somewhere in Argo for people to know this wouldn't work without spending their time trying to figure out what's wrong. What do you think?

See the errors that Swift complains, they are marked by "ERROR" in comments in the code snippet below.

##### Versions:
* Swift 1.2, Xcode 6.3.2, Argo 9d55345 "Update Playground examples"
* Swift 2.0, Xcode 7.0 beta, Argo 651568b "Embrace naming conventions"

##### PS.

For the simplicity, I put all the code in a test file.

To see the errors in Xcode, you can create a new swift file in ArgoTests and paste this in and try to compile for test target.

```swift
import XCTest
import Argo
import Runes

class SuperClass {
  let something: String

  init(something: String) {
    self.something = something
  }
}

extension SuperClass: Decodable {
  static func create(something: String) -> SuperClass {
    return SuperClass(something: something)
  }

  static func decode(j: JSON) -> Decoded<SuperClass> {
    return SuperClass.create
      <^> j <| "something"
  }
}

class SubClass: SuperClass {
  let someOtherThing: String

  init(something: String, someOtherThing: String) {
    self.someOtherThing = someOtherThing
    super.init(something: something)
  }
}

//extension SubClass: Decodable {
// ERROR in the line above:
// * Swift 1.2: Type 'SubClass' does not conform to protocol 'Decodable'
// * Swift 2.0: Redundant conformance of 'SubClass' to protocol 'Decodable'

extension SubClass {
  static func create(something: String)(someOtherThing: String) -> SubClass {
    return SubClass(something: something, someOtherThing: someOtherThing)
  }

  static func decode(j: JSON) -> Decoded<SubClass> {
    return SubClass.create
      <^> j <| "something"
      <*> j <| "some_other_thing"
  }
}

class DecodingTests: XCTestCase {
  func testDecodingSuperClass() {
    let model: SuperClass? = JSONFromFile("super_class") >>- decode

    XCTAssert(model != nil)
    XCTAssert(model?.something == "Something")
  }

  func testDecodingSubClass() {
    // ERROR in the line below comments
    // for both Swift 1.2 and 2.0:
    // Could not find an overload that accepts the supplied argument
    let model: SubClass? = JSONFromFile("sub_class") >>- decode

    XCTAssert(model != nil)
    XCTAssert(model?.something == "Something")
    XCTAssert(model?.someOtherThing == "Some other thing")
  }
}
```

The gist contains the code above, plus two simple json files.
https://gist.github.com/NicholasTD07/5320dbb9c5613bb9398b

**Comment by tonyd256** [comment]
@NicholasTD07 Hey man you were very close. With subclasses, you'll have to redefine the `typealias` on the `Decodable` protocol so your subclass extension should look like this:

```swift
extension SubClass: Decodable {
  typealias DecodedType = SubClass
...
```

**Comment by NicholasTD07** [comment]
Wow, I was really close. Thank you. 



—
