### ISSUE TITLE
How to parse JSON array

### ISSUE THREAD

**Issue by zhukovme** [thoughtbot/Argo#148]
I  have a json structure like this:

```json
{
  "positions": [ [1.23, 4.56], [7.89, 10.111] ]
}
```

And I have structures

```swift
struct Data {
    let positions: [LatLon]
}

struct LatLon {
    let latitude: Double
    let longitude: Double
}
```

How can I parse this json to my structures?

**Comment by tonyd256** [comment]
If you make both of those `Decodable` it will be rather simple. `Data` will just have to do `{ Data($0) } <^> j <| "positions"` then in the `LatLon` `decode` function, check to see if the `JSON` is an `.Array` and pull out the top two values .. would probably do something like this to be safe:

```swift
```

**Comment by tonyd256** [comment]
```swift
extension LatLon: Decodable {
  static func create( ... ) -> LatLon

  static func decode(j: JSON) -> Decoded<LatLon> {
    switch j {
    case let .Array(a): return LatLon.create
      <^> .fromOptional(a.first).flatMap(Double.decode)
      <*> .fromOptional(a.last).flatMap(Double.decode)
    default: return .TypeMismatch("\(j) is not an Array")
    }
}
```
This will get it done; however, you have little guarantee that the array will have 2 values. I would recommend the LatLon's be more of an object as opposed to an array of 2 values.

**Comment by zhukovme** [comment]
Thanks a lot

**Comment by zhukovme** [comment]
Sorry, I'm newbie in swift :) I got an error at 
```Swift
<^> .fromOptional(a.first).flatMap(Double.decode)
```
with ` 'NSNumber' is not a subtype of 'Double'  `

**Comment by tonyd256** [comment]
@zhukovme Did this work for you? Saw that you reopened but couldn't get back to you till today.

**Comment by zhukovme** [comment]
@tonyd256 Yes, it works. Here is the right code for me:
```Swift
    static func decode(json: JSON) -> Decoded<LatLon> {
        switch json {
            case let .Array(a):
                return LatLon.create
                    <^> .fromOptional(Double.decode(a.first!).value)
                    <*> .fromOptional(Double.decode(a.last!).value)
            default:
                return .TypeMismatch("\(json) is not an Array")
        }
    }
```

**Comment by tonyd256** [comment]
@zhukovme Glad to hear it!  2 things though:

1. Calling `Double.decode` returns a `Decoded` type, then calling `.value` returns and `Optional` type, then calling `.fromOptional` returns a `Decoded` type again. You could probably just do this: `Double.decode(a.first!)`

2. The other thing is that `a.first!` and `a.last!` will crash if one of those arrays is empty. If you know that will always be an array of 2 values then that's fine. That statement above should have worked though if you wanted to be safe about unwrapping those values. If it didn't work let me know.

**Comment by zhukovme** [comment]
@tonyd256 Thanks! ```Double.decode(a.first!)``` works fine :)
