### ISSUE TITLE
Remove dependency on Foundation

### ISSUE THREAD

**Issue by gfontenot** [thoughtbot/Argo#149]
It would be nice if we were able to remove Foundation as a dependency. Given that Swift will be open source before too long, it would be nice if Argo could be platform-agnostic.

**Comment by gfontenot** [comment]
AFAIK, this is basically just removing our dependency on `NSNumber`

**Comment by sgoodwin** [comment]
We also get `NSJSONSerialization` and `NSData` from Foundation. Until there's a swift JSON-parsing library to replace `NSJSONSerialization` like how Ruby has stuff like `YAJL`, this might be tricky.

**Comment by gfontenot** [comment]
We aren't relying on `NSJSONSerialization` or `NSData` internally (AFAIK), so that's not really our concern. That would be a concern for whoever makes the `NSJSONSerialization` replacement.

**Comment by neilpa** [comment]
https://github.com/owensd/json-swift includes a mostly pure swift JSON parser.

**Comment by lukescott** [comment]
I just wrote/released this: https://github.com/webconnex/json-parser-swift

It has zero foundation dependencies. It also exposes the tokenization and parsing separately, if you need that. The parser itself has a `parse()` method that creates `Dictionary<String, Any>` and `Array<Any>` objects. It also has a `scan()` and `generate()` methods that exposes the tokens - which works just like the tokenizer, but also verifies the grammar is correct.

The parser is "complete", but not battle tested yet. I need to add some through tests. I have it working with Carthage.

**Comment by RLovelett** [comment]
With Swift now being open source we now know that Swift will include [Foundation](https://github.com/apple/swift-corelibs-foundation) and thus _will_ include an implementation for [`NSJSONSerialization`](https://github.com/apple/swift-corelibs-foundation/blob/master/Foundation/NSJSONSerialization.swift). It would be my opinion that this issue is now over come by events and can safely be closed.

Just thought I'd point it out.

**Comment by gilesvangruisen** [comment]
My two cents: 

While its true that this is no longer _required_ for Argo to be platform-agnostic, I still see immense value in removing a large dependency like Foundation.

I imagine there will be situations where one might want functional JSON parsing but doesn't want to import a large library like Foundation into your (non-Apple-product) Swift application.

**Comment by paulyoung** [comment]
Based on [this thread in the mailing list](https://lists.swift.org/pipermail/swift-corelibs-dev/2015-December/000054.html) it seems like there's still work to be done in that area.

**Comment by gfontenot** [comment]
FWIW, our dependency is _not_ on `NSJSONSerialization`, it's on `NSNumber`.

**Comment by tonyd256** [comment]
Right, so specifically `NSNumber` but also because that's what `NSJSONSerialization` is returning for all numbers and bools. It would be nice if the new Swift Foundation `NSJSONSerialization` used the real types for those instead of the objc types.

**Comment by tonyd256** [comment]
Even more specifically, the fact that `Bool` is internally stored as a `NSNumber` means that any number can be a bool and any bool can be a number which breaks programming in general.

**Comment by paulyoung** [comment]
There is some mention of this in the commits and Jira issues in that mailing list entry, although nothing yet that specifically helps here.

**Comment by gfontenot** [comment]
With the new cross-platform Foundation stuff, I'm not sure that this is an issue. I'm going to close this for now. If we want to do this down the line for a specific reason, we can reopen.
