### ISSUE TITLE
Switch from custom `Decoded<T>` type to `Result<T: Decodable, DecodingError>`?

### ISSUE THREAD

**Issue by gfontenot** [thoughtbot/Argo#151]
I don't remember why we decided not to do this originally, but I think it was around needing multiple error states. Maybe we could get around this with our own error enum:

```swift
enum DecodingError {
  case TypeMismatch(String)
  case MissingKey(String)
}
```

Right now, `Decoded` is kind of a more specialized, less powerful `Result` anyway. Moving to `Result` (and keeping our `Optional` version of `decode`) might end up being a more flexible, more reusable return type.

**Comment by neilpa** [comment]
:+1: for an error specific enum. This will be needed whether switching to `Result` or `throws (or both). `Result` also composes nicely with other frameworks that use it (e.g. RAC).

**Comment by tonyd256** [comment]
In general I like this, my only concern here is using a Result framework that clashes with others. I know Rob's Result has become the "go to" one but if someone wanted to use their own then ours would clash with theirs. A pro for having our own Result-ish type is that we can have it 1. be minimal, 2. be dependency free and 3. not be making 3rd party framework choices for users of Argo.

I also see the cons of having an unfamiliar type, easy composability with other people using that Result, and not having to maintain our own Result-ish type.

I'm all for the enum abstraction, but I'm torn on the Result dependency. I'd love to hear other opinions on this matter from Argo users.

**Comment by gfontenot** [comment]
I think it's probably better for us to have a type that fits in well with _some_ (if not _all_) users, than a type that doesn't fit in with _any_ users. Right now, _everyone_ would have to convert from `Decoded` to `Result`, whereas if we use `Result.Result`, the worst case is _some_ people have to convert to `LlamaKit.Result` (or whatever).

**Comment by jferris** [comment]
One potential reason to keep your own top-level type (`Decoded`) is to allow for other extensions. One likely extension for Argo would be to add state to the parser. For example, you could cache parse results for each key in order to avoid unnecessary, duplicate computations.

**Comment by neilpa** [comment]
> One potential reason to keep your own top-level type (Decoded) is to allow for other extensions. 

It's already easy to extend existing types. Swift 2 also fixes a big pain point here by allowing frameworks to publicly extend generic types.

> One likely extension for Argo would be to add state to the parser. For example, you could cache parse results for each key in order to avoid unnecessary, duplicate computations.

:-1: This can be solved in a number of other ways without baking it into the library directly.

**Comment by RuiAAPeres** [comment]
> Right now, everyone would have to convert from Decoded to Result

Doing that right now.

**Comment by gfontenot** [comment]
I think we should _not_ do this at this point. Using `Result` directly would be nice, but we'd lose the ability to do more complex things with our `Decoded` type.

I do think we should look into simplifying our `Decoded` type to be more Result-ish. This will make transformations trivial, as well as improving support for things like `throws`.

**Comment by gfontenot** [comment]
I'm going to close this in favor of #210
