### ISSUE TITLE
Composing a single value from an Object

### ISSUE THREAD

**Issue by jshier** [thoughtbot/Argo#154]
First, thanks a lot for the provided Playgrounds, it made developing this solution much easier.

I'm attempting to compose a single value from an Object. For instance, take this JSON:
```
{ "URL": {"scheme" : "http", "path" : "apple.com"}}
```
I want to create an NSURL out of these parts. I've come up with this extremely inelegant code:
```swift
let toMultipartNSURL: JSON -> Decoded<NSURL> = {
    switch $0 {
    case .Object(let dict):
        if let schemeObject = dict["scheme"],
           let pathObject = dict["path"] {
            switch (schemeObject, pathObject) {
            case (.String(let scheme), .String(let path)):
                return .fromOptional(NSURL(string: "\(scheme)://\(path)"))
            default:
                return .TypeMismatch("Could not compose URL from parts.") 
            }
        }
        else {
            return .TypeMismatch("Could not compose URL from parts.")
        }
    default:
        return .TypeMismatch("Could not compose URL from parts.")
    }
}
```
There must be a better way. What's the recommended way to accomplish this?

Also, I've written the following to deal with strings that should be booleans:
```swift
let toBool: String -> Decoded<Bool> = {
    switch $0 {
        case "Y", "true":
        return decode(true)
    default:
        return decode(false)
    }
}
```
Seems odd to have to decode literal values, but I see no other way to get the `Decoded` result. I suppose for the default I could return a type error instead and look for specific false values, so I'm actually using `Decoded` for something. Which leads to another question, is there a suggested way to add my own error states?

**Comment by alskipp** [comment]
This might not be exactly what you had in mind – but it's an option : )

```swift
struct URLContainer {
  let scheme: String
  let path: String
  
  var url: NSURL? {
    return NSURL(string: "\(scheme)://\(path)")
  }
}

extension URLContainer: Decodable  {
  static func create(scheme: String)(path: String) -> URLContainer {
    return URLContainer(scheme: scheme, path: path)
  }
  
  static func decode(j: JSON) -> Decoded<URLContainer> {
    return create
      <^> j <| "scheme"
      <*> j <| "path"
  }
}

let url: URLContainer? = JSONFromFile("apple_url")?["URL"] >>- decode
println(url?.url) // "Optional(http://apple.com)"
```

I've tested it in a Playground file by adding the `apple_url.json` to the `Resources` folder.

**Comment by tonyd256** [comment]
@jshier Similar to what @alskipp is saying, I would make `NSURL` conform to `Decodable` and implement it like so:

```swift
extension NSURL: Decodable {
  typealias DecodedType = NSURL

  static func create(scheme: String)(path: String) -> NSURL {
    return NSURL(string: "\(scheme)://\(path)") ?? NSURL() // some default value
  }

  static func decode(j: JSON) -> Decoded<NSURL> {
    return create
      <^> j <| "scheme"
      <*> j <| "path"
  }
}
```

As far as custom error states, there is no way to override what `Decoded` is doing, but you can add another overloaded `decode` global function. Right now there are 2 of them ... one returns `A?` and the other `Decoded<A>`. You could make another that transforms the `Decoded<A>` into a different type (e.g. `Result`) and create your own errors based off of the `Decoded` ones.

Hope that helps.

**Comment by alskipp** [comment]
Of course! The `create` function doesn't need to initialise properties (I had a blind spot there, hence the use of a custom struct). 
Cheers @tonyd256

**Comment by jshier** [comment]
@alskipp @tonyd256 If I add `Decodable` support to `NSURL` with a two part initializer, wouldn't that mean I could add `Decodable` support for just a single string? Granted, the `toNSURL` function works fine in that case, it just seems limiting to have to do it that way. But it seems more elegant than my function solution. 

In general, is there a better implementation of my `toMultipartNSURL` function? In case I have multiple representations I need to map to the same type (already seen in the API I'm currently working with, which has "Y", "true", and "1" as boolean representations, and no actual JSON booleans). 

Also, is there any desire to have a standard set of transform functions (or whatever you want to call them) included in Argo? Things like `String -> NSURL` or 'String -> Int` (which I'll have to write too)? They'd be very useful but I feel like you may consider them out of scope.

**Comment by tonyd256** [comment]
We've decided to leave those types of transform functions up to the user. And yes you're right, implementing `NSURL: Decodable` with 2 strings would be limiting. You can make a function that constructs a `NSURL` with those 2 strings like so:

```swift
extension NSURL {
  static func decodeWithScheme(j: JSON) -> Decoded<NSURL> {
    let url: Decoded<NSURL?> = { NSURL(string: "\($0)://\($1)") }
      <^> j <| "scheme"
      <*> j <| "path"
    
    switch url {
    case let .Success(x): return .fromOptional(x.value)
    case let .TypeMismatch(s): return .TypeMismatch(s)
    case let .MissingKey(s): return .MissingKey(s)
    }
  }
}
```
Then in your decode function:
```swift
static func decode(j: JSON) -> Decoded<SomeType> {
  return SomeType.create
    <^> ...
    <*> (j <| "URL" >>- NSURL.decodeWithScheme)
    ...
}
```
I think this should work.

**Comment by tonyd256** [comment]
@jshier Did this end up working for you?

**Comment by jshier** [comment]
Since my data wasn't actually a URL (it was just an example), I was able to avoid this issue by pulling only one field out of it and transforming it directly (imagine a temperature represented by value and unit where the unit is only ever fahrenheit). Thanks though, I'll keep this in mind, and if I have trouble I'll add another comment.

**Comment by tonyd256** [comment]
@jshier Sounds good. I'll close for now. Feel free to comment here again or open new issues for other questions.

**Comment by jshier** [comment]
@tonyd256 As part of my solution for #177, I'm attempting to use the strategy you outlined to create decode function for `CLLocationCoordinate2D`. I've already created a separate extension that implements `decode` normally, for the case where I get an object that contains latitude and longitude. This function will serve the same purpose but for different keys and using my potential solution to #177 to get the values. However, I can't quite get the types right.
```swift
extension CLLocationCoordinate2D {
    static func decodeWithJSON(j: JSON) -> Decoded<CLLocationCoordinate2D> {
        let location: Decoded<CLLocationCoordinate2D> = {
            if let latitude = $0.value,
               longitude = $1.value {
                return pure(CLLocationCoordinate2D(latitude: latitude, longitude: longitude))
            }
            else {
                return .TypeMismatch("Could not decode CLLocationCoordinate2D")
            }
        }
            <^> (j <| "poiLat" >>- toDouble)
            <*> (j <| "poiLon" >>- toDouble)
        
        return location
    }
}
```
This code results in a "Could not find an overload for `>>-` that accepts the supplied arguments", which I'm guessing is just covering up the real error, since `toDouble` works fine (`String -> Decoded<Double>`).

**Comment by jshier** [comment]
Got it working by creating a separate `decodeFrom*` function and calling it directly (`CLLocationCoordinate2D.decodeFromModel(json)`.
```swift
extension CLLocationCoordinate2D {
    static func decodeFromPOI(j: JSON) -> Decoded<CLLocationCoordinate2D> {
        return curry(self.init)
            <^> (j <| "lat" >>- toDouble)
            <*> (j <| "lon" >>- toDouble)
    }
}
```

**Comment by tonyd256** [comment]
@jshier Let's keep this conversation in #177 as not to confuse a possible follower or later visiter.
