### ISSUE TITLE
Operator for either two key paths?

### ISSUE THREAD

**Issue by terhechte** [thoughtbot/Argo#155]
Hey, I'm consuming an API which (due to schema changes over the time) has multiple cases where a value can be either in key path 1, or in key path 2 depending on when the requested resource was created. I.e .older objects may have a value encoded like this:
`{"caption": "string"}`
and newer objects have it like this:
`{"caption": {"text": "string"}}`

It would be great to have an operator in Argo that would allow to define two key paths and it would try the first, and if that one does not exist, try the second. I.e. something along the lines of:

```
public func <|?! <A where A: Decodable, A == A.DecodedType>(json: JSON, keys: ([String], [String])) -> Decoded<A> {
    return (flatReduce(keys.0, initial: json, combine: decodedJSONForKey) ??
             flatReduce(keys.1, initial: json, combine: decodedJSONForKey)) >>- A.decode
}
```

Right now, I'm simply querying both paths, and then have the selection logic in the create function. However this kind of separates the parsing of this particular artifact, and moves it into the model:

```
struct t {
  func create(text1: String?)(text2: String?) -> t {
   let text = text1 ?? text2
  ...
 }
}
```

So I do have a solution, but I was just wondering if it makes sense to include such an operator.

**Comment by tonyd256** [comment]
I don't think adding a new operator is the right thing here. It's hard to say without more info, but I think you want something like this in your model's `decode` function:
```swift
<*> (j <| "caption") ?? (j <| ["caption", "text"])
```
However, we haven't implemented `??` for `Decoded`. If you think this is what you want then I would love to see a PR to add this.

**Comment by terhechte** [comment]
Hey, I've implemented such an operator and created a pull request here:
https://github.com/thoughtbot/Argo/pull/157
