### ISSUE TITLE
Extracting single value yields error

### ISSUE THREAD

**Issue by eimantas** [thoughtbot/Argo#156]
I'm attempting to extract a single value out of json in `decode` function. Doing so in two ways yields an error

```
let foo: String = json <| "foo" # Binary operator '<|' cannot be applied to operands of type 'JSON' and 'String'

let bar: String = json["bar"] # 'JSON' does not have a member named 'subscript'
```

I'm using Argo 1.0.3 with Swift 1.2 / Xcode 6.3.2.

**Comment by tonyd256** [comment]
The `<|` operator returns `Decoded<T>`. If you'd like to pull out the `String` and don't care about the error state you could call `.value` like so: `let foo: String? = (json <| "foo").value`

**Comment by eimantas** [comment]
Thanks, it'd be good to add this information to README.

**Comment by tonyd256** [comment]
@eimantas glad that worked for you. We're trying to get better documentation done all the time, but it's slow going.
