### ISSUE TITLE
Polymorphic decoding?

### ISSUE THREAD

**Issue by eimantas** [thoughtbot/Argo#158]
Say I have a class that has a number of subclasses (finite, known). Now I'd like to map those subclasses to received JSON, however the JSON for different subclasses arrives under same key. The general structure would look something like this:

```json
{
  "children": [
    {
      "id": 1,
      "name": "Foo",
      "attributeA": "Bar",
      "type": "ChildA",
    },
    {
      "id": 2,
      "name": "Baz",
      "attributeA": "Quux",
      "type": "ChildA"
    },
    {
      "id": 3,
      "name": "Lorem",
      "attributeB": "Ipsum",
      "type": "ChildB"
    }
  ]
}
```

I have a parent class, that has common properties (like `id` and `name`):

```swift
class Parent {
    let id: Int
    let name: String
}
```

and a few child classes:

```swift
class ChildA: Parent {
    typealias DecodedType = ChildA
    let attributeA: String
}

class ChildB: Parent {
    typealias DecodedType = ChildB
    let attributeB: String
}
```

Every child class have different attributes. I have no problem writing `Decodable` extensions for subclasses, however the part where I trip up is implementing `Decodable` for parent class. Each of the child's payload has a `type` key that basically maps to subclasses. This is how decodable looks for parent class:

```swift
enum ChildType {
    case ChildA, ChildB

    init(_ type: String) {
        switch (type) {
        case "ChildA":
            self = .ChildA
        case "ChildB":
            self = .ChildB
      }
}

extension Parent: Decodable {
    static func decode<T: Decodable>(json: JSON) -> Decoded<T> {
        let type : String = (json <| "type").value!
        let typeClass = ChildType(type)
        switch typeClass {
        case .ChildA:
            return ChildA.decode(json)
        case .ChildB:
            return ChildB.decode(json)
        }
    }
}
```

Now syntactically it's correct. But each time I try to build I segfault the compiler. My gut says that I have done something wrong with `Parent`'s `decode` function (because it returns a generic decoded type which is probably nonsense). Any help is much appreciated.

**Comment by tonyd256** [comment]
Hmm this is an insteresting case. It would be nice if every element in the array was the same child type, then decoding would be easy. With them all being different you'll have to decode the array as a `[Parent]`. Your `decode` function on `Parent` should figure out which child to call `decode` on then execute that. It looks like you've done that. I think the type signature of `decode` should look like this: `static func decode(j: JSON) -> Decoded<Parent>`

**Comment by eimantas** [comment]
I did try using

```swift
static func decode(j: JSON) -> Decoded<Parent>
```
for `Parent` class, but then I get the error saying

 ```
Decoded<ChildA> cannot be converted to Decoded<Parent>
```

when returning decodable subclasses in parent's `decode` function.

**Comment by eimantas** [comment]
I changed this to your suggested signature, but now I get a EXC_BAD_ACCESS when executing the code because of recursion that is 'caused by parsing the child from Parent's class:

1. give child's JSON to a parent's class
2. parent tries to parse the child and passes JSON to child's class: ChildA.decode(son)
3. for some reason the class that get's the call is parent, not ChildA.
4. Go to step 1.

**Comment by tonyd256** [comment]
@eimantas It's been a while since your last message. Are you still having this issue?

**Comment by eimantas** [comment]
I am not sure if it's still present. I have migrated my usage down to array of homogenous elements. Thus now listings are only for `[ChildrenA]` or `[ChildrenB]`.

I would still be interested in seeing it working (best as a decoding example in Argo's readme).

**Comment by tonyd256** [comment]
Sounds good. I think that's easier anyways and is how we intend Argo to work. I'd also be interested in what this might look like. I'll close this for now and we'll look into an example of this later.
