### ISSUE TITLE
Replace curried creation function by object's initializer 

### ISSUE THREAD

**Issue by dmcrodrigues** [thoughtbot/Argo#159]
With the last beta of Xcode, initializers can now be referenced like static methods using `.init`. This opens the possibility to drop the curried creation function and use the initializer already offered to us by `struct`'s which can make Argo much more concise and elegant.

The future integration in a model could simply be like this.

```swift
struct User {
  let id: Int
  let name: String
  let email: String?
  let role: Role
  let companyName: String
  let friends: [User]
}

extension User: Decodable {
  static func decode(j: JSON) -> Decoded<User> {
    return User.init
      <^> j <| "id"
      <*> j <| "name"
      <*> j <|? "email"
      <*> j <| "role"
      <*> j <| ["company", "name"]
      <*> j <|| "friends"
  }
}
````

**Comment by tonyd256** [comment]
This is already implemented in the swift 2.0 branch. Although you still need `curry`. Closing this but feel free to open an issue if you need help with something specific.

**Comment by tonyd256** [comment]
https://github.com/thoughtbot/Argo/blob/td-swift-2/ArgoTests/Models/User.swift

**Comment by dmcrodrigues** [comment]
Yeah sorry I missed the last commits. Fantastic! I really like Argo and it's really pleasant to see the activity and evolution. Thank you for the excellent work!

**Comment by tonyd256** [comment]
Thank you! Glad you like it!
