### ISSUE TITLE
Binary operator '<||' cannot be applied

### ISSUE THREAD

**Issue by RuiAAPeres** [thoughtbot/Argo#163]
I am trying to understand why I can't do this:

```
private func decode(json: JSON) -> Decoded<[Article]> {
    return json <|| "articles"    
}
```

The error:
```
Binary operator '<||' cannot be applied to operands of type 'JSON' and 'String'
```

**Comment by RuiAAPeres** [comment]
Changing it to this makes it work:

```
private func decode(json: JSON) -> Decoded<[JSON]> {
    return json <|| "articles"    
}
```

But my `Article` is compliant with the `Decodable` protocol.

**Comment by tonyd256** [comment]
@RuiAAPeres you should be able to do this. If you paste in the `Article` implementation I can try to help debug.

**Comment by RuiAAPeres** [comment]
@tonyd256 I didn't fully understand the lib, it's working now. 👍
