### ISSUE TITLE
Quick Question about code reuse

### ISSUE THREAD

**Issue by terhechte** [thoughtbot/Argo#168]
Hey, I wasn't sure how to contact you about this, so I decided to open an issue and close it soon afterwards. I've created a Swift library for using Value Types with CoreData. For this library I needed a way of decoding NSManagedObjects into value types, very similar to how Argo does it with JSON objects. So I've taken some inspirations from Argo but especially I've basically copied the curry.swift verbatim into said project. I hope that's ok with you? I didn't want to take all of Argo from Carthage as a dependency just for curry.swift. Maybe it'd be useful to add it to Runes, or make it a separate mini framework?

I'm, of course, mentioning Argo in the Readme. Still, I thought I'd let you know and ask for permission.

The project can be found here:
https://github.com/terhechte/CoreValue

Thanks!

**Comment by tonyd256** [comment]
@terhechte Curry is definitely very useful especially now that we'll have initializers as functions. We agree that you shouldn't have to import Argo to get `curry` so @gfontenot very recently created this: https://github.com/thoughtbot/Curry ... you can use it with carthage or submodules for now. It's really new so don't mind the lack of a README, we'll be getting to that.

I think many projects will benefit from `curry` and I hope a micro framework like this will help them.

**Comment by gfontenot** [comment]
Note that we haven't used `Curry.framework` as a dependency anywhere yet, so I'm unsure of the performance characteristics. If you _do_ end up using it as a dependency, I'd love feedback about how it's working. Feel free to open issues against that framework.

**Comment by terhechte** [comment]
Awesome, thanks. I'll give it a try and see if there're any performance changes compared to the current implementation that I'm using.
