### ISSUE TITLE
td-swift-2 branch won't build

### ISSUE THREAD

**Issue by gsimmons** [thoughtbot/Argo#169]
Checked out the project, switched to the branch, updated carthage, opened workspace. 4 build errors.

**Comment by tonyd256** [comment]
@gsimmons it might be related to #165

**Comment by gsimmons** [comment]
Yep, it is. Merged in that change manually and problem solved. I'll close this.

**Comment by tonyd256** [comment]
@gsimmons sounds good. I'm planning on merging that in today.
