### ISSUE TITLE
Cannot parse a JSON with an array in the root

### ISSUE THREAD

**Issue by yar1vn** [thoughtbot/Argo#17]
A temporary solution:

I created a wrapper struct, wrap the array in a dictionary ["Objects": json] and called <||"Object" in the decoder

**Comment by clayellis** [comment]
@gfontenot What is `JSONValue` in your example? It's still not entirely concrete for me what you're doing there.

**Comment by gfontenot** [comment]
@clayellis `JSONValue` was renamed to `JSON`.

The actual answer for this is a bit different now, I think. Assuming you have an array of `String` values:

```swift
let strings: [String]? = decodeArray(json).value
```

**Comment by AndyHT** [comment]
How can I process more complex json array like this:

```
[
 {
    "id": 1,
    "producation": "producation1"
    "tagName": "tag2",
    "status": false
 },
 {
    "id": 2,
    "producation": "producation2"
    "tagName": "tag2",
    "status": false
 }
 ]
```
