### ISSUE TITLE
Add debug mode

### ISSUE THREAD

**Issue by gsimmons** [thoughtbot/Argo#173]
It would be quite useful to be able to flip a switch and have any parse failures spit something out to the console indicating why it failed. As it is, it's great when it works and kind of a pain when it doesn't.

**Comment by tonyd256** [comment]
Not sure what this would look like. Currently, Argo is almost all purely functional, as in there are no side effects. I'd be worried that doing this would add some code bloat and introduce side effects.

It should be easy enough for you print the error message if you get one back. If it's not easy then maybe there is something we can do to make that easier.

**Comment by gsimmons** [comment]
I guess that's the issue. I don't get an error message, just a fully parsed set of objects, or nil. No indication of why it failed. I finally found a place where I could set a breakpoint to see that I had a type mismatch. Maybe that's what's needed - some documentation on where to look when things aren't working.

**Comment by tonyd256** [comment]
When you're decoding your object you usually do this `decode(jsonAnyObject)`. This function can return either an `Optional` or a `Decoded`. If you cast the result to an `Optional` then you will lose the error information. Instead, you could cast the return as a `Decoded` and check if it's a `.Success`. If not, print the error. I agree the documentation needs improvement and we've been slowing getting to that.

I'm going to close this for now. Feel free to keep commenting here if you have more questions about this or open new issues for other questions.

**Comment by gsimmons** [comment]
Ah, didn't know about that. Yes, that's useful in simpler cases. But in a complex case, "Number(1) is not a String" is not a huge help. Guess I'll stick with breakpoints on the important places I've found.

**Comment by gsimmons** [comment]
One more question: I've changed my code to this:
    let eval: Decoded<Template> = decode(jsonObject)
Now I'd like to switch eval to deal with what is coming back. But this doesn't work:
    case .Success:
nor does this:
    case .Success(_):
The only way I've got this to work is:
    case .Success(let unused):
        unused
which seems kind of silly. Am I missing a nuance of Swift.

**Comment by tonyd256** [comment]
I'm not sure what you mean. Could you give more code and/or context?

Generally speaking, say you want a `User` object. You decode it like so:
```swift
let user: Decoded<User> = decode(jsonObject)
```
Then you can check if successful or print the error like so:
```swift
switch(user) {
case let .Success(u): doSomething(u);
default: println(user)
}
```

**Comment by gsimmons** [comment]
In my case, I didn't need to do anything with u, so at first I wasn't doing the "let u" thing. I was just trying to check for .Success. I assumed that "case .Success:" would do it, but I guess not.

**Comment by tonyd256** [comment]
That should work ... what was the error you were getting?

**Comment by gsimmons** [comment]
No error, it just skipped over that case.

**Comment by tonyd256** [comment]
you would need a `break` or `return` after the `.Success:`

**Comment by gsimmons** [comment]
I had several statements. They were skipped. :)

**Comment by gfontenot** [comment]
@gsimmons We're having trouble following you. Can you post the actual code snippet, what you think should be happening, and what is happening?

**Comment by gsimmons** [comment]
Just went back and tested to make sure I was telling you the right thing. Either I'm crazy or Xcode did something weird before (no bets on which), but it works as expected to just have
case .Success:
    // some statements here

Sorry for the confusion.

**Comment by gfontenot** [comment]
No worries, glad it worked itself out!
