### ISSUE TITLE
Composing a single value from sibling values

### ISSUE THREAD

**Issue by jshier** [thoughtbot/Argo#177]
Similar but a bit different from #154. Imagine a response returns some location details, like POI information, including address, phone number, etc. Now imagine that, as part of this response, you're returned latitude and longitude, but they aren't contained in an object (I've already written a `CLLocationCoordinate2D` extension to make it `Decodable` from a containing object). So, something like this:
```json
{
	"poi" : {
		"address" : "blah",
		"latitude" : "55.00",
		"longitude" : "55.00"
	}
}
```
I've already written the string to double conversion function but I'm a bit at loss on how to write any sort of  mapping for `CLLocationCoordinate2D` that can take two sibling values. I'll post back if I come up with some sort of solution, but in the mean time, any ideas?

**Comment by jshier** [comment]
Well, I created an extension to `JSON` that returns a `JSON` composed of sub values of the original. The intention is to create a `.Object` that contains only the specified keys so a proper decode function can be written for them. Perhaps something similar can be done in a way that fits better with Argo's philosophy? I also couldn't get the `.reduce` based version to work, so it's commented out.
```swift
extension JSON {
    func subJSONWithKeys(keys: [Swift.String]) -> JSON {
        switch self {
        case let .Object(object):
            var intermediate: [Swift.String : JSON] = [:]
            for key in keys {
                if let value = object[key] {
                    intermediate[key] = value
                }
            }
            return .Object(intermediate)
//            keys.reduce([Swift.String : JSON], combine: { (var result, key) in
//                if let subobject = object[key] {
//                    result[key] = subobject
//                }
//                return result
//            })
        default:
            return .Null
        }
    }
}
```

**Comment by tonyd256** [comment]
@jshier Would you be able to provide the JSON you're trying to parse and the mode object you are trying to parse it into. Those would make it easier to help out. I think what you're saying doesn't have to be this involved but I need more info.

**Comment by jshier** [comment]
@tonyd256 I posted some sample JSON at the start of this issue. I'm trying to parse something similar to that (I didn't post all of the fields) into a POI model object, like this:
```swift
struct POI {
    let name: String
    let phoneNumber: String
    let zipCode: String
    let address: String
    let city: String
    let state: String
    let latitude: String
    let longitude: String
    let website: NSURL
}

extension POI : Decodable {
    static func decode(j: JSON) -> Decoded<POI> {
        return curry(POI.init)
            <*> j <| "name"
            <*> j <| "phone"
            <*> j <| "zip"
            <*> j <| "address"
            <*> j <| "city"
            <*> j <| "state"
            <*> j <| "latitude"
            <*> j <| "longitude"
			<*> (j <| "website" >>- toNSURL)
    }
}
```
However, I'd like to create a real `CLLocationCoordinate2D` from the latitude and longitude, rather than having them as strings or double values. Like I said, I've already created a decode extension for `CLLocationCoordinate2D` that can parse a dictionary, now I'm looking for something that can parse the lat / long from this sort of representation. I've also posted to #154, as the code I wrote to accomplish this based on the above solution wouldn't build.

**Comment by tonyd256** [comment]
Ah, that makes sense. You should be able to make `CLLocationCoordinate2D` conform to `Decodable` just like normal then replace the lat and lng lines above with just the decode function ... like so:

```swift
...
<*> j <| "state"
<*> CLLocationCoordinate2D.decode(j)
<*> (j <| "website" >>- toNSURL)
...
```

You might also be able to leave off the class name and just have `.decode(j)`. Not sure though.

**Comment by jshier** [comment]
@tonyd256 Brilliant! Works perfectly with the extra decode function I had to create, which I'll post to #154.

**Comment by tonyd256** [comment]
@jshier Why can't you make `CLLocationCoordinate2D` conform to `Decodable` and use that?

```swift
extension CLLocationCoordinate2D: Decodable {
  static func decode(j: JSON) -> Decoded<CLLocationCoordinate2D> {
    return curry(self.init)
      <^> (j <| "latitude" >>- toDouble)
      <*> (j <| "longitude" >>- toDouble)
  }
}
```

**Comment by jshier** [comment]
@tonyd256 Already have. Unfortunately the API I'm dealing with has multiple representation of locations. The other has slightly different strings for the lat/long, so I had to create multiples.

**Comment by tonyd256** [comment]
ah ok too bad. Glad this works for you then! Closing for now but feel free to comment again or create more issues for new questions.
