### ISSUE TITLE
Parsing arrays from objects with array values

### ISSUE THREAD

**Issue by jshier** [thoughtbot/Argo#180]
I'm trying to parse something like this:
```json
{
    "things": [
        {
            "thing1s": [
                {
                    "thing1attributes": "manyMore"
                },
                {
                    "thing1attributes": "manyMore"
                }
            ],
            "thing2s": [
                {
                    "thing2attributes": "manyMore"
                },
                {
                    "thing2attributes": "manyMore"
                }
            ],
            "thing3s": [
                {
                    "thing3attributes": "manyMore"
                },
                {
                    "thing3attributes": "manyMore"
                }
            ]
        }
    ]
}
```
into something like this:
```swift
struct Things {
    let thing1s: [thing1]
    let thing2s: [thing2]
    let thing3s: [thing3]
}
```
Apologies if the naming makes it more confusing. From the root "things" object, I need to grab the "thing1s" etc. arrays and map them to the arrays in my `Things` type. I having trouble translating from the initial array to the arrays of values for each type I expect. Once I have the intermediate mapping, it's just normal value parsing. In the future I may have more intermediate arrays to deal with, but I'll cross that bridge when I come to it.

**Comment by jshier** [comment]
I think I've come with a function that can strip the intermediate array.
```swift
let stripIntermediateArray: JSON -> JSON = {
    if case let .Array(array) = $0 {
        if let json = array.first {
            return json
        }
        else {
            return .Null
        }
    }
    else {
        return .Null
    }
}
```
Which theoretically gives me a `decode` for Things like this (just JSON representations right now:
```swift
struct Things {
    let thing1s: [JSON]
}

extension Things : Decodable {
    static func decode(j: JSON) -> Decoded<Things> {
        return (j <|| "things" >>- stripIntermediateArray) <|| "thing1s"
    }
}
```
I say theoretically since the Swift (beta 4) compiler crashes when trying to type check the return line.

**Comment by jshier** [comment]
Well, my crashing was due to some type mismatches I didn't see. My semi-final form:
```swift
func stripIntermediateArray(decodedJSON: Decoded<[JSON]>) -> JSON {
    if case let .Success(jsonArray) = decodedJSON {
        if let jsonValue = jsonArray.first {
            return jsonValue
        }
    }
    
    return .Null
}
```
With the decode:
```swift
extension Things : Decodable {
    static func decode(j: JSON) -> Decoded<Things> {
        let strippedJSON = stripIntermediateArray(j <|| "alertDetails")
        return curry(self.init)
            <^> strippedJSON <|| "thing1s"
            <*> strippedJSON <|| "thing2s"
            <*> strippedJSON <|| "thing3s"
    }
}
```

**Comment by tonyd256** [comment]
Hmm the naming is a bit tricky but it seems to me that you want an array of `Thing` like `[Thing]`. Then have the `Thing` model hold an array of `Attribute` like so:

```swift
struct Thing {
  let attributes: [[String: String]]
}
```

then write your `decode` function for thing like:

```swift
static func decode(j: JSON) -> Decoded<Thing> {
  switch j {
  case let .Array(a): curry(self.init) <^> sequence(a.map(Dictionary<String, String>.decode))
  default: return .TypeMismatch("\(j) is not an Array")
  }
```

This JSON format though is really weird. Might want to consider altering it if that's possible. Also, it seems that your `stripIntermediateArray` is ignoring everything but the first element in the array. If that's always they case then why have an array there?

**Comment by tonyd256** [comment]
@jshier Did that help? Any updates here?

**Comment by jshier** [comment]
Altering the JSON isn't possible, as I'm strictly a consumer. Once I get time to refactor I may try your implementation. Also, I confirmed that the first level array that I get back will only ever have one element (I know, but that's not nearly the worst thing about this API), so I don't need to do anything more than pull the array out. Thanks.
