### ISSUE TITLE
Does not compiles td-swift-2

### ISSUE THREAD

**Issue by volodg** [thoughtbot/Argo#182]
A lot of compilation errors: "Operator implementation without matching operator declaration"

in places like this - case let .Success(value): return value <^> self

**Comment by lowell** [comment]
Compiles fine and tests pass over here in both Xcode 7 b3 and b4.

Perhaps you might [be more specific](http://www.catb.org/esr/faqs/smart-questions.html#beprecise) with what you've tried so far, what you've tried it on, etc.

**Comment by gfontenot** [comment]
My bet is that you didn't run `bin/setup`, and so it hasn't pulled down the Runes source. We need to be more explicit about that in the readme and contributing guide.

**Comment by volodg** [comment]
you are using operator operator <^> a lot and it defined as 
public func >>- <A, B>(a: Decoded<A>, f: A -> Decoded<B>) -> Decoded<B> {
  return a.flatMap(f)
}
it's ok, but no such thing as - infix operator <^> which was declared within Runes lib, but you removed the Runes from podspec dependencies. Why?

**Comment by gfontenot** [comment]
I went into this fairly in-depth in [the PR that removed Runes as a framework dependency](https://github.com/thoughtbot/Argo/pull/174).

Regardless, this isn't an issue. If you run `bin/setup`, you _will_ get the operator definitions for `<^>`, `<*>`, `>>-`, etc.

**Comment by gfontenot** [comment]
Just realized you're using CocoaPods. We haven't cut a CocoaPods release for Swift 2.0 yet, because it isn't finalized. We'd rather that you didn't point at a WIP branch as a dependency.
