### ISSUE TITLE
Expression was too complex to be solved in reasonable time; consider breaking up into distinct sub-expressions

### ISSUE THREAD

**Issue by JonathanGrant** [thoughtbot/Argo#184]
Hello, I am trying to implement your library for the first time, and I've changed your tl;dr code on the read me to match my JSON file. You can see my file here: https://api.myjson.com/bins/2nkay

I get this error when I try to implement the decode function. Here is my code:
```
static func decode(j: JSON) -> Decoded<User> {
        return User.create
            <*> j <| "user_id"
            <*> j <| "first_name"
            <*> j <| "last_name"
            <*> j <| "password"
            <*> j <| "email_id"
            <*> j <| "dob"
            <*> j <| "picture"
            <*> j <| "street"
            <*> j <| "city"
            <*> j <| "state"
            <*> j <| "country"
            <*> j <| "zip"
            <*> j <| "sex" //I get the error on this line
    }
```

Just in case, here is my whole User file: 
```
mport Argo
import Runes
//import Foundation

struct User {
    let userID: String
    let firstName: String
    let lastName: String
    let password: String
    let emailID: String
    let dob: String //timestamp
    let picture: String //URL?
    let street: String
    let city: String
    let state: String
    let country: String
    let zip: String
    let sex: Character
}

extension User: Decodable {
    static func create(id: String)(firstName: String)(lastName: String)(password: String)(emailID: String)(dob: String)(picture: String)(street: String)(city: String)(state: String)(country: String)(zip: String)(sex: Character) -> User {
        return User(userID: id, firstName: firstName, lastName: lastName, password: password, emailID: emailID, dob: dob, picture: picture, street: street, city: city, state: state, country: country, zip: zip, sex: sex)
    }

    static func decode(j: JSON) -> Decoded<User> {
        return User.create
            <*> j <| "user_id"
            <*> j <| "first_name"
            <*> j <| "last_name"
            <*> j <| "password"
            <*> j <| "email_id"
            <*> j <| "dob"
            <*> j <| "picture"
            <*> j <| "street"
            <*> j <| "city"
            <*> j <| "state"
            <*> j <| "country"
            <*> j <| "zip"
            <*> j <| "sex"
    }
}```

**Comment by tonyd256** [comment]
This is a know issue. It's a limitation in the Swift compiler. The recommended ways to work around this is to make smaller models, which I think you could do if you pulled out the address stuff, or break up that decoding into smaller pieces. Please refer to these issues: #106 and #5

**Comment by tonyd256** [comment]
Feel free to keep using this thread for questions.

**Comment by JonathanGrant** [comment]
Thank you! I'll take out the address stuff because I don't need it right now. However, I have four other errors:  
```(null): Linker command failed with exit code 1 (use -v to see invocation)```
```Command /Applications/Xcode-beta.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1```
```Command /usr/bin/ditto failed with exit code 1```
```(null): Linker command failed with exit code 1 (use -v to see invocation)```
In other libraries installed with Cocoa pods, I solve this problem with Product->BuildFor->Testing. But that doesn't solve my problem this time.

**Comment by tonyd256** [comment]
I'd make sure all your dependencies are downloaded and linked properly. I can't tell what's wrong with just that error message. If there is more please open a new issue with the full message. Thanks!

**Comment by JonathanGrant** [comment]
Now it seems to be stuck on 'Building ArgoInstall: ArgoInstall'. I can't get my code to build because this won't finish.

**Comment by tonyd256** [comment]
You might need to take a look at your types and make sure they align. Looking above, you have the type `Character`. You need to make sure that it is `Decodable` or Argo won't work.
