### ISSUE TITLE
[question] Is there anyway to wrap decode?

### ISSUE THREAD

**Issue by d6u** [thoughtbot/Argo#186]
I want to do:

```swift 
func predecode<R: Decodable>(type: R.Type, data: AnyObject) -> R? {
    let r: Decoded<R> = decode(data) // Error: cannot find overload that accept an argument list of type '(AnyObject)`
    return r.value
}
```

The reason I want to do is easier error logging, so I don't have to put a debug message next to every decode call. But I cannot get away the error, what should I do? Thanks.

**Comment by ikesyo** [comment]
You should constrain the generic parameter as `R: Decodable where R == R.DecodedType` to match with the `decode()` function definition.

**Comment by d6u** [comment]
Thanks!
