### ISSUE TITLE
[question] cannot invoke 'decode' with an argument list of type '((AnyObject))'

### ISSUE THREAD

**Issue by Gagege** [thoughtbot/Argo#187]
Hi, I'm trying to get the decode function to work. I have a decode function that I think conforms to Decodable:

    static func decode(j: JSON) -> Decoded<User> {
        return User.create
            <^> j <| "id"
            <*> j <| "username"
            <*> j <| "access_token"
            <*> j <| "refresh_token"
            <*> j <| "token_type"
    }

Now I'm trying to call User.decode like this:

    let user:User? = User.decode(json)

The json object is an AnyObject from the Alamofire's responseJson callback. As far as I can tell my code matches all the Argo examples I've found, but I'm getting this error when I build:

    cannot invoke 'decode' with an argument list of type '((AnyObject))'

I'm using Swift 1.2 and Argo 1.0.3

**Comment by tonyd256** [comment]
The `decode` function takes

**Comment by tonyd256** [comment]
The `decode` function takes a `JSON` type and since your `json` variable is an `AnyObject`, this won't work. You can use `JSON.parse` to transform the `AnyObject` into a `JSON` type.

**Comment by tonyd256** [comment]
What I think you want is the global `decode` function. Use it like so: `let user: User? = decode(json)`

**Comment by Gagege** [comment]
Ah, thank you! That worked, I didn't catch that there was a global function.

**Comment by tonyd256** [comment]
No problem, glad that's all it was!
