### ISSUE TITLE
Latest version compatible with Swift 1.2?

### ISSUE THREAD

**Issue by paulyoung** [thoughtbot/Argo#190]
The README mentions Swift 1.1. and 0.3.x releases but says nothing about Swift 1.2

Am I correct in thinking that 0.4.x releases will be compatible with Swift 1.2, and 1.x.x releases will be compatible with Swift 2.0?

**Comment by paulyoung** [comment]
Looking at release dates, I think 1.0.4 might support Swift 1.2

**Comment by gfontenot** [comment]
Yep, sorry, we need to update the README. 1.x (and `master`, right now) is compatible with Swift 1.2. Swift 2.0 support is confined to a branch right now and is very much WIP.

**Comment by gfontenot** [comment]
To be clearer, when we support Swift 2.0, we will also be bumping Argo to 2.0 (in accordance with SemVer).
