### ISSUE TITLE
JSON enum missing Boolean case

### ISSUE THREAD

**Issue by paulyoung** [thoughtbot/Argo#191]
I'm curious as to why this is. Is it an oversight, or is `.Number` somehow supposed to cover it?

**Comment by gfontenot** [comment]
`.Number` covers the boolean case, because we're expecting this lib to be used with `NSJSONSerialization` which decodes `"foo": true` into `["foo": NSNumber(1)]`. I'd love for us to find a way to break `.Number` out into `.Float`, `.Integer`, and `.Bool`, but it hasn't been a super high priority.

**Comment by paulyoung** [comment]
Posting a link to https://github.com/edwardaux/Ogra/issues/18 for cross-reference.

@tonyd256 @gfontenot any thoughts on that?

**Comment by gfontenot** [comment]
Reopening this since it's technically an oversight and we can fix it. I might tackle breaking apart the `.Number` case next, assuming we can use the same technique.

**Comment by gfontenot** [comment]
Fix implemented in #314

**Comment by gfontenot** [comment]
This is fixed now!
