### ISSUE TITLE
Issue using partial application with curried initializer

### ISSUE THREAD

**Issue by paulyoung** [thoughtbot/Argo#193]
I'm using the same approach as in the [iTunes Example Playground](https://github.com/thoughtbot/Argo/blob/9d55345286f44c88a887083e18cef65627934fd6/Playgrounds/iTunes-Example.playground/Contents.swift#L58) to convert a `String` to a `NSDate`, like so:

```swift
extension App: Decodable  {
  ...
  
  static func decode(j: JSON) -> Decoded<App> {
    return create
      <^> j <| "trackName"
      <*> j <| "formattedPrice"
      <*> j <|? "averageUserRating"
      <*> (j <| "releaseDate" >>- toNSDate)
  }
}
```

However, I've also needed to break up the expression, similar to:

```swift
extension App: Decodable  {
  ...
  
  static func decode(j: JSON) -> Decoded<App> {
    let app = create
      <^> j <| "trackName"
      <*> j <| "formattedPrice"
    return app
      <*> j <|? "averageUserRating"
      <*> (j <| "releaseDate" >>- toNSDate)
  }
}
```

This results in the following error message:

```
Binary operator '<*>' cannot be applied to operands of type 'Decoded<NSDate -> App>' and 'Decoded<App>'
```

**Comment by tonyd256** [comment]
So there is a known issue with the Swift compiler. When the curried `create` function is broken up like that the type system gets weirded out and thinks that the type needed in the next part of the application needs to have the named argument as well. This can be fixed by placing `_`s before each named param in the create function. It's only needed for params that come after the split, so in your case `averageUserRating` and `releaseDate`.

**Comment by paulyoung** [comment]
I see...

I my case I'm actually doing `curry(self.init)`, so maybe this is actually a change that should be made in [thoughtbot/Curry](https://github.com/thoughtbot/Curry).

**Comment by tonyd256** [comment]
hmm interesting. I'll try it in the morning and see if that helps.

**Comment by paulyoung** [comment]
I still receive the same error when adding the following:

```swift
struct App {
  ...

  init(_ name: String, _ formattedPrice: String, _ averageUserRating: Float?, _ releaseDate: NSDate) {
    self.name = name
    self.formattedPrice = formattedPrice
    self.averageUserRating = averageUserRating
    self.releaseDate = releaseDate
}
```

**Comment by paulyoung** [comment]
I tried using a static `create` function as before, and the workaround for unnamed parameters doesn't seem to be working in Xcode 7 beta 5.

**Comment by paulyoung** [comment]
My mistake. The original workaround **does** work with `create`, except for when using it with a more complex expression like the one I'm using.

**Comment by paulyoung** [comment]
Some more info – in my codebase I'm actually doing this:

```swift
public func toNSDate(date: String) -> Decoded<NSDate> {
    return .fromOptional(jsonDateFormatter.dateFromString(date))
}

public func toNSDate(date: String?) -> Decoded<NSDate> {
    return .fromOptional(date >>- jsonDateFormatter.dateFromString)
}
```

I discovered that I can revert back to using `curry(self.init)` and everything works as expected when using a non-optional property of type `NSDate` after "the split".

The issue appears only to be when using the optional variant.

**Comment by tonyd256** [comment]
you should be able to have an optional `NSDate`. You might have to form is like this: `<*> .optional(j <| "releaseDate" >>- toNSDate)`

**Comment by paulyoung** [comment]
Thanks. That does work although doesn't look as pretty!

**Comment by tonyd256** [comment]
Great! Closing this for now. Feel free to keep commenting here if you have more questions on this or open new issues for other things.

**Comment by paulyoung** [comment]
I just ran into this one again and I'm still curious why `.optional` is (only) required after breaking up the expression.

For example:

```swift
public struct Foo {
    public let createdAt: NSDate?
    public let updatedAt: NSDate?
    
    public init(
        createdAt: NSDate? = .None,
        updatedAt: NSDate? = .None
    ) {
        self.createdAt = createdAt
        self.updatedAt = updatedAt
    }
}

extension Foo: Decodable {
    public static func decode(json: JSON) -> Decoded<Foo> {
        let f = curry(self.init)
            <^> (json <| "created_at" >>- toNSDate)
        return f
            <*> .optional(json <| "updated_at" >>- toNSDate)
    }
}
```

**Comment by gfontenot** [comment]
I'm not sure I understand the question. You can't just return that parser without first breaking it into two expressions?

**Comment by paulyoung** [comment]
This is a super slimmed down version of an expression with more properties in between.

I don't understand how I can get away with not using `.optional()` before the break but must use it afterwards.

**Comment by gfontenot** [comment]
You can always pass a non-optional decoding result (as in `Decoded<T>`) to an optional property, but you can _never_ pass an optional decoding result (as in `Decoded<T?>`) to a non-optional property.

The result of the code above is that if your first line fails, the whole parser will fail. Alternatively, if the second line (marked with `.optional()`) fails, the property will be set to `.None` and the parser will continue.

This is more about the complexities in the parser, rather than the use of partial application.

**Comment by paulyoung** [comment]
To clarify, I needed to add `.optional()` just to get things to compile.

Provided the expression isn't broken up (because it's "too complex"), this works just fine:

```swift
extension Foo: Decodable {
    public static func decode(json: JSON) -> Decoded<Foo> {
        return curry(self.init)
            <^> (json <| "created_at" >>- toNSDate)
            <*> (json <| "updated_at" >>- toNSDate)
    }
}
```

**Comment by gfontenot** [comment]
uhhhh. I have no idea. Seems like a bug in the currying stuff? Weird.

**Comment by paulyoung** [comment]
FWIW I tried this with a manually curried `create` function and still see the same behavior.

I even moved the expressions out and assigned them to constants to confirm that their type is `Decoded<NSDate>`.

The error is still `Cannot convert value of type 'Decoded<(NSDate?) -> Block>' (aka 'Decoded<Optional<NSDate> -> Block>') to expected argument type 'Decoded<_ -> _>'`

This is literally all I'm doing to get that error:

```diff
extension Foo: Decodable {
    public static func decode(json: JSON) -> Decoded<Foo> {
-        return curry(self.init)
+        let f = curry(self.init)
            <^> (json <| "created_at" >>- toNSDate)
+        return f
            <*> (json <| "updated_at" >>- toNSDate)
    }
}
```

**Comment by paulyoung** [comment]
The tooltip in Xcode shows `let f: Decoded<(NSDate?) -> Block>` as the declaration for `f`.

**Comment by gfontenot** [comment]
I wonder if this is related to #298

**Comment by paulyoung** [comment]
Filed this as https://bugs.swift.org/browse/SR-652 after talking to a couple of people on Twitter about it.

**Comment by paulyoung** [comment]
@gfontenot it doesn't look like it based on my example project since I'm only using the map and apply operators.

**Comment by paulyoung** [comment]
I just commented out everything in `DecodeOptional.swift` and still had the same issue.
