### ISSUE TITLE
Question: Delay parsing

### ISSUE THREAD

**Issue by thbaja** [thoughtbot/Argo#194]
Given a json structure like this, where the content of payload will vary:
```
{
"id": 99
"type": "request"
"payload": {"aaa": "bbb", "ccc": "ddd"}
}
```

Is there a way to put it into a struct like this, where the payload is "untouched":
````swift
struct MyMessage {
  let id: Int
  let type: String
  let payload: AnyObject
}
````
I would like to delay the parsing of the payload until later, where I will decide which struct to use for parsing based on the MyMessage.type.

**Comment by tonyd256** [comment]
This wouldn't work for AnyObject because it isn't Decodable and there isn't a way to go from JSON to AnyObject right now. It would probably be easiest to save payload as a JSON type then use that for decoding later.

**Comment by thbaja** [comment]
Thanks for your quick reply!

If I understand you correctly I should be able to do this (using `JSON` instead of `AnyObject` for `Payload`):
```swift
struct MyMessage {
  let type: String
  let payload: JSON
}

extension MyMessage: Decodable {    
    static func create(type: String)(payload: JSON) -> MyMessage {
        return MyMessage(name: name, payload: payload)
    }
    
    public static func decode(json: JSON) -> Decoded<MyMessage> {
        return MyMessage.create
        <^> json <| "type"
        <*> json <|? "payload"
    }
}
```

But how do I go about and decode the payload afterwards? 
From belov I get this `Cannot find an overload for 'decode' that accepts an argument list of type '(JSON)'`
```swift
struct Payload {
  let aaa: String
  let ccc: String
}

extension Payload: Decodable {
    static func create(aaa: String)(ccc: String) -> Payload {
        return Payload(aaa: aaa, ccc: ccc)
    }
    
    public static func decode(json: JSON) -> Decoded<Payload> {
        return Payload.create
        <^> json <| "aaa"
        <*> json <| "ccc"
    }
}
// Given some json in the form from the original question above.
let myMessage: MyMessage = decode(json)
let myPayload: Payload = decode(myMessage.payload)
```

**Comment by tonyd256** [comment]
Yup so first, only use <|? If the property is optional otherwise ditch the ? ... Since payload is JSON (not optional) you don't need the ? 

Then to use it, use the instance function instead: Payload.decode(myMessage.payload)

Excuse the lack of code blocks. I'm responding from an iPhone.

**Comment by thbaja** [comment]
Wow, impressive response time! :+1: Thanks!  :-)
The optionals sneaked in when c/p and editing in here, tried to keep it simple.

Ah, I see. And the debugger actually hinted me in that direction when trying to figure it out.
No need for code blocks.

**Comment by thbaja** [comment]
A little off-topic, but you mention that there isn't a way to go from JSON to AnyObject right now. 
Is there another way to make the payload in the struct encodable to JSON, since this wouldn't work:
```swift
extension MyMessage {
    public func encode() -> AnyObject {
        return ["type": type, "payload":payload]
    }
}
```

I can certainly work around it, just wanted to know if there  a shortcut I might have missed.

Thanks again for a great library! :+1:

**Comment by tonyd256** [comment]
Hmm ya I see what you're doing here. There isn't a way to have `JSON` got to `AnyObject` so this isn't straight forward. I would probably decode the `payload` then call `encode` on it. Then for each object that `payload` could decode to, also implement `encode` for that object and then this should work.
