### ISSUE TITLE
Pure Swift parser to replace NSJSONSerialization

### ISSUE THREAD

**Issue by lukescott** [thoughtbot/Argo#197]
I created a pure Swift parser: [json-parser-swift](https://github.com/webconnex/json-parser-swift). I just updated the API to expose the [ParserStateMachine](https://github.com/webconnex/json-parser-swift/blob/master/JSON/ParserState.swift#L11). This should be of particular interest to you guys because you can get validated tokens w/ state without creating intermediary Dictionary/Array objects during the decode process.

[Parser.swift](https://github.com/webconnex/json-parser-swift/blob/master/JSON/Parser.swift) is a good example of how to use it. It creates JSON.Value objects, which works similarly to SwiftyJSON.

Let me know what you guys think of the API, and let me know if I can make it any easier!

(I had made a comment on #149, but I figured I'd create a separate issue)

**Comment by tonyd256** [comment]
@lukescott Thanks man! This looks really cool. Looking forward to digging in deeper.
