### ISSUE TITLE
Is there any way to use JSON like this ?

### ISSUE THREAD

**Issue by alvinvarghese** [thoughtbot/Argo#199]
{
{"name":"alvin"},
{"name":"alvin"},
{"name":"alvin"},
{"name":"alvin"},
{"name":"alvin"}
}

Is there anyway to parse JSON like this ? In the example you have given in the GitHub ReadMe, You were saying that "user" must be needed to get each dictionary from the JSON. But in my case i don't have any key its just the plane and simple dictionary. I was just curious about this, cause i could not find any workaround this, I just wanted to know if anyone from this Argo community know how to parse this JSON. Please help me out here.

**Comment by tonyd256** [comment]
Interesting, is that valid json? I though objects needed key/value pairs. Is this just an array of objects?

**Comment by jshier** [comment]
What's your desired end result? In other words, what's your desired model object? An array names, or are all of these part of the same model?

**Comment by neilpa** [comment]
Nope, that's not valid JSON.

**Comment by jshier** [comment]
Would `NSJSONSerialization` still parse it with fragments enabled?

**Comment by alvinvarghese** [comment]
This is the URL -> http://thetopfives.net/thetopfivesposts

**Comment by alvinvarghese** [comment]
Or should i loop through all the dictionaries and apply Argo way to parse those values .?

**Comment by jshier** [comment]
I'm guessing your meant this then: 
```json
[
{"name":"alvin"},
{"name":"alvin"},
{"name":"alvin"},
{"name":"alvin"},
{"name":"alvin"}
]
```

**Comment by alvinvarghese** [comment]
Yes i was, Sorry about the parenthesis. Yes it was a bracket.

**Comment by alvinvarghese** [comment]
So what you guys think about this. Is this a valid JSON URL ? Or Argo still needs key to process this JSON ?

**Comment by tonyd256** [comment]
you should just be able to say `let users: Decoded<[User]> = decode(json)` where `json` is the `AnyObject` returned from `NSJSONSerialization`

**Comment by alvinvarghese** [comment]
//
//  DataFromServer.swift
//  The Top Fives
//
//  Created by Alvin Varghese on 8/25/15.
//  Copyright (c) 2015 The Top Fives. All rights reserved.
//

import UIKit
import Foundation
import Argo
import Runes

struct TheTopFivesData {
    
    let title : String
    let redirectUrl : String
    let discussionUrl : String
    let serialNumber : Int
    let color : String
    let newsSourceName : String
    let newsSourceId : Int
}

extension TheTopFivesData: Decodable {
    
    static func create(title: String)(redirectUrl: String)(discussionUrl: String)(serialNumber: Int)(color: String)(newsSourceName: String)(newsSourceId : Int) -> TheTopFivesData {
        
        return TheTopFivesData(title: title, redirectUrl: redirectUrl, discussionUrl: discussionUrl, serialNumber: serialNumber,color : color, newsSourceName: newsSourceName, newsSourceId: newsSourceId)
    }
    
    static func decode(j: JSON) -> Decoded<TheTopFivesData> {
        return TheTopFivesData.create
            <^> j <| "title"
            <*> j <| "redirectUrl"
            <*> j <| "discussionUrl"
            <*> j <| "serialNumber"
            <*> j <| "color"
            <*> j <| "newsSourceName"
            <*> j <| "newsSourceId"
    }
}

class DataFromServer: NSObject, NSURLConnectionDataDelegate, NSURLConnectionDelegate {
    
    //MARK: Local Variables
    
    var mutableData : NSMutableData!
    
    
    //MARK: Request for Data
    
    func requestData()
    {
        NSURLConnection(request: NSURLRequest(URL: NSURL(string: "http://thetopfives.net/thetopfivesposts")!), delegate: self, startImmediately: true)
    }
    
    //MARK: NSURLConnection Delegate
    
    func connection(connection: NSURLConnection, didReceiveResponse response: NSURLResponse)
    {
        self.mutableData = NSMutableData()
    }
    
    func connection(connection: NSURLConnection, didReceiveData data: NSData)
    {
        self.mutableData.appendData(data)
    }
    
    func connectionDidFinishLoading(connection: NSURLConnection)
    {
        // Wherever you receive JSON data:
        
        if let json: AnyObject? = NSJSONSerialization.JSONObjectWithData(self.mutableData, options: NSJSONReadingOptions(0), error: nil) {
            
            if let j: AnyObject = json {
                
                let allValues : Decoded<[TheTopFivesData]> = decode(j)
                
                println("COUNT : \(allValues.value?.count)") // prints COUNT : nil
            }
            else
            {
                println("NO DATA")
            }
            
        }
        else
        {
            println("NO JSON")
        }
        
        
    }
    
    func connection(connection: NSURLConnection, didFailWithError error: NSError)
    {
        utilitiesObjet.alertThis("Oh ho !!", message: "\(error.localizedDescription)")
    }
    
 }

**Comment by alvinvarghese** [comment]
I solved it, there was some optional values. Added optional value ? notation to the variables. Now its working fine. Thanks to all who spent their valuable time with me to make me re think on this.
