### ISSUE TITLE
Argo in Swift 2.0

### ISSUE THREAD

**Issue by alvinvarghese** [thoughtbot/Argo#207]
I integrated Argo with my project ( Swift 1.2, Xcode 6.4 ). I wanna move to the Xcode 7 beta 6, with Swift 2.0. I want to integrate argo with Swift 2.0. When i imported project to Xcode 7 beta 6, it suggested lot of code changes from Swift 1.2 to Swift 2.0. Which was really bad, i really could not understand what Xcode did to my project.

Could you please tell me that, which is the best way, updating via cocoapods ? Do i have to wait till the release of Xcode 7, Cause i decided that i will be taking Argo with my app to the production. So i don't want to waste time by integrating again and solving the bugs.

May i wait till the release of Xcode 7 ? or this Argo gonna behave the same without any problem in Xcode 7.

Suggest me your thoughts.

**Comment by ikesyo** [comment]
You should check #142, and you might be able to use the branch of that PR as following: 

```ruby
pod 'Argo', :git => 'https://github.com/thoughtbot/Argo.git', :branch => 'td-swift-2'
```

**Comment by alexkent** [comment]
I have an issue #203 with Cocoapods integration on the td-swift-2 branch.
I would be very interested to hear if you don't run into this!

**Comment by ikesyo** [comment]
Oh, I'm sorry. It seems that we should add `:submodules => true` to the entry above.

**Comment by alvinvarghese** [comment]
Okay, Let me update it, let you guys know :)

**Comment by alexkent** [comment]
aha, Cocoapods ignores the `submodules => true` in the .podspec when integrating with `:git => '...'`
As discussed here https://github.com/CocoaPods/CocoaPods/issues/2317

**Comment by paulyoung** [comment]
My understanding is that the dependency on Runes was removed in the `td-swift-2` branch.

**Comment by alexkent** [comment]
The dependency on including the entire Runes framework was removed. But a single "Runes.swift" files is still included (and necessary as it declares the custom operators) when building the `td-swift-2` branch.

The source files line in the podspec includes it:
`spec.source_files = 'Argo/**/*.{h,swift}', 'Carthage/Checkouts/Runes/Source/Runes.swift'`

**Comment by gfontenot** [comment]
yep, that's correct. We've removed Runes.framework as a dependency, but still rely on it as an internal dependency.

The snippet that @ikesyo pasted _should_ be correct. I'm going to close this for now, and if it's still an issue after using that format, please let me know. We will ship a proper pod once we've finalized support for Swift 2.0.

**Comment by jscubida** [comment]
Is there a reason that the `td-swift-2` branch is missing? I'm trying to integrate Argo in a Swift 2.0 app.

**Comment by paulyoung** [comment]
@jscubida it just got merged to master in #142

**Comment by jscubida** [comment]
@paulyoung Gotcha. Thanks!

**Comment by lyoshaprikhodko** [comment]
Good day. 
I’m using your Argo library in my project at work. 
For some reason Argo doesn't work in Swift 2.0. 
I use Carthage to update frameworks, and that is how Argo looks in my Cartfile.
github "thoughtbot/Argo»
Can you help me in updating it? I can’t find any info about new version or whatever.

**Comment by gfontenot** [comment]
@lyoshaprikhodko We haven't officially shipped Argo 2.0 (which will include Swift 2.0 support) yet, but you can point at `master` in your Cartfile:

```
github "thoughtbot/Argo" "master"
```

We should be officially releasing 2.0 soon.

**Comment by bonebox** [comment]
Has anyone gotten this to build successfully pointing to master from a Podfile?  I'm getting a lot of build errors.  I also tried it in a new project to make sure it wasn't my existing project, but it still fails.

**Comment by CWalig** [comment]
Same here. 
```
pod 'Argo', :git => 'https://github.com/thoughtbot/Argo', :branch => 'master'
```
mainly
```
Pods/Argo/Argo/Operators/DecodedOperators.swift:14:13: Operator implementation without matching operator declaration
```

**Comment by jscubida** [comment]
I found that the Runes file is missing. Runes.swift contains the operator declaration that its complaining about.

**Comment by tonyd256** [comment]
I just updated the podfile ... not sure if that helped

**Comment by jshier** [comment]
@tonyd256 Did you push trunk? I don't see 2.0.0 on CocoaPods yet.

**Comment by CWalig** [comment]
@tonyd256 nop. I just tried with in a new project.
@jscubida indeed.

**Comment by tonyd256** [comment]
I did not push to trunk ... let me go figure out how to do that haha

**Comment by tonyd256** [comment]
Ok Pushed!! Let me know if it doesn't work still

**Comment by jshier** [comment]
It does not. Perhaps something is broken with CocoaPods submodule support. Doesn't even work if you include the Runes pod.

**Comment by tonyd256** [comment]
I just created a new project and setup cocoapods then added `pod 'Argo'` ... then ran `pod install` and the project is building fine even with a bit of argo in it. What are you seeing as the specific error message?

**Comment by jshier** [comment]
Huh. I deleted my Pods directory and ran `pod update` again and now it works. Perhaps after the first failed attempt from GitHub directly, it didn't like it when I switched to the official pod version. Thanks.

**Comment by tonyd256** [comment]
huh ... well glad to hear it's working now!

**Comment by CWalig** [comment]
👍🎉Thanks.

**Comment by alvinvarghese** [comment]
It works for me in Swift 2.0, Didn't do anything except updating pods with iOS 9.0.
