### ISSUE TITLE
Decoded should support custom error states

### ISSUE THREAD

**Issue by jshier** [thoughtbot/Argo#211]
In all of the custom decoding I've had to do with the backend I'm current developing against, I've found myself rather limited by `.TypeMismatch` and `.MissingKey` being the only `Decoded` error states. I've started just returning `.TypeMismatch` with a custom string describing the issue, since `.TypeMismatch` comes closest to representing a custom decoding error. For example, if a `double` is being returned as a string and I want to convert it to be an actual `double`, I do this: 
```swift
let toDouble: String -> Decoded<Double> = {
    if let double = Double($0) {
        return pure(double)
    }
    else {
        return .TypeMismatch("Could not convert String \($0) to Double.")
    }
}
```
This gives me a little extra detail without having to examine the actual returned JSON. It'd be great if this was a supported state, like `.General` or `.Custom`. Better names are always good. :smile:  

I mentioned my concern in PR #210.

**Comment by gfontenot** [comment]
So this seems easy/reasonable enough. I don't have any real problem with it. My only question is whether it should be a "fatal" error or not?

Basically, we need to consider whether a failed decoding with a custom type should be considered a failure for an optional property. Right now, this is what we do:

```swift
public extension Decoded {
  static func optional<T>(x: Decoded<T>) -> Decoded<T?> {
    switch x {
    case let .Success(value): return .Success(.Some(value))
    case .Failure(.MissingKey): return .Success(.None)
    case let .Failure(.TypeMismatch(x)): return .Failure(.TypeMismatch(x))
    }
  }
```

Basically, we say that a missing key is actually fine, and that a type mismatch is a real failure. My gut says that custom failures should work like type mismatch failures, and so should be treated as "fatal" for optional values.

**Comment by jshier** [comment]
I agree, which is why I used `.TypeMismatch` as my equivalent for a custom error, as it seemed closest in intent, even if it didn't really describe the issues I could see in custom transformers.

Customization of which errors are fatal is yet another, small, issue I have with Argo. It would be nice to, say, decode an array and not have the decode fail because a single element failed to decode. But I'll raise that issue if I ever run into that requirement while using Argo.

**Comment by gfontenot** [comment]
>  It would be nice to, say, decode an array and not have the decode fail because a single element failed to decode.

Different issue, but fwiw that can be achieved on a case by case basis by using a different decoder.

Instead of using our decoder, which is basically `sequence(A.decode <^> a)` where `a` is the array, you could just do `catFailures(A.decode <^> a)`. That's a function that we could probably support along with our implementation of `sequence`, as well.

**Comment by paulyoung** [comment]
FWIW: https://github.com/thoughtbot/Argo/issues/109#issuecomment-93572717
