### ISSUE TITLE
Convert JSON field to enum value

### ISSUE THREAD

**Issue by Blackjacx** [thoughtbot/Argo#22]
Hey, 

can you give me please an example how I could parse a JSON when one of my struct fields is of an enum type? Lets take the following example:

    struct Money {
      let amount: String
      let currecy: CurrencyValue
    }

    enum CurrencyValue : String {
      case EUR = "EUR"
      case unknown = "unknown"
    }
	
The JSON keys are the same as the struct variable names amount and currency. I get the error 

    Type 'CurrencyValue' does not conform to protocol 'JSONDecodable'

How can I get rid of this? Can you give me an example how to make an enum conform to this protocol?

**Comment by tonyd256** [comment]
it should be as simple as just making it conform to that protocol. Make `CurrencyValue` conform to JSONDecodable and then implement the decode method for it.

**Comment by Blackjacx** [comment]
I have now this:

    extension CurrencyValue : JSONDecodable {
	    static func create(rawValue: String) -> CurrencyValue {
	  	    if let newValue = CurrencyValue(rawValue: rawValue) {
			    return newValue
		    }
		    return .unknown
	    }
	    
	    static func decode(j: JSONValue) -> CurrencyValue? {
		    return CurrencyValue.create
			    <^> j <|  "amount"
			    <*> j <|  "currency"
	    }
    }

But I fail somehow at the implementation of the decode method. I didn't get the Idea of that functional operators yet. Can you give me a tip?

**Comment by tonyd256** [comment]
so your `CurrencyValue` type is an enum that represents a single string. To create an instance of the enum you have written the `create` function that takes a single string and parses it into a `CurrencyValue` instance. Now in the `decode` function you want to create that `CurrencyValue` with the string in the `JSONValue` using the `create` method.

without getting into what fmap and apply mean ... since your create function takes one parameter you should only give it one parameter ... in this example you are trying to pass in 2 parameters.  Replace `"amount"` with `"currency"` and remove the second line.

**Comment by Blackjacx** [comment]
I tested this, but it didn't work. I now follow the idea to store whatever comes from the server as raw value and implement a parser function for every enum inside the model struct, to access the enum value... Maybe there is a more elegant solution to this.

The problem was probably that the JSONValue 'j' coming to decode() is already the value of the JSON field with the key _currency_, so there is nothing more to decode. I would just need to call the create function with the raw value. But then I think I circumvent the system and loose the error checking because I do not use the operators then... Am I at least a littl bit right :-D?

**Comment by tonyd256** [comment]
If `j` is already the value you want you could just do `return CurrencyValue.create <^> j.value()` or ` ... <^> String.decode(j)`

**Comment by Blackjacx** [comment]
Ahhh cool thank you very much :+1:

**Comment by tonyd256** [comment]
No problem. Closing this now.
