### ISSUE TITLE
More Advanced Example

### ISSUE THREAD

**Issue by RLovelett** [thoughtbot/Argo#223]
Given a JSON file that looks like:

```json
{
  "series": [
    {
      "seriesId": 1,
      "title": "Lorem ipsum"
    },
    {
      "seriesId": 2,
      "title": "Consectetur adipiscing elit"
    }
  ]
}
```

And a Swift `Series` type that looks like this:

```swift
struct Series {
    let seriesId: Int
    let title: String
}
```

Assuming that I have implemented the `Decodable` protocol for `Series` and can properly decode a single instance from a JSON object.

What would be the proposed way to decode _all_ of the `Series` in the array? What would be the return type (e.g., `Decoded<[Series]>` or `[Decoded<Series>]`)? I looked in the tests, as best I could, to see if I could find an example to no avail. Is there such an example in the tests?

**Comment by jshier** [comment]
To simplify parsing, I usually create a `SeriesResponse` type that contains a single property of type `[Series]`. Otherwise you may be able to do `let series: [Series] = json <|| "series"`.

**Comment by ikesyo** [comment]
There are array variants of `decode` function: https://github.com/thoughtbot/Argo/blob/4b71fa487b9d81aee458049867f1b89e20c526d9/Argo/Functions/decode.swift

**Comment by RLovelett** [comment]
I couldn't get `let series: [Series] = (JSON.parse(json) <|| "series")` to compile. Kept getting "Ambiguous reference to member '<||'". However, I did get this to work `let series: [Series]? = (json <|| "series").value`.

In the end, I think I'm probably going to go `SeriesResponse` route. In the meantime, until I get that written, this is the final test code I've settled on.

```swift
let decoded: Decoded<[Series]> = (JSON.parse(json) <|| "series")
switch decoded {
case .Success(let series):
  XCTAssertEqual(series.count, 23)
default:
  XCTFail(decoded.description)
}
```

Thank you @jshier and @ikesyo. :beers:

**Comment by tonyd256** [comment]
@RLovelett glad you were able to figure it out! You came to the correct conclusion, you want to use the `<||` operator to decode and array of `Series`, `[Series]`. That operator will return a `Decoded<[Series]>` that retains an error message if something fails. If you don't care about an error message then you can call `.value`, as you found out, to get an optional value `[Series]?`.

so in all:
```swift
let json: JSON = JSON.parse(anyobject)
let series: Decoded<[Series]> = json <|| "series"
// or
let series: [Series]? = (json <|| "series").value
```
