### ISSUE TITLE
Question: tvOS support

### ISSUE THREAD

**Issue by bruceflowers** [thoughtbot/Argo#224]
I would love to be able to use Argo in a tvOS project (via Carthage if possible) - is support for this planned?

**Comment by wovencharlie** [comment]
+1

**Comment by tonyd256** [comment]
Yes definitely. We're getting read to merge in the Swift 2 branch and after that we'll get tvOS support going. However, if you don't want to wait PRs are welcome :)

**Comment by bruceflowers** [comment]
I'm actually considering your suggestion of doing a PR... but I haven't found any documentation that makes this clearcut yet. 

Does anyone here have pointers/links for how to add tvOS support to a framework project?

**Comment by tonyd256** [comment]
A PR just opened on Curry .. might be a good starting point: https://github.com/thoughtbot/Curry/pull/9

**Comment by nickygerritsen** [comment]
Ah, I just wanted to also add a PR here for tvOS. Guess it will be best to base it of the Swift 2 branch right?

**Comment by tonyd256** [comment]
hold on a bit if you can ... the swift-2 branch is going to be merged into master today

**Comment by nickygerritsen** [comment]
OK I guess I can wait that long :).

**Comment by tonyd256** [comment]
have at it guys

**Comment by nickygerritsen** [comment]
@bruceflowers I will probably work on this tomorrow (CEST), but if you want to do it earlier go ahead :)

**Comment by gfontenot** [comment]
For the record, we'll need to keep tvOS support on a branch till 7.1 is official, since it will break Carthage installs.

The alternative is to merge tvOS support and just keep the scheme un-shared, like is done in Result.

**Comment by nickygerritsen** [comment]
I have no problem keeping it in a branch. How does that work with a PR?
I will use it with a Carthage project, but I have XCode 7.1 so that won't be a problem for me.

**Comment by gfontenot** [comment]
Add the target, but don't share the scheme. We will then open a branch that has the scheme shared so that you can point to it.

**Comment by nickygerritsen** [comment]
Yeah just read it in the Curry PR. Will do this :)

**Comment by nickygerritsen** [comment]
Maybe I'm missing something, but why are the test targets referencing .frameworks from `Carthage/Checkout/Curry/build/` instead of `Carthage/Build/*/Curry.framework`?

I of course also want to add a tvOS test target but on my machine I have the frameworks not located in that directory...

**Comment by paulyoung** [comment]
@nickygerritsen sounds like you may have an older version of Carthage

**Comment by nickygerritsen** [comment]
Double checked its 0.9.1 according to carthage version

**Comment by neilpa** [comment]
0.9.1 doesn't support binary releases for watchOS or tvOS yet. You'll need a release with carthage/carthage#760

**Comment by nickygerritsen** [comment]
Ok I will wait for a new release then, as my El Capitan doesn't want to build from source

**Comment by bruceflowers** [comment]
@neilpa "0.9.1 doesn't support binary releases for watchOS or tvOS yet."

looking for clarification - are you saying that only release builds for device are not working? I haven't had an issue deploying debug builds to tvOS with 0.9.1 fwiw.

**Comment by neilpa** [comment]
It's not about release vs debug. If the pre-packaged frameworks.zip on github releases contain a watchOS target they break on 0.9.1 because it incorrectly identifies it as an iOS framework.

**Comment by bruceflowers** [comment]
@neilpa makes sense

**Comment by nickygerritsen** [comment]
Annndddd they release [0.9.2](https://github.com/Carthage/Carthage/tree/0.9.2), which should fix this :). I'll try soon.

**Comment by tonyd256** [comment]
tvOS support added in the latest version: 2.2.0!
