### ISSUE TITLE
Argo 1.0.4 pulls Runes 3.0.

### ISSUE THREAD

**Issue by nomothetis** [thoughtbot/Argo#230]
The Cartfile reads:

```
github "thoughtbot/Runes" >= 1.2.2
```

Per semantic versioning, this will get any version higher than that, up to, including, and beyond 3.0. This breaks apps that are not yet on Swift 2.0. Any way we can have a 1.0.5 that fixes this?

**Comment by tonyd256** [comment]
just pushed a v1.0.5 tag. That should work better.

**Comment by tonyd256** [comment]
Let me know if it works for you!

**Comment by nomothetis** [comment]
Thank you! That was a much faster turnaround time than we dared hope; we'll check this morning and get back to you.

**Comment by nomothetis** [comment]
Thanks, it all worked. :+1:
