### ISSUE TITLE
throws clause in create() causes "ambiguous reference to member" error

### ISSUE THREAD

**Issue by edwardaux** [thoughtbot/Argo#248]
For some reason, having a `throws` clause in my curried `create` method causes the Swift compiler some problems trying to resolve the `<|` operator. Consider the following code:

	enum Blah {
		case XXX(String, String)
	}
	extension Blah : Decodable {
		static func create(type: String)(parameter: String) throws -> Blah {
			return .XXX(type, parameter)
		}
		
		static func decode(j: JSON) -> Decoded<Blah> {
			return Blah.create
				<^> j <|  "type"
				<*> j <| "parameter"
		}
	}

Removing `throws` makes the error go away (see error screenshot below). However, what is not shown is that I need to do some validation in the `create` function which may mean an error gets thrown. Note that I used to return a `Result<Blah, NSError>` object and everything worked OK, but I'm slowly moving towards using `throws` as my error handling technique. Do I need to go back to using `Result` for this piece?

![screen shot 2015-09-29 at 4 57 11 pm](https://cloud.githubusercontent.com/assets/1574429/10157202/32cc0eac-66cb-11e5-93c3-be36ba7360d2.png)

**Comment by tonyd256** [comment]
this makes sense because adding `throws` in the `create` function signature changes the type. Argo's operators are not setup to handle `throws`. I could use a `try-catch` inside the `create` function and inside the `catch` return a custom `DecodedError` instead.

**Comment by tonyd256** [comment]
Actually scratch that. I would abstract a function that performs the throwing code say `readFile()`. then have that function return a `DecodedError` if the `try` fails:

```swift
func readFile(path: String) -> Decoded<String> {
  do {
    let string = try readFileWithPath(path) // function that could throw
    return pure(string)
  } catch {
    return .custom("Custom Error String")
  }
}
```
Then in your `decode` function you would use it like so: `<*> (j <| "parameter" >>- readFile)`

**Comment by paulyoung** [comment]
Maybe a use case for `materialize` after all?

**Comment by tonyd256** [comment]
hmm oh yes, possibly!

**Comment by edwardaux** [comment]
Thanks @tonyd256, I like the idea of abstracting out the function. It keeps things isolated, and it means I don't have to use a `Result` object just for this isolated instance. Thanks for the feedback and suggestion.
