### ISSUE TITLE
Bundle only contains bitcode-marker

### ISSUE THREAD

**Issue by zamith** [thoughtbot/Argo#249]
When trying to submit an app with Xcode 7.0.1, Swift 2.0 and Argo 2, I get the following error:

```
Invalid Bundle - Failed to verify bitcode in Argo.framework/Argo: error: 
Bundle only contains bitcode-marker MyApp.app/Frameworks/Argo.framework/Argo (armv7) ...
```

As per [this comment](https://github.com/Carthage/Carthage/issues/535#issuecomment-143402348), I'm assuming this might be an Argo issue.

**Comment by tonyd256** [comment]
I'm not sure what's going on here. I'll take a look into it and get back to you.

**Comment by zamith** [comment]
Any luck with this? Are you at least confident that this is actually a bug with Argo? Were you able to reproduce?

**Comment by tonyd256** [comment]
@zamith Can you confirm that #260 fixes things?

**Comment by zamith** [comment]
Yes it does.

**Comment by tonyd256** [comment]
cool I'll merge

**Comment by tonyd256** [comment]
Currently in master (bd79021cac3f4419c2b5631fcf19a02352ce00c5). I'll cut a release soon.
