### ISSUE TITLE
The compiler hangs compiling my struct extension

### ISSUE THREAD

**Issue by Blackjacx** [thoughtbot/Argo#26]
Hi,

I have a struct that has 16 fields. Is that too large for your library? Here It is:

    extension ContractOverview {
    					static func create
    						(status: ContractOverviewStatusValue)
    						(key: ContractKey?)
    						(customerNumber: String?)
    						(customerName: String?)
    						(phoneNumber: String?)
    						(tariffName: String?)
    						(debitor: String?)
    						(endOfBinding: String?)
    						(prepaidBalance: PrepaidBalance?)
    						(consumption: [ConsumptionItem])
    						(cost: CostItem)
    						(pass: Pass?)
    						(hasOpenOrder: ContractOverviewHasOpenOrderValue)
    						(informationservice: Bool)
    						(invoiceType: ContractOverviewInvoiceType)
    						(amount : String?) -> ContractOverview {
							
    							return ContractOverview(status: status, key: key, customerNumber: customerNumber, customerName: customerName, phoneNumber: phoneNumber, tariffName: tariffName, debitor: debitor, endOfBinding: endOfBinding, prepaidBalance: prepaidBalance, consumption: consumption, cost: cost, pass: pass, hasOpenOrder: hasOpenOrder, informationservice: informationservice, invoiceType: invoiceType, amount: amount)
					    }
					
					    static func decode(j: JSONValue) -> ContractOverview? {
						    return ContractOverview.create
							    <^> j <|  "status"
							    <*> j <|?  "key"
							    <*> j <|?  "customerNumber"
   							    <*> j <|?  "customerName"
    							<*> j <|?  "phoneNumber"
	    						<*> j <|?  "tariffName"
		    					<*> j <|?  "Debitor"
			    				<*> j <|?  "endOfBinding"
				    			<*> j <|?  "prepaidBalance"
					    		<*> j <|  "consumption"
    							<*> j <|  "currentCost"
	    						<*> j <|?  "pass"
		    					<*> j <|  "hasOpenOrder"
			    				<*> j <|  "informationservice"
				    			<*> j <|  "invoiceType"
					    		<*> j <|?  "amount"
					}
    }

Maybe I made a typo but I already looked at it for about an hour. *help*

This is the enum:

    struct ContractOverview {
        var status = ContractOverviewStatusValue.incomplete
    	var key : ContractKey?
        var customerNumber : String?
        var customerName : String?
        var phoneNumber : String?
        var tariffName : String?
        var debitor : String?
        var endOfBinding : String?
        var prepaidBalance : PrepaidBalance?
    	var consumption = [ConsumptionItem]()
    	var cost: CostItem
        var pass : Pass?
        var hasOpenOrder = ContractOverviewHasOpenOrderValue.indeterminable
        var informationservice = false
    	var invoiceType = ContractOverviewInvoiceType.unknown
    	var amount: String?
    }

**Comment by gfontenot** [comment]
Unfortunately, Argo isn't the issue here. You're running into the limits of the compiler itself. There's not much you can do here short of breaking apart your model. See also #5. We're going to add a note in the README about this.
