### ISSUE TITLE
Can't decodeWithRootKey the JSON type

### ISSUE THREAD

**Issue by jakecraige** [thoughtbot/Argo#266]
![screen shot 2015-10-09 at 5 32 06 pm](https://cloud.githubusercontent.com/assets/3799709/10406124/c1283e72-6eab-11e5-9b67-ae23f249c25a.png)

**Comment by gfontenot** [comment]
I don't think this is a bug.

**Comment by tonyd256** [comment]
`decodeWithRootKey` is meant to be used with `AnyObject`, not `JSON`.
