### ISSUE TITLE
Cocoapods with master: Operator implementation without matching operator declaration

### ISSUE THREAD

**Issue by bruceflowers** [thoughtbot/Argo#267]
I want to build the latest swift2.0 code using Cocoapods.

I've added Argo to a podfile, run pod install using the latest Cocoapods release (0.39.0).  That succeeds, but when building the project, I have this error which looks related to Runes:

Operator implementation without matching operator declaration

Am I doing something wrong here?

**Comment by gfontenot** [comment]
you need to add `:submodules =>  true` to your pod file if you aren't using the official release.

**Comment by bruceflowers** [comment]
Just realized my error while you were typing this, works. Thank you!
