### ISSUE TITLE
 No such module 'curry'

### ISSUE THREAD

**Issue by zhaodg** [thoughtbot/Argo#269]
i can find argo module, but can not find curry.
i use it with pod,8.0, and use_frameworks

**Comment by tonyd256** [comment]
Curry is not a dependency of Argo. If you're seeing this error it is probably because you're trying to use `curry` but have not included the Curry framework. Please check here for instructions: https://github.com/thoughtbot/Curry

We could probably clarify that in the README if it is unclear.
