### ISSUE TITLE
Expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions

### ISSUE THREAD

**Issue by zhaodg** [thoughtbot/Argo#272]
// 
//  CommentItem.swift
//  xxxxxxxxxxxxxxx
//
//  Created by xxxxxxx on 10/20/15.
//  Copyright © 2015 xxxxxx. All rights reserved.
//

import Argo
import Curry

struct CommentItem {
    let fromUserId: String?
    let toUserId: String?
    let content: String?
    let timestamp: Int64?
}

extension CommentItem: Decodable {
    static func decode(j: JSON) -> Decoded<CommentItem> {
        return curry(UACCommentItem.init)
            <^> j <| "fromUserId"
            <*> j <|? "toUserId"
            <*> j <| "content"
            <*> j <| "timestamp"
    }
}

Above is code, swift 2.0, Version 7.0.1 (7A1001), i have this problem. 
the line of problem is "<*> j <| "timestamp""

**Comment by paulyoung** [comment]
@zhaodg based on your `CommentItem` model, I think your `decode` method should be this:

```swift
static func decode(j: JSON) -> Decoded<CommentItem> {
    return curry(CommentItem.init)
        <^> j <|? "fromUserId"
        <*> j <|? "toUserId"
        <*> j <|? "content"
        <*> j <|? "timestamp"
    }
}
```

Beyond that, I'm not 100% sure decoding `Int64` works out of the box.

**Comment by gilesvangruisen** [comment]
@zhaodg @paulyoung (aside from the operator typos & missing optional decodes) my first thought was also about decoding `Int64`, but I just wrote an example model with an `Int64` property and the `Decodable` extension seems to compile just fine

**Comment by gilesvangruisen** [comment]
@zhaodg I'm not sure how `CommentItem` is being used after it's decoded, but Apple suggests using `Int` over `Int32`/`Int64` unless your program requires you to use a particular size integer. Behind the scenes, Swift will decide which to use based on the system architecture.

[From the docs](https://developer.apple.com/library/ios/documentation/Swift/Conceptual/Swift_Programming_Language/TheBasics.html) ("Int" section):
> In most cases, you don’t need to pick a specific size of integer to use in your code. Swift provides an additional integer type, Int, which has the same size as the current platform’s native word size
> …
> Unless you need to work with a specific size of integer, always use Int for integer values in your code.

**Comment by tonyd256** [comment]
@zhaodg What @paulyoung and @gilesvangruisen are suggesting is correct. Fixing the operator typos (`<*>` instead of `<>`) and using the optional Argo operators (`<|?` instead of `<|`) should fix your issues.

Another thing you might want to think about is if all you properties on `Comment` need to be optional. Will you ever have a `Comment` object that doesn't have at least one of those properties? I'm willing to bet that all of those properties will exist every time you have a comment. If that is the case then you should make all of those properties non-optional like so:

```swift
struct CommentItem {
  let fromUserId: String
  let toUserId: String
  let content: String
  let timestamp: Int64
}

extension CommentItem: Decodable {
  static func decode(j: JSON) -> Decoded<CommentItem> {
    return curry(CommentItem.init)
      <^> j <| "fromUserId"
      <*> j <| "toUserId"
      <*> j <| "content"
      <*> j <| "timestamp"
    }
  }
}
```

**Comment by zhaodg** [comment]
#Hi, @tonyd256 @paulcsmith @gilesvangruisen , thanks.

I have a right answer to fix above question, but i have another same question.
``` 
import Argo
import Curry

struct FeedItem {
    let id: String
    let userId: String
    let tags: [String]
    let praiseCount: NSInteger
    let isPraised: Bool
    let title: String
    let content: String
    let summary: String
    let comments: [CommentItem]
    let commentCount: NSInteger
    let timestamp: NSInteger
}

extension FeedItem: Decodable {
    static func decode(j: JSON) -> Decoded<FeedItem> {
        return curry(FeedItem.init)
            <^> j <| "id"
            <*> j <| "userId"
            <*> j <|| "tags"
            <*> j <| "praiseCount"
            <*> j <| "isPraised"
            <*> j <| "title"
            <*> j <| "content"
            <*> j <| "summary"
            <*> j <|| "comments"
            <*> j <| "commentCount"
            <*> j <| "timestamp"
    }
}
```
The line of problem is still "<*> j <| "timestamp"", which is last line of code.

**Comment by barrettclark** [comment]
I have a struct that works with up to 6 items. Any more and I get the error.  Here is my struct:

```swift
struct Airport {
    let id: Int
    let cityName: String
    let stateCode: String
    let countryCode: String
    let latitude: Double
    let longitude: Double
//    let airportName: String
//    let iataCode: String
}

extension Airport: Decodable {
    static func decode (j: JSON) -> Decoded<Airport> {
        return curry(Airport.init)
            <^> j <| "id"
            <*> j <| "city_name"
            <*> j <| "state_code"
            <*> j <| "country_code"
            <*> j <| "latitude"
            <*> j <| "longitude"
//            <*> j <| "poi_name"
//            <*> j <| "vendor_code"
    }
}
```

**Comment by zhaodg** [comment]
@barrettclark  I can use it in this approach.
```
extension FeedItem: Decodable {
    static func decode(j: JSON) -> Decoded<FeedItem> {
        let a = curry(FeedItem.init)
            <^> j <| "id"
            <*> j <| "userId"
            <*> j <|| "tags"
            <*> j <| "praiseCount"
            <*> j <| "isPraised"
            <*> j <| "title"
        return a
            <*> j <| "content"
            <*> j <| "summary"
            <*> j <||? "comments"
            <*> j <| "commentCount"
            <*> j <| "timestamp"
    }
}
```
Is there another approach to fix this question.

**Comment by barrettclark** [comment]
Thanks for the workaround @zhaodg 

I know that this is a known issue with Xcode. I filed a bug on it after talking with an engineer at WWDC this past summer, and that bug was closed because there was an existing radar on it.  That issue (#17244974 ) is still open.

**Comment by tonyd256** [comment]
@zhaodg and @barrettclark ... this is an unfortunate known issue. We've found that the number of expressions that `decode` can handle depends on how much type inference and complexity there is within the operators and auxiliary functions. Recently, we added a lot more `curry` functions to that library and the magic number dropped to 6 which is pretty low. I want to do some experiments when I have some time to see if I can get that number back up a bit.

Some thoughts are: reduce the number of curry functions (we probably don't need a 64 parameter curry),   try removing the backticks in the curry functions (not sure if that's hard on the compiler), remove the optional implementations of the Argo operators (reducing the type inference options may lead to less complexity).

**Comment by tonyd256** [comment]
So it looks like removing the backticks or removing the optional Decoded operators didn't help. But reducing the amount of curry functions to 26 (number of letters in the alphabet) allowed me to have 9 partial applications before the "expression to complex" error.

BUT, it turns out that the best approach is to have the `curry` function in a separate expression. I was able to get up to 14 partial applications but doing this:

```swift
extension TestModel: Decodable {
  static func decode(j: JSON) -> Decoded<TestModel> {
    let f = curry(self.init)
    return f
      <^> j <| "numerics"
      <*> j <| ["user_opt", "name"]
      <*> j <| "bool"
      <*> j <|| "string_array"
      <*> j <||? "string_array_opt"
      <*> j <|| ["embedded", "string_array"]
      <*> j <||? ["embedded", "string_array_opt"]
      <*> j <|? "user_opt"
      <*> (j <| "dict" >>- { [String: String].decode($0) })
      <*> j <| "numerics"
      <*> j <| ["user_opt", "name"]
      <*> j <| "bool"
      <*> j <|| "string_array"
      <*> j <||? "string_array_opt"
  }
}
```
The important part being:
```swift
let f = curry(self.init)
return f
```
I think this is the best approach for now.

**Comment by zhaodg** [comment]
@tonyd256  It works, thanks.

**Comment by Jakenberg** [comment]
Has there been a proposed solution to having more than 14 partial applications? 

I currently cannot get past the `Expression was too complex...` error with: 
```swift
static func decode(j: JSON) -> Decoded<Project> {
        let f = curry(self.init)
        return f
            <^> j <| "id"
            <*> j <| "account"
            <*> j <|? "budget"
            <*> j <| "calendar"
            <*> j <| "client"
            <*> (j <| "created_at" >>- { $0.SH_toNSDate })
            <*> j <|? "created_from_template"
            <*> j <| "main_event"
            <*> j <| "name"
            <*> j <| "public_id"
            <*> j <| "status"
            <*> j <|| "tags"
            <*> j <| "template_yn"
            <*> j <| "type"
            <*> (j <| "updated_at" >>- { $0.SH_toNSDate })
            <*> j <| "user"
    }
```

I found `SH_toNSDate` in another thread (https://github.com/thoughtbot/Argo/issues/131). Mine looks like: 
```swift
private let SH_jsonDateFormatter: NSDateFormatter = {
    let dateFormatter = NSDateFormatter()
    dateFormatter.dateFormat = "yyyy-MM-dd "
    return dateFormatter
}()

public func SH_toNSDate(dateString: String) -> Decoded<NSDate> {
    return Decoded<NSDate>.fromOptional(SH_jsonDateFormatter.dateFromString(dateString))
}
```

I would be happy to take a stab at extending the number of partial applications if an idea has been proposed, but not yet implemented.

**Comment by gilesvangruisen** [comment]
@Jakenberg unfortunately this seems to be purely an issue with the Swift compiler. Have you tried splitting up the expression any further to have a higher number of slightly less complex expressions? (see @zhaodg's response above)

Additionally, while Swift should certainly be able to handle these large models, I've personally found this issue to be evidence of poor data modeling in my applications. Decomposing data models has a number of benefits, one of which is that this issue no longer applies.

Another is that it's easier to load data piece-by-piece as you need it and compose the chunks later when it's necessary. This is especially helpful on mobile, and while it might not necessarily be a solution for this problem, it's something worth considering.

**Comment by litt1e-p** [comment]
this bug? still exist in swift2, Xcode7.3 beta

**Comment by Jakenberg** [comment]
@litt1e-p yes it does. I would recommend using https://github.com/Hearst-DD/ObjectMapper instead 👍

**Comment by jshier** [comment]
It's not a bug, just a limitation of the Swift compiler. You can work around it by breaking the initialization statement into multiple parts, as outlined in #321.

**Comment by Jakenberg** [comment]
@jshier you're right, but the response above (https://github.com/thoughtbot/Argo/issues/272#issuecomment-159309819) isn't a solution. https://github.com/thoughtbot/Argo/issues/321 gets you maybe another 10 attributes until the same error starts occurring (goes without mentioning the significant increase in compilation time).

It's perfectly normal (and common) to have more than 10 attributes to a model. I feel that Curry should have been re-assessed at the time this issue was found; refactored or migrated off of. There are obviously many other ways to handle serialization than nested variadic & generic functions (see ObjectMapper) - albeit fancy as hell!

@litt1e-p I recommended ObjectMapper because I'm currently serializing models with (gasp) 30+ attributes with ease. Imo it's the right tool for this job.

**Comment by jshier** [comment]
It isn't a `curry` issue. You can use your own curried initializer if you want, with as many parameters as you want, but the swift compiler requires you to break the curried sequences into smaller parts. I used to have a model with nearly 30 properties working this way. I was finally able to cut out the fields I wasn't using and go with curry in all cases.

**Comment by Jakenberg** [comment]
@jshier 
> "the swift compiler requires you to break the curried sequences into smaller parts." 

I disagree. `curry` is the one **requiring** the developer to use the compiler in an explicit way. Using a custom `curry` doesn't fix this problem either. 

I can appreciate how this compiler issue isn't one that the Argo team has much control over, but it's not like this is the only solution. A solution that fits the compiler better could have been designed. 
In the words of thoughtbot: 
> "As software developers, we are hired to write code that works. If our code doesn’t work, we have failed." https://thoughtbot.com/testing-rails-sample.pdf

Thus, I don't think blaming the compiler is a sufficient solution.

P.S. I would be very interested in a gist demonstrating how you pulled off more than 30 attributes.

**Comment by mbrandonw** [comment]
@Jakenberg i haven't had time to make edits to get this merged, but some documentation i wrote up describes other ways to get around this: https://github.com/mbrandonw/Argo/blob/e613d0723b47af4adc0e4b75c9f2f6351b68fdea/Documentation/Common-Gotchas.md

In particular the part where you normalize a set of fields into a sub-struct.
