### ISSUE TITLE
how to parse data to array?

### ISSUE THREAD

**Issue by zhaodg** [thoughtbot/Argo#273]
The json data is:
```
[
  {
    "id" : "56260a7fc7c4ef852165d1be",
    "praiseCount" : 13,
    "content" : "",
    "isPraised" : false,
    "comments" : null,
    "timestamp" : 1445333631,
    "tags" : [
      "Crimson",
      "Red",
      "Ruby",
      "Maroon"
    ],
    "title" : "zhaodg...title...TestAddFeedOne",
    "userId" : "56260a7fc7c4ef852165d1bd",
    "summary" : "zhaodg...summary...TestAddFeedOne",
    "commentCount" : 1,
    "views" : 1013
  },
  {
    "id" : "5625a102c7c4efa7a97e2bd9",
    "praiseCount" : 13,
    "content" : "",
    "isPraised" : false,
    "comments" : null,
    "timestamp" : 1445306626,
    "tags" : [
      "Crimson",
      "Red",
      "Ruby",
      "Maroon"
    ],
    "title" : "zhaodg...title...TestAddFeedOne",
    "userId" : "5625a102c7c4efa7a97e2bd8",
    "summary" : "",
    "commentCount" : 1,
    "views" : 1013
  }
]
```

the item is 
```
import Argo
import Curry

struct FeedItem {
    let id: String
    let userId: String
    let tags: [String]
    let praiseCount: NSInteger
    let isPraised: Bool
    let title: String
    let content: String
    let summary: String
    let comments: [CommentItem]
    let commentCount: NSInteger
    let timestamp: NSInteger
}

extension FeedItem: Decodable {
    static func decode(j: JSON) -> Decoded<FeedItem> {
        return curry(FeedItem.init)
            <^> j <| "id"
            <*> j <| "userId"
            <*> j <|| "tags"
            <*> j <| "praiseCount"
            <*> j <| "isPraised"
            <*> j <| "title"
            <*> j <| "content"
            <*> j <| "summary"
            <*> j <|| "comments"
            <*> j <| "commentCount"
            <*> j <| "timestamp"
    }
}
```
how to decode json to `[FeedItem]` array?

**Comment by tonyd256** [comment]
Since there is no root key, you can use the `decode` function. `let array: [FeedItem]? = decode(json)` where `json` is the `AnyObject` returned from `NSJSONSerialization`. If you have a `JSON` type already then you can do this: `[FeedItem].decode(json)` where `json` is type `JSON` in this instance.

**Comment by zhaodg** [comment]
How about  use the decode function.
Such as ` let array: [FeedItem]? = decode(json) ` where json is the `array`

**Comment by zhaodg** [comment]
I see why i  parse failed. Thanks @tonyd256 .

it's better use ` let array: Decoded<[FeedItem]> = decode(json["data"].object)`
I can find parse error through array.error

But how can i check parsing error use below approach 
` let array: [FeedItem] = decode(json["data"].object)`

**Comment by tonyd256** [comment]
@zhaodg You should not use `json["data"].object`. From what I can tell, it will return `.None` in instances where there actually is something. I think you will hit unexpected errors if you do this. Instead, I would use the `decodeWithRootKey` function like so: 
`let array: Decoded<[FeedItem]> = decodeWithRootKey("data", json)`

if you don't want the error information then you can use the Optional variant:
`let array: [FeedItem]? = decodeWithRootKey("data", json)`

Using the Optional variant will drop any error data and you won't be able to see why decoding failed. If you need the error information, use the `Decoded` variant.

**Comment by zhaodg** [comment]
thanks @tonyd256
