### ISSUE TITLE
Just wondering about Curry with large objects.

### ISSUE THREAD

**Issue by jamesdo** [thoughtbot/Argo#274]
I'm wondering if anyone has successfully used Curry for parsing larger objects. If anyone has been able to break down an object to smaller pieces using Curry that would be great, I would like to eliminate all of the `create()` functions if they're not necessary.

**Comment by tonyd256** [comment]
I think people have successfully been able to do this. Check out #272. I'm going to close this but if you have a specific issue feel free to create a new Issue with the code.
