### ISSUE TITLE
Better error message for enums/RawRepresentable types

### ISSUE THREAD

**Issue by paulyoung** [thoughtbot/Argo#275]
I currently see `TypeMismatch(Expected .Some(Provider), got .None)` because of an invalid value coming from the server and ultimately being passed to `Provider(rawValue: ...)`

It would be useful to know what the value is without needing to go and look at the server response.

**Comment by tonyd256** [comment]
What are you thinking? Perhaps we could attach the JSON as a third parameter?

**Comment by paulyoung** [comment]
I was thinking something simple like `TypeMismatch(Expected .Some(X), got .None) with rawValue: y`

**Comment by gfontenot** [comment]
Done in da89baf
