### ISSUE TITLE
Xcode 7.1 support

### ISSUE THREAD

**Issue by eimantas** [thoughtbot/Argo#276]
Any plans on releasing a new build just for Xcode 7.1? It's the only library in my tool-belt requiring me to use `--no-use-binaries` when updating with Carthage.

**Comment by carlossless** [comment]
+1

**Comment by AlexanderKaraberov** [comment]
The same problem
I got `error: module file was created by an older version` after upgrading

**Comment by tonyd256** [comment]
Hey all, I'm can push a new binary tonight. It will include tvOS support! I'll post back here when it's done.

**Comment by tonyd256** [comment]
New version pushed! Available via Carthage and Cocoapods! 2.2.0

**Comment by carlossless** [comment]
@tonyd256 Thank you! Great work with the Lib, guys!
