### ISSUE TITLE
Ambiguous reference to member ‘curry’

### ISSUE THREAD

**Issue by nhatlee** [thoughtbot/Argo#278]
I got the error: "Ambiguous reference to member ‘curry’" when create a custom model(I use Swift 2 and Xcode 7.1). Below is my code:

```swift
import UIKit
import Argo
import Curry

struct CountryState{
    let stateId: String
    let stateName: String
    let stateAbbrev: String
}
extension CountryState: Decodable {
    static func decode(j: JSON) -> Decoded<CountryState> {
        return curry(CountryState.init)
            <*> j <| "id"
            <*> j <| "name"
            <*> j <| "abbrev" // Use ? for parsing optional values
    }
}

class CountryStateModel: NSObject {
}
```

Please help me to fix it.

**Comment by gfontenot** [comment]
Looks like you're using `apply` (``<*>`) where you should be using `map` (`<^>`). Try changing the first operator in the chain to `<^>`:

```swift
extension CountryState: Decodable {
    static func decode(j: JSON) -> Decoded<CountryState> {
        return curry(CountryState.init)
            <^> j <| "id"
            <*> j <| "name"
            <*> j <| "abbrev"
    }
}
```

**Comment by nhatlee** [comment]
@gfontenot Thank you very much. you save me a lot of time. But I still don't understand that my variable "id" is a String, so why I must to use <^> (not a: <*>)?

**Comment by gfontenot** [comment]
the difference between `map` (`<^>`) and `apply` (`<*>`) has nothing to do with the type of the parameter, but actually has to do with the type of the function. `apply` is expecting a function of the type `Decoded<T -> U>`, but `curry` is returning a function of the type `T -> U` (note that the function is _not_ wrapped in `Decoded`. It might help to check out the function signatures for those functions, as well as [reading up on curry][curry] and [using monadic functions][monadic]. (replace the word `fmap` with `map` in that second article)

[curry]: https://robots.thoughtbot.com/introduction-to-function-currying-in-swift
[monadic]: https://robots.thoughtbot.com/functional-swift-for-dealing-with-optional-values

**Comment by gfontenot** [comment]
@nhatlee I'm going to close this, but feel free to ask more questions if this still doesn't make sense.
