### ISSUE TITLE
Model to JSON

### ISSUE THREAD

**Issue by RuiAAPeres** [thoughtbot/Argo#280]
I understand that this might be out of scope for Argo, but have you guys considered adding the ability of going from a Model object to JSON? Even if it's not part of this lib, maybe as a separated library?

**Comment by wouterw** [comment]
@RuiAAPeres Have you seen Argo's dual [Orga](https://github.com/edwardaux/Ogra)? :)

**Comment by RuiAAPeres** [comment]
Ah I missed it! Thanks @wouterw
