### ISSUE TITLE
Separate model got the error: cannot convert value of type ‘(user_Id: Int, user_Email: String, user_FirstName: String….)

### ISSUE THREAD

**Issue by nhatlee** [thoughtbot/Argo#283]
Hi all, I face with the error 'cannot convert value of type ‘(user_Id: Int, user_Email: String, user_FirstName: String….)' when try to separate my model. Below is my code:

```swift
struct UserModel {
    let user_Id: Int
    let user_Email: String
    let user_FirstName: String
    let user_MemberToken: String
    let user_LastName: String
    let user_SurName: String
    let user_Bithday: String
    let user_ProfilePhoto: String
    let user_Role: Int //role: 1-Coach; 2: Requester
}

extension UserModel: Decodable{
    static func decode(json: JSON) -> Decoded<UserModel> {
        let a = UserModel.init
            <^> json <| "id"
            <*> json <| "email"
        let a1 = a
            <*> json <| "firstName"
            <*> json <| "memberToken"
            <*> json <| "lastName"
        let a2 = a1
            <*> json <| "sureName"
            <*> json <| "birthDay"
        return a2
            <*> json <| "profilePhoto"
            <^> json <| "role"
    }
}
```

Please help me to fix it. Thanks so much.

**Comment by gfontenot** [comment]
Looks like your last monadic operator is `<^>` (map) instead of `<*>` (apply). This needs to be fixed.

**Comment by nhatlee** [comment]
@gfontenot I change the variable 'role' to 'let user_Role: String' and replace (<^> json <| "role") to (<*> json <| "role") as your advice but still got the same error.

**Comment by gfontenot** [comment]
Oh, I see. You aren't currying your initializer either. You need to either write a curried static method, or you need to use `curry` function to curry `UserModel.init`. For example, see [Curry.framework](https://github.com/thoughtbot/Curry)

**Comment by nhatlee** [comment]
@gfontenot not as you guess, I had Curry framework in pod file. And can parse data successful with another model. Like that:
struct CountryState{
    let stateId: Int
    let stateName: String
    let stateAbbrev: String
}
extension CountryState: Decodable {
    static func decode(j: JSON) -> Decoded<CountryState> {
        return curry(CountryState.init)
            <^> j <| "id"
            <*> j <| "name"
            <*> j <| "abbrev" // Use ? for parsing optional values
    }
}

BUT when I try to parse UserModel with many variable. I face with the error as above.

**Comment by gfontenot** [comment]
The original code snippet you posted above doesn't use `curry`. Was that a typo?

**Comment by nhatlee** [comment]
@gfontenot ooh, my god. So sorry cause my stupid mistake. You save my life.Thanks so much

**Comment by gfontenot** [comment]
No problem! Glad I could help. I'm going to close this, but feel free to continue asking questions.
