### ISSUE TITLE
Decoding with protocol conformance

### ISSUE THREAD

**Issue by mstfy** [thoughtbot/Argo#287]
Hello. I have a protocol to represent api endpoint. Inside protocol there is ResourceType declaration which represents the model object that will be returned from server. It also conforms `Decodable` protocol.

    protocol EndPointType {
        typealias ResourceType: Decodable
    }

Inside protocol extension I have a function that parses response to `ResourceType`. Here is the function

    extension EndPointType {
        private func parseResponse(response: AnyObject) -> Result<ResourceType, NetworkError> {
            let result: Decoded<ResourceType> = decode(response)
            switch result {
            case .Failure: return Result.Failure(NetworkError.IncorrectDataReturned)
            case .Success(let value): return Result.Success(value)
            }
        }
    }

But on first line compiler gives error. `Ambiguous reference to member decode`. So what am I missing here?

**Comment by sidraval** [comment]
I think I see a couple problems:

The compiler doesn't know the `DecodedType` of `ResourceType`. When things conform to the `Decoded` protocol, they get by default `typealias DecodedType = Self`, but this can be overriden.

The version of the `decode` function you're trying to use has this type signature:
```swift
decode<T : Decodable where T == T.DecodedType>(object: AnyObject) -> T?
```

But I think the `T == T.DecodedType` constraint is necessarily fulfilled in your case.

I can get your code snippet to compile as follows, though I'm not sure if it's exactly what you want:

```swift
protocol EndPointType {
  typealias ResourceType: Decodable
}

extension EndPointType {
  private func parseResponse(response: AnyObject) -> Result<ResourceType.DecodedType, NSError> {
    let result = ResourceType.decode(.parse(response))
    switch result {
    case .Failure: Result.Failure(NetworkError.IncorrectDataReturned)
    case .Success(let value): return Result.Success(value)
    }
  }
}
```

**Comment by mstfy** [comment]
Yeah I completly miss that DecodedType typealias. Thank you
