### ISSUE TITLE
Avoiding implicit decode in curried function

### ISSUE THREAD

**Issue by hwaxxer** [thoughtbot/Argo#293]
I'm using Argo to parse JSON into NSManagedObjects. So let's say that I have a model `Channel` that contains a one-to-many relationship with `Participant`.

I might fetch a channel multiple times so I don't want to insert one into Core Data if I already have it.

My decode function looks something like this:

```
extension Channel: Decodable {
  static func decode(json: JSON) -> Decoded<Channel> {
    return Channel.create
      <^> json <| "id"
      <*> json <|| "participants"
  }
}
```

Now I'll end up with stale participants if I did something like this:
```
  static func create(id: String)(participants: [Participant]) -> Channel {
    if let channel: Channel = firstWithId(id) {
      return channel
    ...
```

So I hold on to the JSON and decode it if necessary: 
```
  static func create(id: String)(participantsJSON: [JSON]) -> Channel {
    if let channel: Channel = firstWithId(id) {
      return channel
    }
    let participants: [Participant] = participantsJSON.flatMap({ try! Participant.decode($0).dematerialize() })
    ...
```

But it feels like I'm doing something wrong here. Is there a cleaner solution that I'm missing?

**Comment by paulyoung** [comment]
I'd like to help but not sure I fully understand the problem, or how holding on to the JSON helps.

Could you elaborate, and maybe share some more code?

**Comment by hwaxxer** [comment]
Sorry, I tried to keep it short when I should have been more clear.

Explaining my issue makes me think that directly decoding `NSManagedObject` is what's causing trouble, since they need to be inserted into an `NSManagedObjectContext` upon creation. 

I'm holding on to the JSON because I don't want to create any relational entities (in this case `Participant`) before I know if a `Channel` with that `id` exists or not. If that `Channel` does NOT exist, I want to decode and create the `Participants`. But if the `Channel` already exists, I may instead want to modify the relationship (remove or add `Participants`) or make no changes at all.

But if `Channel.create()` takes `[Participant]` as a parameter, they will already be inserted into Core Data. 
I would return any existing `Participant` in its decode method if I could, but in our data model a `Participant's id` is only unique for a `Channel`, and the `Participant` JSON does not include a `Channel id`.

One solution would be decoding an intermediary struct that contains all the necessary information needed to insert a real `NSManagedObject`. That way I wouldn't have to care as much about what's created since they will be discarded unlike an `NSManagedObject`.

Anyway, I hope this makes some sense! I was just looking for some best practice for Argo + Core Data.

**Comment by paulyoung** [comment]
Would this work?

```
func create(id: String)(participants: [Participant]) -> Channel {
    if var channel: Channel = firstWithId(id) {
        // Optionally do something with participants
        channel.participants = participants
        return channel
    } else {
        return Channel(id: id, participants: participants)
    }
}
```

**Comment by hwaxxer** [comment]
Replacing the participants with new ones will leave the old participants hanging without a `channel` which is a non-optional relationship which will error on the next save unless they are deleted. I think I'll go with holding on to the JSON for now, and potentially creating intermediary structs later on. Thanks for the help, feel free to close this.
