### ISSUE TITLE
Changing from Array-based to List-based

### ISSUE THREAD

**Issue by oisdk** [thoughtbot/Argo#299]
It seems like Swift.Array as the basic datatype for this kind of decoding isn't very well suited to the task: 

* Building arrays in functional ways (i.e. with `reduce`) is slow
* Functional operations (`map`, etc.) copy each intermediate array
* Laziness is difficult (if not impossible)

However, a lazy list type is easy to define:

```swift
enum List<T> {
  case Cons(T, () -> List<T>)
  case Nil
}
```

And if you define an operator with an `@autoclosure`, it's lazy:

```swift
public func >| <T>(lhs: T, @autoclosure(escaping) rhs: () -> List<T>) -> List<T> {
  return .Cons(lhs, rhs)
}
```

Some of the functions seem to be a lot more naturally suited to this data structure. `sequence`, for instance:

```swift
public func sequence<T>(xs: List<Decoded<T>>) -> Decoded<List<T>> {
  return xs.reduceR(pure([])) { elem, accum in (>|) <^> elem <*> accum }
}
```

Anyway, I've been fiddling around with some of these ideas [on this fork](https://github.com/oisdk/Argo). I have a fuller implementation of a lazy list [here](https://github.com/oisdk/SwiftDataStructures). Does this sound like a direction that might be useful?

**Comment by gfontenot** [comment]
I think this is _super_ interesting. Especially with the performance issues we've been having. I haven't dug too deep here, but some thoughts off the top of my head:

 - I think we'd want to make sure this is an implementation detail, not something to be consumed by users. Or, at least, it should be trivial to get an array back.
 - I'd be (minorly) concerned about introducing this as an external dependency. But I'm also not thrilled about shipping an unrelated type that we expose in the public API. Maybe we _start_ internal and then look at a shared dependency if we see the performance improvements that I'd hope for?

We've had discussions internally a number of times about making at least parts of Argo lazy. This might be a good step in that direction. I'll dig into this more (including your links) as soon as I sit down in front of a computer.

**Comment by gfontenot** [comment]
I'm going to close this due to inactivity, but I'm _definitely_ going to keep this in mind as we continue to look for areas to improve performance.
