### ISSUE TITLE
String parsing for Int64?

### ISSUE THREAD

**Issue by nvh** [thoughtbot/Argo#300]
As Javascript is [not really](http://www.2ality.com/2012/07/large-integers.html) equipped to handle large integers, and it's required to use strings for anything above 53-bits, wouldn't it be logical if the decode function of `Int64` automatically parses strings?

**Comment by tonyd256** [comment]
that makes sense to me. Would you be able to open a PR for it?

**Comment by nvh** [comment]
I tried to that this afternoon, but cloning Argo and running `bin/setup` crashed carthage. That was, however, before I read [this](https://github.com/Carthage/Carthage/issues/812). After running `submodule init` and `submodule update`, all works fine again. Anyway, I will try again tomorrow :)

**Comment by gfontenot** [comment]
Merged in the fix from #301 as e7680fc
