### ISSUE TITLE
Decoding all-optional object

### ISSUE THREAD

**Issue by eimantas** [thoughtbot/Argo#305]
I'm receiving an error when I'm trying to decode an object with all optional (7) attributes. Is this behavior "as designed" or did I hit a bug?

The error I'm getting is `Cannot convert value of type '{curried initialiser here}' to expected argument type 'Decoded<_ -> _>`

**Comment by gfontenot** [comment]
Can you post your `decode` function? That error message isn't super helpful.

**Comment by tonyd256** [comment]
@eimantas I was talking with someone the other day who had a similar issue. It's possible that one of the types you're trying to decode does not conform to `Decodable`. I would recommend you double check that all your types lineup. We can also help spot any type mismatches if we can see your model and decoding code.

**Comment by eimantas** [comment]
Nevermind. It was a screw up on my part. That particular error was triggered by me using wrong type as the `curry` function parameter. I.e.
```
extension SomeType: Decodable {
    static func decode(json: JSON) -> Decoded<SomeType> {
        return curry(SomeOtherType.init)
        /* ... */
    }
}
```

Too much copy-pasta. Too little coffee .)

**Comment by gfontenot** [comment]
Glad to hear coffee fixed the issue! That's usually my favorite bug fix.

I'm going to close this, but feel free to open another issue if you run into any problems in the future!
