### ISSUE TITLE
Segmentation fault 11

### ISSUE THREAD

**Issue by aschuch** [thoughtbot/Argo#31]
I think I just ran into another Swift Compiler isse, but want to report it here just to make sure.

```swift
// Inside `decode:`
let x = (j <| "valid_until") >>- parseDate
// ...

class func parseDate(dateString: String) -> NSDate? {
        return NSDate()
}
```
Using Xcode 6.2 beta 4, the above code fails with

```
Command failed due to signal: Segmentation fault: 11
```

However, this works as expected

```swift
// Inside `decode:`
let x = parseDate(j <| "valid_until")
// ...

class func parseDate(dateString: String?) -> NSDate? { // note optional dateString here
        return NSDate()
}
```

**Comment by gfontenot** [comment]
We've noticed some odd behavior in the compiler specifically with `>>-`. I haven't been able to reduce it to a simple test case, but for now a quick fix _might_ be to wrap `parseDate` in a closure and pass the argument explicitly:

```swift
let x = (j <| "valid_untill") >>- { self.parseDate($0) }
```

**Comment by gfontenot** [comment]
@aschuch Have you tried this possible fix?

**Comment by aschuch** [comment]
Sorry, totally forgot about opening this issue. Your suggested fix is indeed working, thanks.
Hope things like this will get resolved once the compiler advances.

**Comment by gfontenot** [comment]
Yep, me too. I'm going to close this issue for now, since there's not much we can do about it. Thanks for reporting it!
