### ISSUE TITLE
Treating certain values as nil

### ISSUE THREAD

**Issue by jshier** [thoughtbot/Argo#311]
I'm wondering how I could treat certain return values (e.g. empty strings) as nil, while still allowing custom types to be decoded from the result. That is, take this JSON:
```json
{
    "thing" : ""
}
```
And be able to decode it into a custom type, while treating the empty string as a nil value. I feel like there should be a way to do this without having to add such a check to every custom value that could be decoded from a `String`.

**Comment by gfontenot** [comment]
Great question.

There's no _awesome_ way to do this now, but I'd suggest transforming the `JSON` value after it comes out of `JSON.parse` as a possible place to do this kind of thing.

In my head, this might look something like:

```swift
func convertEmptyStrings(j: JSON) -> JSON {
  switch j {
  case let .Array(a): return .Array(a.map(convertEmptyStrings))
  case let .Object(o): return .Object(o.map(convertEmptyStrings))
  case let .String(s):
    if s == "" {
      return .Null
    }

    fallthrough
  default:
    return j
  }
}
```

This relies on the [`Dictionary.map` and pure `+` implementations from Argo](https://github.com/thoughtbot/Argo/blob/master/Argo/Extensions/Dictionary.swift), which aren't exposed publicly but could be copied into your project.

**Comment by gfontenot** [comment]
Usage would then look something like:

```swift
let deserialized = NSJSONSerialization // blah blah blah
let json = JSON.parse(deserialized)
let correctedJSON = convertEmptyStrings(json)
let user = User.decode(correctedJSON)
```

**Comment by jshier** [comment]
This implementation worked well, however it turned out that, for the response I was parsing, empty strings were sometimes legitimate values and sometimes meant no value. So I ended up using a combination of this function and the alternative operator which turned values that needed to be empty strings back into strings when they couldn't be decoded from nil.

**Comment by gfontenot** [comment]
@jshier I'm going to go ahead and close this as it seems like this is resolved? If you have any other questions about this feel free to re-open.
