### ISSUE TITLE
About install

### ISSUE THREAD

**Issue by cconecode** [thoughtbot/Argo#312]
When I use carthage install the Argo，It‘s spent a lot of time to Fetching LlamaKit，And finally, it's failure

**Comment by tonyd256** [comment]
@cconecode you're probably on a very old version of Argo. LlamaKit doesn't exist anymore and is now called Result. However, Argo has no dependencies itself. Perhaps check your Cartfile and Cartfile.resolved and make sure there isn't a weird version of Argo specified somewhere. Also make sure LlamaKit isn't specified in either of those files.

**Comment by tonyd256** [comment]
Closing this for now. @cconecode let me know if you're still having issues.
