### ISSUE TITLE
Optional Date Parse

### ISSUE THREAD

**Issue by RLovelett** [thoughtbot/Argo#316]
I'm hoping this is possible and my hope is that my functional foo is not high enough yet to understand how to do this properly yet.

Effectively what I'd like to do is decode a `JSON.String` into a `NSDate` and fail if it doesn't decode properly and for another decode a `JSON.String` into a `NSDate?`. For the sake of this discussion the two properties are `always` and `sometimes`. As you can probably infer `always` should fail decoding if it doesn't decode properly and `sometimes` should decode successfully and return `Optional.None` if it doesn't.

Below is some code that gets me most of the way there.

```swift2
struct DecodedObj: Decodable {
  let always: NSDate
  var sometimes: NSDate?

  internal static func decode(json: JSON) -> Decoded<DecodedObj> {
    return curry(DecodedObj.init)
      <^> json <| "always"
      <*> json <|? "sometimes"
  }
}

extension NSDate: Decodable {
  public typealias DecodedType = NSDate

  static func parseISO8601(string: String,
    locale: NSLocale = NSLocale.autoupdatingCurrentLocale(),
    timeZone: NSTimeZone = NSTimeZone.systemTimeZone()) -> NSDate?
  { ... }

  public static func decode(json: JSON) -> Decoded<NSDate> {
    switch json {
    case .String(let jsonString):
      guard let result = NSDate.parseISO8601(jsonString).map(pure) else { fallthrough }
      return result
    default:
      return .typeMismatch("ISO8601 Date", actual: json)
    }
  }
}
```

```json
{
  "always": "2016-01-05T070808.34+00:00",
  "sometimes": "2016-01-05T070808.34+00:00"
}
```
:heavy_check_mark:  Expect `sometimes` to be `Decoded.Success(Optional.Some(NSDate))`.

```json
{
  "always": "2016-01-05T070808.34+00:00",
  "sometimes": "TODO"
}
```
:x: Expect `sometimes` to be `Decoded.Success(Optional.None)`. Get `Decoded.Failure()`

```json
{
  "always": "2016-01-05T070808.34+00:00",
  "sometimes": null
}
```
:heavy_check_mark: Expect `sometimes` to be `Decoded.Success(Optional.None)`.

I guess the first question: is this even possible with Argo? The second is how would you go about it?

(Sorry if this is the wrong place. Or if it's been asked, I tried searching to no avail.)

**Comment by jshier** [comment]
Easiest way to get the behavior you want is to use the `alternative` operator `<|>` like this: `json <|? "sometimes" <|> pure(nil)`. That means, if the expression on the left fails, the expression on the right is used instead. See 'Alternative.swift` for more detail.

**Comment by RLovelett** [comment]
Gracias. So simple I wish I had realized that _without_ asking. I feel foolish now.

Again thank you. :clap:

**Comment by gfontenot** [comment]
Interesting use case! Don't feel foolish. This stuff isn't easy. Please feel free to open issues any time you have any questions.
