### ISSUE TITLE
Expression was too complex to be solved in reasonable time

### ISSUE THREAD

**Issue by RobinChao** [thoughtbot/Argo#321]
Expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions.

How  to  fix this??

**Comment by jhihguan** [comment]
I'm also encountering this issue, I ended up using 
`MyObject.create`
But it needs lots of effort...
[sample](https://github.com/jhihguan/JSON2Realm/blob/master/JSON2RealmTests/ArgoRealm.swift)

**Comment by tonyd256** [comment]
Hey all, We have some some workarounds that help with the issue. Please refer to #272 for more info.
tldr: Curry the init separately from the rest and break up the chain if you have really big models.

```swift
let f = curry(MyObject.init)
return f
  <^> ...
  <*> ...
```

You can then break up that chain if it's too long into other intermediate constants.
