### ISSUE TITLE
Help Parsing Weird JSON

### ISSUE THREAD

**Issue by bryanbartow** [thoughtbot/Argo#323]
I'll start off by saying I have absolutely no control over this JSON. The obvious answer is to fix it but, unfortunately, I can't.  So, here it is:

```json
{
  "success": true,
  "attemptId": "196929924007358",
  "pages": 1,
  "positions": {
    "1": [
      1,
      2
    ]
  }
}
```

I've tried several things, but I can't get that positions object to parse / decode. I should also point out that the positions object can have a variable number of children, all of whose keys are strings whose value is a number.  Anyone had any luck with a similar JSON object?

**Comment by tonyd256** [comment]
@bryanbartow What have you tried? I think there could be different ways to parse this depending on what you're trying to get as an end result.

You'll probably have to parse it out separately as a `[String: JSON]` then iterate over that manually to get what you want.

**Comment by bryanbartow** [comment]
@tonyd256 I actually don't care because I'm not using it. I just want to be able to parse the rest of the object and there's no way that I know of to skip over or dismiss it. Maybe I'm missing something?

**Comment by tonyd256** [comment]
If you don't need it then you simply don't parse it. Don't have a field for it in your model. Then you won't have to try and decode that section.

**Comment by bryanbartow** [comment]
My bad. I thought the lib expected to match every property in the JSON to a property on your model.

**Comment by tonyd256** [comment]
Thanks for bringing this up. I don't think we explicitly say it anywhere, but Argo will only attempt to decode things you tell it to. You can have as much extra stuff in your JSON as you'd like. I'll close this since it seems like that was the issue. Feel free to comment again if this is not resolved or open a new issue of other things.

**Comment by bryanbartow** [comment]
As a follow up, can you have a property in your model object that you don't attempt to initialize from the JSON object?

**Comment by tonyd256** [comment]
You would have to have a specific initializer that would only take in the parameters from the parsing and provide defaults for the others. It would get really tricky to partially apply some of the init parameters.
