### ISSUE TITLE
Map two JSON properties to the same attribute

### ISSUE THREAD

**Issue by RLovelett** [thoughtbot/Argo#326]
I have a JSON object that can come in one of two formats. Sometimes the property is called `notes` other times it is called `text`. In either case it refers to the same property of my Swift struct.
```json
{
  ...
  "notes": "bearing, range, and Doppler "
}
```
or
```json
{
  ...
  "text": "bearing, range, and Doppler "
}
```

The below code does not compile, `Cannot convert value of type '(text: String?) -> Data' to expected argument type '(_) -> _'`.
 
```swift
struct Data: Decodable {
  let text: String?

  static func decode(json: JSON) -> Decoded<Data> {
    return curry(Data.init) <^> ((json <| "text") <|> (json <|? "notes"))
  }
}
```

 I really thought that would have been the syntax. Any suggestions?

**Comment by RLovelett** [comment]
I also have tried this: `<^> (json <| "text") <|> (json <| "notes") <|> pure(Optional<String>.None)` to no avail. Same compiler error as above.

**Comment by RLovelett** [comment]
I finally got it! `<^> Decoded.Success(((json <| "text") <|> (json <| "notes")).value)`.

Is this the most idiomatic solution to the problem?

**Comment by gfontenot** [comment]
I almost feel bad for giving you the answer, because you were _so_ close! You actually have a bit of extra syntax, and we have a helper function available for making a property optional:

```swift
<^> .optional((json <| "text") <|> (json <| "notes"))
```

This should work the way you expect.

**Comment by RLovelett** [comment]
Gah! You were right I was so close. Thank you for the help though.

**Comment by gfontenot** [comment]
My pleasure, glad you got it working!
