### ISSUE TITLE
Parsing dictionary from nested key

### ISSUE THREAD

**Issue by alexth** [thoughtbot/Argo#327]
Hello, @thoughtbot!
Thanks for such a cool library!
I am very beginner, and have an issue with parsing JSON.
My JSON structure is like:

```json
{
    "profile": {
        "email": "email@email.io",
        "full_name": "Name",
        "id": 319935,
        "photo": {
            "is_placeholder": false,
            "url": "http://user/photo/220023/default_3d8e0dbb8d7f2c716cb55a525ffcafa6.png"
        },
        "updated_at": "2016-02-15T07:23:58.826-07:00"
    },
    "success": true
}
```

And model is like this:

```swift
rotocol User {
    var id: Int64? {get}
    var name: String? {get}
    var email: String? {get}
    var photo: String? {get}
    var updatedAt: String? {get}
}

struct UserResponse: User {
    let id: Int64?
    let name: String?
    let email: String?
    let photo: String?
    let updatedAt: String?
}

extension UserResponse: Decodable {
    static func decode(json: JSON) -> Decoded<UserResponse> {
        return curry(UserResponse.init)
            <^> json <|? "id"
            <*> json <|? "name"
            <*> json <|? "email"
            <*> json <|? "photo"
            <*> json <|? "updated_at"
    }
}
```
I want to read values from nested "profile" dictionary and "url", what is one more level deep, but not sure how to access them properly. What is the right signature for decode() in this case?

Best regards,
Alex

**Comment by gfontenot** [comment]
We provide a special array based syntax for accessing nested values. The array of strings that you pass reflects the path to get to the value you want. So, for example, if you wanted to parse:

```json
{
  "foo": {
    "bar": {
      "baz": "value"
    }
  }
}
```

you could do so with:

```swift
let val: Decoded<String> = j <| ["foo", "bar", "baz"]
```

So in your case, you could change your parser to pull out the nested photo url:

```swift
extension UserResponse: Decodable {
    static func decode(json: JSON) -> Decoded<UserResponse> {
        return curry(UserResponse.init)
            <^> json <|? "id"
            <*> json <|? "name"
            <*> json <|? "email"
            <*> json <|? ["photo", "url"]
            <*> json <|? "updated_at"
    }
}
```

At this point we still aren't pulling out the root key, but now we have a couple of options, depending on where we are in the parsing process.

If we've already passed the `AnyObject` returned from `NSJSONSerialization` through `JSON.parse` (resulting in a `JSON` object), we can pull the root key manually and then `flatMap` it into `UserResponse.decode`:

```swift
let json: JSON = // from JSON.parse
let user = (json <| "profile") >>- UserResponse.decode
// or if you're operator-averse
let user = (json <| "profile).flatMap(UserResponse.decode)
```

Alternatively, if you _haven't_ passed the `AnyObject` through `JSON.parse`, you can use our handy `decodeWithRootKey` function to do the whole thing in one step:

```swift
let user: UserResponse?

if let object = NSJSONSerialization.blahblahblah {
  user = decodeWithRootKey("profile", object)
} else {
  user = .None
}
```

You could _also_ use the array syntax to just add `profile` to the path for each object, but we'd generally recommend pulling a common root key at the highest level like described here.

**Comment by gfontenot** [comment]
UNRELATED ADVICE: It might be a good idea to audit your JSON API and reflect non-optional properties as such with your types. You'll still be able to decode safely using Argo and you'll end up with a more pleasant model object to work with in your app.

**Comment by alexth** [comment]
Wow, looks like I am late to the party...
@gfontenot , thank you very much for such an detailed explanation!
Actually, I made it another way, maybe even simpler.
I just created another UserResponse object with fields of nested dictionary and set is as a property in UserResponse protocol and struct

**Comment by gfontenot** [comment]
@alexth 💯 

Is this resolved now? Can we close it?

**Comment by alexth** [comment]
@gfontenot , sure, thanks!
