### ISSUE TITLE
swiftc failed with exit code 1 when trying to parse a Dictionary ( [String : JSON] )

### ISSUE THREAD

**Issue by kaosdg** [thoughtbot/Argo#328]
Hi, I'm getting this error when compiling my code `swiftc failed with exit code 1` when trying to parse a field in my JSON response to a Dictionary.

Digging deeper into the error, LLVM is choking on this:
```
Call parameter type does not match function signature!
%O4Argo7Decoded.31* %0
 %O4Argo7Decoded.32*  tail call void @_TZFeRq_Ss28DictionaryLiteralConvertibleqq_S_5Value4Argo9Decodablezqq_S_5Valueqqq_S_5ValueS1_11DecodedType_S0_S_6decodeuRq_S_qq_S_5ValueS1_zqq_S_5Valueqqq_S_5ValueS1_11DecodedType_fMq_FOS0_4JSONGOS0_7DecodedGVSs10DictionarySSqq_S_5Value__(%O4Argo7Decoded.31* noalias nocapture sret %0, %O4Argo4JSON* noalias nocapture dereferenceable(25) %1, %swift.type* %5, %swift.type* %6, i8** @_TWPu0_Rq_Ss8Hashable_GVSs10Dictionaryq_q0__Ss28DictionaryLiteralConvertibleSs, %swift.type* @_TMdSS, %swift.type* @_TMdO4Argo4JSON, i8** @_TWPO4Argo4JSONS_9DecodableS_) #0, !dbg !586
LLVM ERROR: Broken function found, compilation aborted!
```

Following all examples I could find of parsing a field into a Dictionary, here's my code:
```
public typealias Options = [String : JSON]

public class ScreenFeed: BaseFeed {
    public let id: String
    public let type: String
    public let url: String
    public let zones: [Zone]
    public let options: Options
    public let urlTimeStamp: Int
    
    init(envelope: Envelope, status: Status, id: String, type: String, url: String, zones: [Zone], options: Options, urlTimeStamp: Int) {
        self.id = id
        self.url = url
        self.zones = zones
        self.options = options
        self.urlTimeStamp = urlTimeStamp
        self.type = type
        
        super.init(envelope: envelope, status: status)
    }
}

extension ScreenFeed: Decodable {
    public typealias DecodedType = ScreenFeed
    public static func create
        (envelope: Envelope)
        (status: Status)
        (id: String)
        (type: String)
        (url: String)
        (_ zones: [Zone])
        (_ options: Options)
        (_ urlTimeStamp: Int)
        -> ScreenFeed {
            return ScreenFeed(envelope: envelope, status: status, id: id, type: type, url: url, zones: zones, options: options, urlTimeStamp: urlTimeStamp)
    }
    
    public static func decode(json: JSON) -> Decoded<ScreenFeed> {
        let decoded = ScreenFeed.create
            <^> json <| "envelope"
            <*> json <| "status"
            <*> json <| ["data", "screen", "id"]
            <*> json <| ["data", "screen", "type"]
            <*> json <| ["data", "screen", "url"]
            <*> json <|| ["data", "screen", "zones"]
            <*> (json <| ["data", "screen", "options"] >>- Options.decode)
            <*> json <| ["data", "screen", "urlTimestamp"]
        return decoded
    }
}
```

Sample json:  http://myjson.com/1rsnv

I've tried not using `typealias`, tried `[String : String]` (or any combination of `Decodable`'s) and still get the same error.

Essentially, I need to pass my `options` field back as a Dictionary to the app, as it can have an unknown number of Keys, with any type of value (valid JSON decodable types) - thus making a concrete 1:1 Swift object impossible for this field.

Am I doing something wrong with Argo here?
Is there another way to do this?  

Thanks in advance

**Comment by jshier** [comment]
I get the same error, or quite similar, when using Argo as a CocoaPod and building with optimizations on. My only recourse has been to bundle Argo directly with my code. Have tried the Xcode 7.3 betas yet though.

**Comment by kaosdg** [comment]
@jshier interesting, I am using Cocoapods to bring Argo in.

**Comment by kaosdg** [comment]
So barring turning off optimizations - does anyone have an alternative way to simply pull in a dictionary of [String : JSON]?  I see a few other issues in the repo, but those all lead to the approach I am taking which is causing compiler issues.

How would I just import that field as a raw JSON string, while modeling the rest of the JSON?

**Comment by jshier** [comment]
Raw JSON or Argo's `JSON` type? To decode said dictionary, you can use:
```swift
(json <| "label" >>- { [String : JSON].decode($0) })
```
That will give you Argo's `JSON` type.

**Comment by jshier** [comment]
In regards to the crash, I just rebuilt my project with Argo as a pod on Xcode 7.2 and it successfully built using whole module optimization. First time that's been possible in quite a while.

**Comment by jshier** [comment]
FYI, I use this hook to set whole module optimization for all of my Pods:
```ruby
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.name == 'Release'
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Owholemodule'
      else
        config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
      end
    
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```
Also turns bit code off, which I may not need any more.

**Comment by kaosdg** [comment]
with -Owholemodule optimization, I am getting link errors form another lib I am using in our app. 

regarding `(json <| "label" >>- { [String : JSON].decode($0) })` this works well enough, though I'll have to have a second step I suppose when accessing the values within (since it's an Argo.JSON type).

**Comment by jshier** [comment]
Unless you need the flexibility of an arbitrary dictionary, having an actual model type that's decoded is usually much more useful and easier to work with.

**Comment by kaosdg** [comment]
unfortunately, that options field is always going to be an arbitrary dictionary.  It's more or less hand-written JSON that is passed to the app, to be passed to our reporting system (not the best way, but it's what I have to work with)

**Comment by gfontenot** [comment]
Yeah, you _should_ be able to use @jshier's suggestion of using `[String: JSON].decode`. In the next version of Argo, we're re-adding the `decodeObject` free function, which will make it look a little nicer, as well. And then long term, once we get the ability to have types conditionally conform to protocols, we'll be able to make this all invisible by making `[String: T]` decodable when `T: Decodable`.

Note that you don't _have_ to use the closure or the argument, and if you prefer you could opt for:

```swift
json <| "label" >>- [String: JSON].decode
```

Unfortunately, Argo _needs_ to have a concrete type to decode to, so there's no way to make this work with `[String: AnyObject]` (at least, not out of the box, you might be able to use a companion lib like [Ogra](https://github.com/edwardaux/Ogra) to help here).

@jshier I'm intrigued by the compiler optimization issues. Are they resolved for you? If not, would you mind opening an issue so that we can discuss them directly?

**Comment by jshier** [comment]
They seem to be resolved now, as I was able to integrate Argo as a pod this weekend. But it was essentially the same issue originally reported. Something about optimization and Argo as a pod (or perhaps just a framework in general, I never tested that) caused the compiler to mismatch the function signatures and bail out. My only option was to integrate Argo directly into the project. I reported the crash to Apple but never heard anything. I'll see if I can find the output.

**Comment by jshier** [comment]
Here's what I was seeing, using Xcode 7.2 beta 2:
```
%O4Argo7Decoded.21* %0
 %O4Argo7Decoded.17*  tail call void @_TZFeRq_Ss14CollectionTypeqqq_S_9GeneratorSs13GeneratorType7Element4Argo9Decodablezqqq_S_9GeneratorS0_7Elementqqqq_S_9GeneratorS0_7ElementS2_11DecodedType_S1_S_6decodeuRq_S_qqq_S_9GeneratorS0_7ElementS2_zqqq_S_9GeneratorS0_7Elementqqqq_S_9GeneratorS0_7ElementS2_11DecodedType_fMq_FOS1_4JSONGOS1_7DecodedGSaqqq_S_9GeneratorS0_7Element__(%O4Argo7Decoded.21* noalias nocapture sret %0, %O4Argo4JSON* noalias nocapture dereferenceable(25) %1, %swift.type* %5, %swift.type* %6, i8** @_TWPurGSaq__Ss14CollectionTypeSs, %swift.type* %7, i8** @_TWPuRq_Ss9Indexable_GVSs17IndexingGeneratorq__Ss13GeneratorTypeSs, %swift.type* @_TMdV3ECO22SomeCustomType, i8** @_TWPV3ECO22SomeCustomType4Argo9DecodableS_, %swift.type* @_TMdSi, i8** @_TWPSiSs16ForwardIndexTypeSs, %swift.type* @_TMdSi, i8** @_TWPSiSs18_SignedIntegerTypeSs, %swift.type* @_TMdSi, i8** @_TWPSiSs33_BuiltinIntegerLiteralConvertibleSs, %swift.type* @_TMdSi, %swift.type* %8, i8** @_TWPurGVSs10ArraySliceq__Ss9IndexableSs, i8** @_TWPurGVSs10ArraySliceq__Ss12SequenceTypeSs, %swift.type* %9, i8** @_TWPuRq_Ss9Indexable_GVSs17IndexingGeneratorq__Ss13GeneratorTypeSs, %swift.type* @_TMdV3ECO22SomeCustomType, %swift.type* @_TMdSi, i8** @_TWPSiSs16ForwardIndexTypeSs, %swift.type* @_TMdSi, i8** @_TWPSiSs18_SignedIntegerTypeSs, %swift.type* @_TMdSi, i8** @_TWPSiSs33_BuiltinIntegerLiteralConvertibleSs, %swift.type* @_TMdSi, %swift.type* %8, %swift.type* @_TMdV3ECO22SomeCustomType, %swift.type* @_TMdV3ECO22SomeCustomType) #0, !dbg !893
LLVM ERROR: Broken function found, compilation aborted!
```

**Comment by gfontenot** [comment]
Is this still an issue for anyone, or can it be closed?

**Comment by gfontenot** [comment]
I'm going to go ahead and close this due to inactivity but please feel free to reopen if this is still an issue.
