### ISSUE TITLE
Decoding nested objects that do not contain all the values as the inital object alone

### ISSUE THREAD

**Issue by matejaSkr** [thoughtbot/Argo#331]
I have a document structure with decode function that looks like this:

```swift
struct Document {
    let id: Int
    let name: String?
    let url: String
    let createdAt: NSDate
    let owner: User
}

static func decode(json: JSON) -> Decoded<Document> {
        let document = curry(self.init)
        return document
            <^> json <| "id"
            <*> json <|? "name"
            <*> json <| "url"
            <*> (json <| "created_at" >>- fromLongServerDateToNSDate)
            <*> json <| "owner"
}
```

There is also a milestone struct that contains an embedded list  of documents. However, when document is part of this embedded list, it does not contain createdAt and owner properties. Milestone that contains list of documents looks something like this:

```swift
struct Milestone {
    let id: Int
    let documents: [Document]
}

static func decode(json: JSON) -> Decoded<Milestone> {
        let milestone = curry(self.init)
        return milestone
            <^> json <| "id"
            <*> json <|| "documents"
 }
```

And the json that needs to be decoded here looks like this: 

```json
{
	"id": 1,
	"documents": [{
		"id": 522,
		"name": "<null>",
		"url": "https://url-example.com"
	}, {
		"id": 523,
		"name": "name",
		"url": "https://url-example.com"
	}]
}
```

Is there a way I can use existing document structure to decode document when is embedded in milestone object without having to use optionals for createdAt and owner properties? Also, I know that I could use a different structure for embedded documents in milestone object that would only contain id, name and url but is there any other solution to this?

**Comment by alskipp** [comment]
Unless you have sensible default values for `createdAt` & `owner` (which is unlikely), I think the only option is to make these field optional, or to have a separate data structure for these abbreviated models.

**Comment by gfontenot** [comment]
Yeah, like @alskipp said, the only real options are to mark those properties as `Optional`, or to use a different data structure. In theory, you could be polymorphic about it by introducing a new protocol:

```swift
protocol Document {
  var id: Int { get }
  var name: String? { get }
  var url: NSURL { get }
}

struct CompleteDocument: Document {
  let id: Int
  let name: String?
  let url: String
  let createdAt: NSDate
  let owner: User
}

struct PartialDocument: Document {
  let id: Int
  let name: String?
  let url: String
}
```

Not sure if there's really a better way than this, but I'd be interested to hear if people have found one.

**Comment by gfontenot** [comment]
@matejaSkr Did that help at all? Were you able to figure out a better way?

**Comment by gfontenot** [comment]
I'm going to go ahead and close this due to inactivity but please feel free to reopen if this is still an issue.
