### ISSUE TITLE
Major issues with optimized Release build

### ISSUE THREAD

**Issue by mattrubin** [thoughtbot/Argo#34]
Summary: The "Fastest [`-O`]" optimization level used by a release build breaks Argo, with behavior ranging from incorrect to crashy.

---

I first noticed this issue when using Argo via Carthage. I linked my code to the Mac framework produced by `carthage build` (which uses the Release configuration by default). I tried to parse the following JSON:

``` json
{
    "from": "Alpha",
    "to": "Omega"
}
```

The JSON object produced by `NSJSONSerialization.JSONObjectWithData()` is correct:
```
{
    from = Alpha;
    to = Omega;
}
```

However, the output from `JSONValue.parse(jsonObject)` was:
```
Object([to: Null, from: Null])
```

When using a Debug build of the framework (via `carthage build --configuration Debug`) the output is correct:
```
Object([to: String(Omega), from: String(Alpha)])
```

---

Running Argo's own tests in Release configuration (by changing the Test configuration for the current scheme) leads to several issues. Most of the tests fail before a call to `XCTAssertEqual()` brings the whole thing crashing to a halt with an `EXC_BAD_INSTRUCTION (code=EXC_I386_INVOP, subdued=0x0)`.

The cause of the issue seems to be the compiler's optimization. Swapping the `SWIFT_OPTIMIZATION_LEVEL` setting between Fastest [`-O`] and None [`-Onone`] appears to toggle these issues.

---

Additional info: I'm building with Xcode 6.1.1 (6A2008a) on OS X 10.10.1 (14B25). I haven't tried this yet with the latest Xcode beta.

**Comment by mattrubin** [comment]
It looks like this issue is related to the problems with `flatMap` in #33. Replacing all instances of `json >>- JSONValue.parse` in ArgoTests with `(JSONValue.parse <^> json)` fixes both the test failures and the `EXC_BAD_INSTRUCTION`s I was seeing in Release configuration.

**Comment by gfontenot** [comment]
Good catch with the tests. Really wish Swift wouldn't let that mistake compile.

I'm not seeing how this would help your production code though. Did you make a change to your parser as well?

Working on a PR to change to tests over to the release scheme and fix them up. Should be up shortly.

**Comment by gfontenot** [comment]
@mattrubin Fix for the tests is over at #35. I'd love to know if this somehow fixes the issues you're seeing in production (although, again, I'm not sure how it would).

**Comment by mattrubin** [comment]
My issue was actually fixed in PR #33, so once I upgraded to [0.3.1](https://github.com/thoughtbot/Argo/releases/tag/v0.3.1) my code was fine. Thanks!

---

I've been going back and forth on whether it's a good idea to add a function to divert to `map` when the compiler allows the `flatMap` operator to be used incorrectly:
``` swift
public func >>-<T, U>(a: T?, f: T -> U) -> U? {
    return a.map(f)
}
```
I'm afraid this might encourage incorrect use of the `>>-` operator, but if that mistake's already being made with no warnings, it would at least ensure the code ran as intended.

**Comment by gfontenot** [comment]
I'm pretty sure that would end up with ambiguous function definitions (since in Swift `String?` could be `U` _or_ `U?`). The mistakes are really our fault though. I'd rather just try to Be Better At Things than encourage the use of the wrong operator.

Glad to hear this is all working again. It was worth it to move our tests over to the release scheme anyway. I'm going to close this for now. We can reopen if issues present themselves in the future.

**Comment by mattrubin** [comment]
I agree it's better to catch our mistakes than cater to them.

For future reference, I've found this snippet does a great job throwing errors for incorrect uses of `>>-` with optionals that the compiler would otherwise allow:
``` swift
@availability(*, unavailable, message="map (<^>) should be used instead of flatMap (>>-) here.")
public func >>-<T, U>(a: T?, f: T -> U) -> U? {
    return a.map(f)
}
```

**Comment by gfontenot** [comment]
Oh, interesting idea. I might steal that. Thanks!
