### ISSUE TITLE
Can't deserialize array?

### ISSUE THREAD

**Issue by eestein** [thoughtbot/Argo#355]
Hi!
I'm trying to deserialize an array, but I think I might be doing something wrong.

`let returnData2: Decoded<[TransactionInformation]> = decode(data)`

Argo is working, only for this case it doesn't. It says:

![screen shot 2016-04-04 at 14 35 46](https://cloud.githubusercontent.com/assets/2049255/14257164/d321d932-fa72-11e5-94f9-67349af37d54.png)

It expected an Array but got a String? I don't understand what's wrong there, since the String seems to be in the correct JSON format for Arrays. 

Any ideas?

Thanks!

**Comment by gfontenot** [comment]
hmm, that type mismatch error seems incorrect. It _looks_ like you're trying to deserialize a string into an array, which isn't right. Can you post the JSON you're trying to decode? I think it might also help to see where `data` is coming from.

**Comment by gfontenot** [comment]
Oh, I see. Nevermind. The type mismatch error looks correct. I misread the debugger output.

**Comment by eestein** [comment]
:)
Ok, in any case here's the JSON:

https://gist.github.com/eestein/09de19cc34e54517b76b2490b1c1bdcd

Any ideas?

**Comment by gfontenot** [comment]
Gotcha, yeah. That JSON is technically malformed, so we can't really fix it internally. Arrays are an actual data type in JSON, so they shouldn't be sent as strings. You can see an example of a properly formed JSON array in our [test file for decoding a post with comments](https://github.com/thoughtbot/Argo/blob/master/ArgoTests/JSON/post_comments.json).

**Comment by eestein** [comment]
@gfontenot thanks for that, is there a way to change its type on-the-fly? I need to return a String because Message's content can be several different classes. The outer structure is the same for all requests, only the Message property changes. 
I'm actively looking for a solution since Message must be a string. Please let me know if you have any solution in mind.

Thanks!

**Comment by eestein** [comment]
@gfontenot thanks for your help. I was able to fix that using this solution:

http://stackoverflow.com/questions/25621120/simple-and-clean-way-to-convert-json-string-to-object-in-swift

Cheers!
