### ISSUE TITLE
Is it possible to use generics with Argo?

### ISSUE THREAD

**Issue by eestein** [thoughtbot/Argo#357]
Hi :)
Is it possible?

As I've stated here: https://github.com/thoughtbot/Argo/issues/355 I return different classes in a JSON String. As you can imagine, I'm not willing to write one method for every possible class I have (DRY). So I'm trying to use generics. Here's my code:

![screen shot 2016-04-04 at 15 33 00](https://cloud.githubusercontent.com/assets/2049255/14258827/8c8f5bb8-fa7a-11e5-9a91-8c98d071d68d.png)

I've read some questions on SO regarding this error and all the solutions involved specifying the class I was targeting, which I can't since I'm trying to use generics.

FYI: I'm new to swift, so even though I read the book and rechecked before posting I could be doing something wrong in my generics implementation.

**Sorry if it's not related directly to Argo, I really don't know if it's Argo, Swift or me here...**

**Comment by gfontenot** [comment]
Yeah, you can do this provided that you're typing the callback. At that point it'll work.

You'll also want to add a type constraint to your generic definition. Specifically, it should look like:

```swift
<T: Decodable where T.DecodedType == T>
```

This will let the compiler know that this type is able to be decoded to.

**Comment by eestein** [comment]
Thanks again @gfontenot  :) 
It was my swift inexperience after all!
