### ISSUE TITLE
Argo 3 breaks implicit Number -> Bool conversion

### ISSUE THREAD

**Issue by jshier** [thoughtbot/Argo#358]
With the addition of an actual `JSON.Bool` case, it seems that the implicit `.Number` conversion to `Bool` has been broken. Was this intentional? It's unfortunately common for backend software to return boolean values as `1` or `0`. Previously Argo was able to automatically convert these to `Bool`. Now that's no longer possible. I believe the previous behavior could be returned by adding the previous behavior back to the `Bool` `Decodable` extension:
```swift
extension Bool: Decodable {
  /**
    Decode `JSON` into `Decoded<Bool>`.

    Succeeds if the value is a boolean, otherwise it returns a type mismatch.

    - parameter j: The `JSON` value to decode

    - returns: A decoded `Bool` value
  */
  public static func decode(j: JSON) -> Decoded<Bool> {
    switch j {
    case let .Bool(n): return pure(n)
    case let .Number(n as Bool): return pure(n)
    default: return .typeMismatch("Bool", actual: j)
    }
  }
}
```
Would that be an acceptable change?

**Comment by gfontenot** [comment]
Ah, crap. Sorry. Yeah, this is inline with the way of handling `Int` values, so it makes sense to me.

**Comment by jshier** [comment]
Want me to do a PR or is it something you can do quickly?

**Comment by gfontenot** [comment]
I'm happy to submit a PR if you'd like.

**Comment by gfontenot** [comment]
done
