### ISSUE TITLE
latest 3.0.1 doesnt compile on xcode 7.3 using cocoapods

### ISSUE THREAD

**Issue by dogeri28** [thoughtbot/Argo#362]
Use of undeclared type DecodedType 

In protocol file Decodable

### Argo Version

 Argo 3.0.1_

### Dependency Manager

Cocoapods,

**Comment by gfontenot** [comment]
This should work, we've heard no other reports of it failing to compile. Are you sure you're on Xcode 7.3?

**Comment by dogeri28** [comment]
my sincere apologies , just realised i am not running xcode 7.3 .
RegardsSunday
 

    On Tuesday, 12 April 2016, 19:56, Gordon Fontenot <notifications@github.com> wrote:
 

 This should work, we've heard no other reports of it failing to compile. Are you sure you're on Xcode 7.3?—

**Comment by gfontenot** [comment]
No worries, glad I wasn't crazy. Feel free to let me know if you run into any other issues.
