### ISSUE TITLE
Question : Could we add helper functionality for easy Serialization of Swift structs/classes?

### ISSUE THREAD

**Issue by flangel** [thoughtbot/Argo#364]
Hi,

helper functionality to easily create JSON from structs and classes would come in handy and increase the value of the module. Any plans in that area ?

Thanks a lot 
Frank

**Comment by gfontenot** [comment]
This has come up a number of times, and isn't something we feel like fits in with the goal of Argo (type-safe flexible JSON parsing). Moving from a strongly typed system to a loosely typed system is much more straightforward, and we haven't felt a real need for it as a library in our own apps.

That being said, there are a number of people that _do_ feel that need out there, and some have gone through the work of implementing their own libraries to work alongside Argo to do so. For example, @edwardaux has created [Ogra](https://github.com/edwardaux/Ogra) to fill this need.
