### ISSUE TITLE
How to parse a dictionary in an array in a dictionary?

### ISSUE THREAD

**Issue by jeroenleenarts** [thoughtbot/Argo#365]
I'm trying to grasp Argo when dealing with somewhat weird constructs in JSON.

Any thoughts on this?

### Sample JSON

```
{
    "Session": [
        {
            "Token": "some string based GUID",
        }
    ]
}
```

### Models

```
public class Session {
    var token: String?
}

extension Session : Decodable {
    public typealias DecodedType = Session
    
    public static func decode(json: JSON) -> Decoded<Session> {
        let session = Session()
        session.token = json <| "Token"
        
        return .Success(session)
    }
    
}
```

### Argo Version

Argo 2.3.0

**Comment by gfontenot** [comment]
so is `"Session"` always populated with a single element array that is a dictionary? That's a wacky API...

You'll basically need to do 3 things:

1. Extract the `[JSON]` from the `"Session"` key
2. Get the first element from the `[JSON]`
3. Try to pull the `"Token"` key from that `JSON` and assign it to `session.token`

It's hard to say _where_ these responsibilities should go. I could make arguments for a bunch of different techniques. But basically, if we just take the core issue of going from `[String: [JSON]]` to `String`, it might look something like:

```swift
let json: JSON = // the JSON object

// Step 1
let sessionDict: Decoded<[JSON]> = json <|| "Session"

// Step 2
let firstElement: Decoded<JSON> = sessionDict.map { $0.first ?? JSON.Null }

// Step 3
let token: Decoded<String> = firstElement.flatMap { $0 <| "Token" }
```

That final `flatMap` is kind of unfortunate, but step 2 kind of forces us into it.

**Comment by jeroenleenarts** [comment]
Silly me. :) It seems to work as you described.

**Comment by gfontenot** [comment]
Not silly at all. This kind of thing is fairly unintuitive. Glad I could help!
