### ISSUE TITLE
Putting together data from several nodes

### ISSUE THREAD

**Issue by jedmund** [thoughtbot/Argo#367]
Hello, I'm trying to work with some JSON from my server that I realized I don't quite know how to translate into Argo.

I have three models, User, Project, and Post. A Project is owned by a User and returns the following JSON:

```json
"project": {
    "id": 1,
    "name": "My Cool Project",
    "user": {
        "id": 1,
        "name": "Justin"
    }
}
```

However, in order to reduce redundancy, I've removed the User node from the Project when it appears on a Post, because they will **always** have the same owner.
```json
"post": {
    "id": 1,
    "content": "Hello world!",
    "user": {
        "id": 1,
        "name": "Justin"
    },
    "project": {
        "id": 1,
        "name": "My Cool Project"
    }
}
```

However, since the Project model expects a User object and the data is technically there, I was wondering if there were a way to write to assign this data in a helper function.

### Models

Here is a sample of the relevant Post model:

```swift
struct Post {
    let id: Int
    let createdAt: NSDate
    
    let user: User
    let project: Project
    let content: String

    static let fromStringToNSDate: String -> Decoded<NSDate> = {
        .fromOptional(NSDateFormatter.standardFormatter().dateFromString($0))
    }
    
    static let fromJSONToUser: JSON -> Decoded<User> = {
        var userData: [String: JSON] = [:]
        userData["user"] = $0
        let encodedData = userData.encode()
        return Decoded<User>.fromOptional(User.decode(encodedData).value)
    }
    
    static let fromJSONToProject: JSON -> Decoded<Project> = {
        // $0 is the Project data, but can we get the User data here to complete the Project?
        var projectData: [String: JSON] = [:]
        projectData["project"] = $0
        let encodedData = projectData.encode()
        return Decoded<Project>.fromOptional(Project.decode(encodedData).value)
    }
    
}

extension Post: Decodable {
    static func decode(j: JSON) -> Decoded<Post> {
        let f = curry(Post.init)
        return f
            <^> j <| ["post", "id"]
            <*> (j <| ["post", "created_at"] >>- fromStringToNSDate)
            <*> (j <| ["post", "user"] >>- fromJSONToUser)
            <*> (j <| ["post", "project"] >>- fromJSONToProject)
            <*> j <| ["post", "content"]
    }
}
```

Essentially, I need to be able to parse `["post", "user"]` as is, but also pass it to the parser for `["post", "project"]` to join the two together to decode.

I _could_ make the User on the Project optional, and then assign it later, but I'm trying not to do that since it seems kind of messy to me.

I was thinking that maybe something in #177 or #284 might help, but I'm not really sure where to start, maybe a combinatory operator instead of alternate that I'm not aware of?

**Comment by gfontenot** [comment]
Fantastic question. You have to think outside the box just a bit.

In this case, I might update `fromJSONToProject` to  take the full `"post"` key JSON instead of the nested `"project"` JSON. At that point, you'll have everything you need and can pull the project, then pull the user.

A couple more points about the samples you sent: If you make `NSDate`, and `User` `Decodable`, you can get rid of those helper functions. It might also be good to pull the `"post"` root key _before_ getting to this `decode` function. That would remove the duplication and ensure that if you're dealing with an array that doesn't include a root key your parser already works.

**Comment by jedmund** [comment]
Thanks so much for the help! I managed to get it working—I didn't realize you could substitute an actual method after the `<*>` apply operator, which is what I needed to get up and running.

My `User` object was `Decodable`, but I ran into the exact problem you described and solved them with those helper functions. Then in researching for this issue I learned about the `<|>` alternative operator and refactored accordingly. Its still a bit messy though, so I wonder if theres anything I can do to clean it up.

Here's what I landed on:

```swift
struct Post {
    let id: Int
    let createdAt: NSDate

    let user: User
    let project: Project
    let content: String

    static let fromStringToNSDate: String -> Decoded<NSDate> = {
        .fromOptional(NSDateFormatter.standardFormatter().dateFromString($0))
    }

    static func fromJSONToProject(json: JSON) -> Decoded<Project> {
        // I wish I knew a better way
        guard
            let rootData = [String: JSON].decode(json).value,
            let postData = rootData["post"],
            let data = [String: JSON].decode(postData).value,
            let userData = data["user"],
            let projectData = data["project"],
            var projectObject = [String: JSON].decode(projectData).value else {
            fatalError() // We should edit more gracefully
        }
        
        projectObject["user"] = userData
        let encodedData = projectObject.encode()
        return Decoded<Project>.fromOptional(Project.decode(encodedData).value)
    }

}

extension Post: Decodable {
    static func decode(j: JSON) -> Decoded<Post> {
        let f = curry(Post.init)
        return f
            <^> (j <| "id") <|> (j <| ["post", "id"])
            <*> (((j <| "created_at") <|> (j <| ["post", "created_at"])) >>- fromStringToNSDate) // Still need to make NSDate decodable
            <*> (j <| "user") <|> (j <| ["post", "user"])
            <*> fromJSONToProject(j)
            <*> (j <| "content") <|> (j <| ["post", "content"])

    }
}
```

**Comment by gfontenot** [comment]
To a certain extent, what you really need is a more consistent JSON API. The more consistent _that_ is, the more concise your use of Argo can be.

For example, if you made sure to only ever send one root key, you could remove the use of `<|>` and pull the root key at a higher level in your networking architecture.

So only ever send:

```json
{
  "post": {
    "id": 1,
    "content": "Hello world!",
    "user": {
      "id": 1,
      "name": "Justin"
    },
    "project": {
      "id": 1,
      "name": "My Cool Project"
    }
}
```

or

```json
{
  "post": {
    "id": 1,
    "content": "Hello world!",
    "user": {
      "id": 1,
      "name": "Justin"
    },
    "projects": [
      {
        "id": 1,
        "name": "My Cool Project"
      }
    ]
}
```

but _never_ send

```json
{
  "post": {
    "id": 1,
    "content": "Hello world!",
    "user": {
      "id": 1,
      "name": "Justin"
    },
    "projects": [
      { "project":
        {
        "id": 1,
        "name": "My Cool Project"
        }
      }
    ]
}
```

Then you'd be able to do something like

```swift
let posts: [Post]? = (j <| "post").value
```

and remove all references to the `post` key in your parser.

**Comment by gfontenot** [comment]
That's kind of a bad example, but maybe you understand what I mean?

**Comment by jedmund** [comment]
I think I see what you're saying! That is helpful. I'm going to work at cleaning things up a bit, but the core problem in this issue is solved, so I'm going to close it.

Thanks!
