### ISSUE TITLE
Decode fails silently and returns nil

### ISSUE THREAD

**Issue by alper** [thoughtbot/Argo#369]
> If it fails, you will instead be given the reason why the User couldn't be constructed.

Well, if I have this:
`let userID: Int`

and it should actually be a String type, Argo returns me a nil and does not give me any hint why this didn't work.

**Comment by gfontenot** [comment]
sounds like you're decoding to `User?` instead of `Decoded<User>`. We can't add anything to `Optional`, but `Decoded` contains more useful info for debugging cases like this. In your example, you should end up with `Decoded.Failure(DecodeError.TypeMismatch(expected: "Int", actual: "foo"))`.

**Comment by alper** [comment]
Ok, but that is the exact example on the front page hence why I used it.

**Comment by gfontenot** [comment]
The text you're referring to is in the Ideology section of the documentation and makes no mention of the requested return type. It's being abstract. Are you requesting that we be more explicit in that documentation? Or are you requesting that we use `Decoded` in the basic usage in the README? I'd be more than happy to review a PR that fits your expectations better.

**Comment by gfontenot** [comment]
I'm going to close this because I'm not sure what the actionable outcome would be. Please feel free to re-open if you feel like there's something specific we can improve.

**Comment by alper** [comment]
No problem, to be able to contribute documentation I would need to seriously use Argo for a while I think.
