### ISSUE TITLE
Parsing JSON with Root Users Array

### ISSUE THREAD

**Issue by SSamanta** [thoughtbot/Argo#370]
I am facing parsing problem while creating objects from json
My code is 
` let users: Decoded<[User]> = json! <|| "users"`
### Error Messages
My users array is showing Error

![screen shot 2016-05-01 at 10 54 10 am](https://cloud.githubusercontent.com/assets/3451021/14940244/17f807fc-0f8b-11e6-83b4-74a420cfeedf.png)

### Sample JSON

![screen shot 2016-05-01 at 10 52 13 am](https://cloud.githubusercontent.com/assets/3451021/14940234/d7f08a9e-0f8a-11e6-9397-85259252e1d1.png)

### Models

_All models involved, including their `Decodable` implementations._

```
struct User {
    let id: String
    let name: String
    let attendingWebinars : [Webinar]
}

extension User: Decodable {
    static func decode(j: JSON) -> Decoded<User> {
        return curry(self.init)
            <^> j <| "id"
            <*> j <| "name"
            <*> j <|| "attending_webinars"
    }
}
```

### Argo Version

_example: Argo 3.0.0_

### Dependency Manager

_examples: Carthage, Cocoapods, git submodules, copied code, etc._

**Comment by gfontenot** [comment]
Looks like your model is expecting `id` to be a `String`, but the JSON is representing it as an `Int`. That's what the failure is trying to say as well. Changing the type in the model should fix the issue.

**Comment by SSamanta** [comment]
Thanks I figure it out forgot to close it closing now
