### ISSUE TITLE
Compiler error in `decode` method

### ISSUE THREAD

**Issue by sendyhalim** [thoughtbot/Argo#372]
Hi guys!

I was just trying out `Argo` and copy-pasted the example to xcode. There are compiler errors with the current example (first screenshot in `Error Messages` section), then I simplified the `User` struct with my own implementation (just 2 properties, `id` and `name`) and the compiler error still there (second screenshot)

### Error Messages
```
Cannot invoke `curry` with an argument list of type `((id: Int, name: String, email: String? companyName: String, friends: [User]) -> User)`
```
<img width="811" alt="screen shot 2016-05-06 at 20 54 59" src="https://cloud.githubusercontent.com/assets/3948217/15075109/d67e272a-13cc-11e6-903e-6842f747bfc5.png">

With the previous error message, I think that it would help if I define my own curried function (since the previous error seemed to be related with [`Curry`](https://github.com/thoughtbot/Curry), but even with the type-hinting that I provided, the compiler still couldn't infer the types. (The screenshot below is a simplified version of `User` struct provided in the example)

```
Cannot convert value of type `Int -> String -> User` to expected argument type `_ -> _ -> User`
```
<img width="817" alt="screen shot 2016-05-06 at 21 06 52" src="https://cloud.githubusercontent.com/assets/3948217/15075454/a4a77e34-13ce-11e6-9bbb-72ff38916f66.png">

### Sample JSON
Not provided yet

##### First attempt 
```swift
import Argo
import Curry

struct User {
  let id: Int
  let name: String
  let email: String?
  let companyName: String
  let friends: [User]
}

extension User: Decodable {
  static func decode(j: JSON) -> Decoded<User> {
    return curry(User.init)
      <^> j <| "id"
      <*> j <| "name"
      <*> j <|? "email" // Use ? for parsing optional values
      <*> j <| ["company", "name"] // Parse nested objects
      <*> j <|| "friends" // parse arrays of objects
  }
}
```
##### Second Attempt
```swift
import Argo
import Curry

struct User {
  let id: Int
  let name: String
}

extension User: Decodable {
  static func decode(j: JSON) -> Decoded<User> {
    let createUser: Int -> String -> User = { (id: Int) in
      return { (name: String) in
        return User(id: id, name: name)
      }
    }

    return createUser
      <^> j <| "id"
      <*> j <| "name"
  }
}
```

### Argo Version
Argo 3.0.1

### Dependency Manager
Tried with cocoapods and carthage

### XCode
```
xcodebuild -version
Xcode 7.3
Build version 7D175
```

**Comment by sidraval** [comment]
Hi @sendyhalim,

Strangely, every example you included builds just fine on my end. I'm using:

- Argo v3.0.1
- Curry v1.4.0
- Xcode 7.3
- Build version 7D175

**Comment by sendyhalim** [comment]
@sidraval I just tried with fresh project and it builds fine, weird. Anyway I'm closing this, thanks for the response! 🍻

**Comment by sendyhalim** [comment]
@sidraval I did some investigation, I found the culprit. I had a test struct named `JSON` in my project

```
struct JSON {
   ...
}
```

I guess it confused the compiler :D.
