### ISSUE TITLE
How to decode GeoJSON?

### ISSUE THREAD

**Issue by jkereako** [thoughtbot/Argo#374]
I do love and trust this framework, so I want to use it to decode GeoJSON, but, I have no idea how to decode the key `coordinates`  of a GeoJSON polygon which is of type `[[[Float]]]`.

I understand that Argo 1) may only decode values which have a corresponding key, and 2) may only decode flat arrays. Is this correct?

### Sample JSON

```son
{
  "type": "FeatureCollection",
  "features": [
    {
      "type": "Feature",
      "properties": {
        "CREATED": "1/26/2016"
      },
      "geometry": {
        "type": "Polygon",
        "coordinates": [
          [
            [
              -70.48991310328375,
              41.77278231563589
            ],
            [
              -70.48994334899999,
              41.77978929800018
            ],
            [
              -70.49714660644526,
              41.77749252319358
            ],
            [
              -70.49694061279291,
              41.77778244018566
            ],
            [
              -70.49700927734375,
              41.778106689453445
            ],
            [
              -70.4972915649414,
              41.778480529785334
            ]
          ]
        ]
      }
    }
  ]
}
```

### Argo Version

Argo 3.0.0

### Dependency Manager

Carthage

**Comment by jshier** [comment]
What have you tried? For a type:
```swift
struct GeoJSON {
    let coordinates: [[[Float]]]
}
```
I think the issue is that, while `Array<T>` where `T: Decodable` is defined by Argo, `Array<Array<T>>` where `T: Decodable` is not, and so forth. Due to the (current) limitations of Swift's generics and extensions, you'd have to do something like this abomination:

```swift
extension GeoJSON: Decodable {
    static func decode(json: JSON) -> Decoded<GeoJSON> {
        return self.init <^> [[[Float]]].decode((json <| "coordinates").value!)
    }
}

extension CollectionType where Generator.Element == Array<Array<Float>> {
    static func decode(j: JSON) -> Decoded<[Generator.Element]> {
        switch j {
        case let .Array(a): return sequence(a.map(Generator.Element.decode))
        default: return .typeMismatch("Array", actual: j)
        }
    }
}

extension CollectionType where Generator.Element == Array<Float> {
    static func decode(j: JSON) -> Decoded<[Generator.Element]> {
        switch j {
        case let .Array(a): return sequence(a.map(Generator.Element.decode))
        default: return .typeMismatch("Array", actual: j)
        }
    }
}
```
It compiles, which is about all I can say for it.

You could also try writing a `decode` for a custom type, or an additional one for collections of `Float`s, that unwraps the arrays manually.

I also generally dislike representations with unlabeled fields, as that means you have to rely on ordering, which is also somewhat nasty in Argo. But I imagine there's not a lot you can do about that here.

**Comment by jkereako** [comment]
Thanks @jshier! 

To be honest I haven't tried anything. I had no idea how to approach the problem of parsing. I'll try out what you suggested and see if I can make this thing work.

**Comment by jkereako** [comment]
This does the trick. I was able to parse GeoJSON and use it in my app.

Thanks for helping me out @jshier!

**Comment by gfontenot** [comment]
This is great!

I might do _one_ thing different and try to avoid the force unwrapped optional:

```swift
extension GeoJSON: Decodable {
    static func decode(json: JSON) -> Decoded<GeoJSON> {
        let floats: Decoded<JSON> = json <| "coordinates"
        return self.init <^> floats.flatMap([[[Float]]].decode)
    }
}
```

Also, I just wanted to say that while Argo certainly is _easier_ to use with a fairly generic JSON structure (where you have objects assigned to keys and/or flat arrays as you noted in your original post), we've tried to make sure that it's flexible enough to be able to work with whatever structure you have, although it occasionally requires more plumbing work (as is the case here).
