### ISSUE TITLE
JSON Array Merge Question

### ISSUE THREAD

**Issue by RLovelett** [thoughtbot/Argo#375]
I'm trying to parse two arrays of objects into a single array of objects. The API I'm interacting with is the [Schedules Direct JSON API](https://github.com/SchedulesDirect/JSON-Service/wiki/API-20141201). Sadly I do not control the JSON schema or I'd fix the problem server side.

### Sample JSON

```
{
  "map": [
    { "stationID": "blah1", ... },
    { "stationID": "blah2", ... },
    ...
  ],
  ...
  "stations": [
    { "stationID": "blah1", ... },
    { "stationID": "blah2", ... },
    ...
  ],
  ...
}
```

I'd like to create a model called `Station` or `Channel`. That is an amalgamation of the `map` property record and `stations` property record joined by `"stationID"`.

My intuition is effectively message the raw JSON from the Schedules Direct API into a more manageable format before passing it onto the `decode` function of the `Station`/`Channel` model.

Unfortunately _how_ to go about doing this in an idiomatic way using the `JSON` type is currently eluding me. Perhaps it is eluding me because it is the wrong approach. Perhaps I should be doing it _before_ I send it to Argo's `JSON` type. Any suggestions?

### Argo Version

3.0.1

### Dependency Manager

Cocoapods

**Comment by sidraval** [comment]
I'd suggest decoding into intermediary objects, and then doing the merging (rather than doing the merging with Argo's representations). That might look something like this:

```swift
static func decode(j: JSON) -> Decoded<Channel> {
  let k: Decoded<JSON> = j <| "maps"
  let mapsIntermediary: Decoded<[MapsIntermediary]> = k.flatMap([MapsIntermediary].decode)

  let m: Decoded<JSON> = j <| "stations"
  let stationsIntermediary: Decoded<[StationIntermediary]> = m.flatMap([StationIntermediary].decode)

  ...
}
```

Then you can work with the intermediary objects wrapped in `Decoded` (check out `pure` and `<^>`) to massage them into your final object. Does that make sense?

**Comment by RLovelett** [comment]
Perfect sense. 👌

Thank you @sidraval
