### ISSUE TITLE
Use of unresolved operator "<|"

### ISSUE THREAD

**Issue by Bill-SnowWolf** [thoughtbot/Argo#380]
Trying to get one member from `JSON` object but throwing error

### Error Messages

* Ambiguous reference to member '<|'
* Use of unresolved operator '<|'

### Sample JSON

```
{
  "data": { "0": 0, "1", 1 }
}
```

### Code

```
public static func decode(j: JSON) -> Decoded<T> {
        let data = (j <| "data").value
        ...
}
```

### Argo Version

Argo 3.0.0

### Dependency Manager

Carthage

**Comment by tonyd256** [comment]
You'll need to type that expression. The way Argo and it's operators works is by using Generics which could be any type. Argo can't know what type you want unless you tell it. you can do that by returning the expression like so: `return j <| "data"` or by assigning a type to the variable `let data: Int? = (j <| "data").value`.

However, it looks like you're going to have more trouble with the return type of that function being `Decoded<T>`. You will probably want to pick a concrete type to return like `Decoded<Int>` or a model object like `Decoded<User>`.

**Comment by gfontenot** [comment]
You're also going to need to do more work to decode a dictionary. We don't expose an operator for that. You're basically going to need to do:

```swift
let data: [String: Int]? = (j <| "data" >>- decodeObject).value
```

And then like @tonyd256 said, you'll need to make sure your `decode` function has a proper return type.

**Comment by Bill-SnowWolf** [comment]
@gfontenot If I do it, it will throw error: `No '<|' candidates produce the expected contextual result type 'Decoded<_>'`.

```
let data: [String: Int]? = (j <| "data" >>- parseDictionary).value

private func parseDictionary(reviewScores: AnyObject) -> Decoded<[String: Int]> {
    return .Success(["0": 0])
}
```

**Comment by gfontenot** [comment]
The type of `parseDictionary` isn't correct. We expose a `decodeObject` method, which should drop in like I said. It's defined like so:

```swift
public func decodeObject<T: Decodable where T.DecodedType == T>(_ json: JSON) -> Decoded<[String: T]> {
  return [String: T].decode(json)
}
```

**Comment by gfontenot** [comment]
To be more specific, you aren't dealing with `AnyObject` at that point. By typing `parseDictionary` as `AnyObject -> Decoded<[String: Int]>` you're saying that you want to use `<|` with the type of `(JSON, String) -> Decoded<AnyObject>` which doesn't exist (because we can't conform `AnyObject` to `Decodable`. Our internal `JSON` type, on the other hand, _does_ conform to `Decodable`, and so you can decode values of the type `Decoded<JSON>` just fine using `<|`

**Comment by Bill-SnowWolf** [comment]
Thanks @gfontenot , I figured it out. I can do something like this to get Dictionary from it:
```
private func parseDictionary(json: JSON) -> Decoded<[String: JSON]> {
    switch (json) {
    case .Object(let value):
        return .Success(value)
    default:
        // return error
    }
}
```

**Comment by gfontenot** [comment]
You can do that, sure, but that's just a less generic version of `decodeObject`, so you might want to use that directly.

**Comment by tonyd256** [comment]
@Bill-SnowWolf Looks like you were able to get this working. Closing the issue, but feel free to keep commenting here if you need more help or creating new issues for other questions!
