### ISSUE TITLE
pod install error: Carthage/Checkouts/Curry did not contain...

### ISSUE THREAD

**Issue by tkuichooseyou** [thoughtbot/Argo#385]
EDIT:
It was actually a cocoapods-downloader issue:
https://github.com/CocoaPods/cocoapods-downloader/pull/58

I'm having an issue installing Argo 3.0.1 with Cocoapods. It seems like the git commit revision for the Curry submodule doesn't exist. I pasted the error below

### Error Messages

pod install                                                                                                                                                                                    [ruby-2.3.0]
Analyzing dependencies
Downloading dependencies
Installing Argo (3.0.1)

[!] Error installing Argo
[!] /usr/local/bin/git clone https://github.com/thoughtbot/Argo.git /var/folders/69/0yg4sm394y13cw08b7gqx7zh0000gn/T/d20160701-13948-1f4932b --template= --single-branch --depth 1 --branch v3.0.1 --recursive

Cloning into '/var/folders/69/0yg4sm394y13cw08b7gqx7zh0000gn/T/d20160701-13948-1f4932b'...
Note: checking out 'be127e583674ff8e92653c9bbd0328ab55daebc7'.

You are in 'detached HEAD' state. You can look around, make experimental
changes and commit them, and you can discard any commits you make in this
state without impacting any branches by performing another checkout.

If you want to create a new branch to retain commits you create, you may
do so (now or later) by using -b with the checkout command again. Example:

  git checkout -b <new-branch-name>

Submodule 'Carthage/Checkouts/Curry' (https://github.com/thoughtbot/Curry.git) registered for path 'Carthage/Checkouts/Curry'
Submodule 'Carthage/Checkouts/Runes' (https://github.com/thoughtbot/Runes.git) registered for path 'Carthage/Checkouts/Runes'
Cloning into '/private/var/folders/69/0yg4sm394y13cw08b7gqx7zh0000gn/T/d20160701-13948-1f4932b/Carthage/Checkouts/Curry'...
Cloning into '/private/var/folders/69/0yg4sm394y13cw08b7gqx7zh0000gn/T/d20160701-13948-1f4932b/Carthage/Checkouts/Runes'...
error: no such remote ref 2397c82e2ef800df6327a69640e6dba386b38268
Fetched in submodule path 'Carthage/Checkouts/Curry', but it did not contain 2397c82e2ef800df6327a69640e6dba386b38268. Direct fetching of that commit failed

### Dependency Manager

 Cocoapods 1.0.1

**Comment by zats** [comment]
How did you resolve this issue? I'm hitting the same problem here

**Comment by tkuichooseyou** [comment]
@zats I updated cocoapods-downloader and then it worked. `gem update cocoapods-downloader`
