### ISSUE TITLE
How can I interrupt decode to specify a subclass based on a key/value?

### ISSUE THREAD

**Issue by timcloss** [thoughtbot/Argo#391]
I have JSON like this:

> 

    "activities": [
      {
        "id": "intro-to-the-program",
        "type": "session",
        "audio": "intro-to-the-program.mp3"
      },
      {
        "id": "goal-setting",
        "type": "session",
        "audio": "goal-setting.mp3"
      },
      {
        "id": "onboarding-quiz",
        "type": "quiz"
      }
    ]

> 

Based on the 'type', I actually want to instantiate a subclass of the Activity class (ActivitySession, ActivityQuiz etc) and have the subclass do its own decoding.

How can I do this? The top-level decode() function expects a return type of `Decoded<Activity>`, and none of my approaches so far seem able to defeat it.

**Comment by jakecraige** [comment]
Here's one way I was able to get it working, it's not terribly pretty but it does the job. There are probably more elegant solutions, but I wanted to provide you at least something until others can chime in.

I wrote this in the Argo playground in this repo which is where the `JSONFromFile` thing comes from, which I added and put the JSON you specified above into it.

```swift
struct ThingWithActivities: Decodable {
    let activities: [Activity]

    static func decode(json: JSON) -> Decoded<ThingWithActivities> {
        return curry(ThingWithActivities.init)
            <^> json <|| "activities"
    }
}

class Activity: Decodable {
    let id: String

    init(id: String) {
        self.id = id
    }

    class func decode(json: JSON) -> Decoded<Activity> {
        let decodedType: Decoded<String> = json <| "type"
        return decodedType.flatMap { type in
            switch type {
            case "session": return ActivitySession.decode(json)
            case "quiz": return ActivityQuiz.decode(json)
            default:
                return .Failure(.Custom("Expected valid type, found: \(type)"))
            }
        }
    }
}

class ActivitySession: Activity {
    let audio: String

    init(id: String, audio: String) {
        self.audio = audio
        super.init(id: id)
    }

    override static func decode(json: JSON) -> Decoded<Activity> {
        return curry(ActivitySession.init)
            <^> json <| "id"
            <*> json <| "audio"
    }

}

class ActivityQuiz: Activity {
    override static func decode(json: JSON) -> Decoded<Activity> {
        return curry(ActivityQuiz.init)
            <^> json <| "id"
    }
}

let activities: Decoded<ThingWithActivities>? = JSONFromFile("activities").flatMap(decode)
print(activities) 
// => Optional(Success(ThingWithActivities(activities: [ActivitySession, ActivitySession, ActivityQuiz])))
```

**Comment by timcloss** [comment]
You sir are a genius - it works.
Wow this Swift malarkey certainly takes some getting used to!

**Comment by jakecraige** [comment]
Great to hear!
