### ISSUE TITLE
MKAnnotation and how to conform

### ISSUE THREAD

**Issue by ericlewis** [thoughtbot/Argo#392]
What is the recommended way for conforming to MKAnnotation while also uses Decodable?

**Comment by jakecraige** [comment]
Since `MKAnnotation` is a protocol that doesn't define an initializer, there's not really a way to make it conform sincee the `decode` method needs to be able to initialize it. 

If you have a particular conforming class in mind, it can be done. Here's what confirming `MKPlacemark` might look like:

```swift
extension CLLocationCoordinate2D: Decodable {
    public static func decode(json: JSON) -> Decoded<CLLocationCoordinate2D> {
        return curry(CLLocationCoordinate2D.init)
            <^> json <| "latitude"
            <*> json <| "longitude"
    }
}

extension MKPlacemark: Decodable {
    public static func decode(json: JSON) -> Decoded<MKPlacemark> {
        return curry(MKPlacemark.init)
            <^> json <| "coordinate"
            <*> pure(.None) // Ignore `addressDictionary`, this could be implemented if you wanted though.
    }
}

let json: AnyObject = ["coordinate": ["latitude": 30, "longitude": 50]]
let placemark: Decoded<MKPlacemark> = decode(json)
// => Success(<+30.00000000,+50.00000000> +/- 0.00m)
```

**Comment by gfontenot** [comment]
@ericlewis Do you still need help on this, or were you able to resolve your issue?

**Comment by gfontenot** [comment]
I'm going to go ahead and close this due to inactivity but please feel free to reopen if this is still an issue.
