### ISSUE TITLE
Carthage update doesn't fetch/build Curry or Runes

### ISSUE THREAD

**Issue by AndrewSB** [thoughtbot/Argo#397]
New Cartfile, empty directory with the contents:
```
github "thoughtbot/Argo"
```

`carthage update --no-use-binaries --use-ssh --platform ios` prints out:
```
*** Checking out Argo at "v3.0.2"
*** xcodebuild output can be found in /var/folders/dx/dywzvjnj6nl_x1nfzrb618f40000gn/T/carthage-xcodebuild.tUqHNV.log
*** Building scheme "Argo-iOS" in Argo.xcworkspace
```

Not sure why Curry or Runes aren't being fetched (they seem to be in the `Cartfile.resolved` for release `v3.0.2`)...

My temporary workaround has been to add `Runes` & `Curry` into my `Cartfile`

**Comment by gfontenot** [comment]
Neither of those libraries are hard dependencies. The Runes dependency is (currently) hidden from the user by importing the operator definitions directly, and Curry isn't a dependency at all (although it's recommended). If you want these libraries in your code, it's expected that you would add them as dependencies yourself.
