### ISSUE TITLE
Has JSONValue been renamed JSON ?

### ISSUE THREAD

**Issue by Nono67** [thoughtbot/Argo#40]
Hi, 

I'm implementing for the first time a struct using Argo and I have a strange problem.

```swift
struct Shop {
    let name: String
	let displayName: String
	let order: Int
}

extension Shop: JSONDecodable {
	static func create(name: String)(displayName: String)(order: Int) -> Shop {
		return Shop(name: name, displayName: displayName, order: order)
	}
	
	static func decode(j: JSONValue) -> Shop? {
		return Shop.create
			<*> j <| "name"
			<*> j <| "displayName"
			<^> j <| "order"
	}
}
```
Tell me if I missed something, but I think everything is ok. The problem is that I have an error saying that 'JSONValue' has been renamed to JSON and because of that the extension is not conform to the protocol 'JSONDecodable'. If I look in the protocol, a JSONValue is required so I don't really understand ...

**Comment by kaishin** [comment]
This seems like an error from SwiftyJSON https://github.com/SwiftyJSON/SwiftyJSON/blob/02878562cc779fda8e86be3211050f03228a01d6/Source/SwiftyJSON.swift#L1176

We did not rename anything on Argo. Make sure that you remove SwiftyJSON from your project.
