### ISSUE TITLE
Ignore fields?

### ISSUE THREAD

**Issue by MikeHuntington** [thoughtbot/Argo#402]
I was just curious if there was a way to ignore fields in our models? I would like to add some properties to my model that I don't want to be decoded or mapped to json values.

Is this possible?

**Comment by tonyd256** [comment]
@MikeHuntington This is definitely possible! Those other values will probably need to have defaults though. You can provide those defaults in the decoding steps like `<*> .Success(default_value)` or write a custom initializer that ignores those values. If you have an example we can help you work through it.

**Comment by MikeHuntington** [comment]
Hi! I went with the custom initializer method and that worked great! Thank you for the help!
