### ISSUE TITLE
Runes warning as missing from working copy and errors Xcode 8 beta 4

### ISSUE THREAD

**Issue by MHGigster** [thoughtbot/Argo#403]
I am experiencing a weird problem that I know it is due to Runes not being installed correctly as a submodule with Argo pod but not sure what I should do with it.

Installed as:
pod 'Argo', :git => 'https://github.com/thoughtbot/Argo.git', :commit => 'b8ce449', :submodules => true
(This is the latest commit as this is the only way I seem to get the changes for Xcode 8 beta 4)
Warning I get is:

warning: Missing file: /Users/Home/Development/.../.../Pods/Argo/Carthage/Checkouts/Runes/Source/Runes.swift is missing from working copy

Then a bunch of errors in Runes Array.swift and Optional.swift for syntax error. If I go check master in Runes, it has the correct files, mine does not.

Any idea what I should do to fix that?

**Comment by gfontenot** [comment]
You probably shouldn't be pointing at that specific commit. In the next release of Argo, we have exposed Runes as an explicit dependency, and have updated the podfile to match that expectation. We no longer rely on submodules for that. You should probably look at pointing at `master` if you want the most recent code.
