### ISSUE TITLE
Less strict mapping for Int and String

### ISSUE THREAD

**Issue by olejnjak** [thoughtbot/Argo#405]
_Hi, 

I'm often experiencing issue that APIs I work with are not really consistent and often don't keep same data types on all endpoints, e.g. on some endpoints identifiers are sent as `String` on others as `Number`. So for my cases I have my own fork in which I've edited the `decode` function of `String` and `Int`. 

And I was wondering if this approach could be considered to be useful to merge in any of your releases or it is just meant to be as strict as it is now?_

### Sample JSON

One endpoint:
```
{
  "id": "1"
}
```
Another endpoint:
```
{
  "id": 1
}
```

### Models

_All models involved, including their `Decodable` implementations._

```
struct User {
  let identifier:Int
}

extension User: Decodable {
  static func decode(json: JSON) -> Decoded<User> {
    return curry(self.init) 
      <^> json <| "id" 
  }
}
```

### Argo Version

_Argo 3.1.0_

### Dependency Manager

_Cocoapods_

**Comment by tonyd256** [comment]
Hi @olejnjak, so we actually have built in functionality to help with this. You can specify an alternative decode that parses it from a string. Here is an example:
```swift
struct User {
  let identifier:Int
}

extension User: Decodable {
  static func decode(json: JSON) -> Decoded<User> {
    return curry(self.init) 
      <^> json <| "id" <|> (json <| "id" >>- stringToInt) 
  }
}

func stringToInt(string: String) -> Decoded<Int> {
  switch Int(string) {
  case .Some(let x): return .Success(x)
  case .None: return .Failure(.CustomError("Some cool error"))
  }
}
```
Something like this should do the trick. I think the parens on that decode line should be correct but if you get errors try adding more :)

**Comment by olejnjak** [comment]
I do know the _either_ and _flatMap_ operators but was thinking that this feature might be useful in general but I totally understand if the purpose is to keep the decoding of standard types as simple as possible.

**Comment by tonyd256** [comment]
Yes we're trying to keep them as simple as possible because some users might not want that case to work and it's much easier for a user to implement the above than for them to try and implement what exists now if we allowed strings to cast to ints by default.
