### ISSUE TITLE
Xcode 8 beta 6 - not able to build project after adding Argo

### ISSUE THREAD

**Issue by raghvendra** [thoughtbot/Argo#408]
I am not able to build my project after I add Argo

### Error Messages

Carthage/Build/iOS/Argo.framework/Argo compiled with older version of Swift language (2.0) than previous files (3.0) for architecture x86_64

### Argo Version
Argo 3.1.0

### Dependency Manager
 Carthage

**Comment by gfontenot** [comment]
3.X releases are intended for Swift 2.2 and 2.3. We're in the process of updating Argo for Swift 3.0, and you can find the most recent code on master. The beta 6 changes, specifically, are currently [living in an open PR](https://github.com/thoughtbot/Argo/pull/407) and should be merged relatively soon.
