### ISSUE TITLE
Nested dictionary with dynamic keys

### ISSUE THREAD

**Issue by berkcebi** [thoughtbot/Argo#409]
Hey hey, just starting off with Argo. Loving it so far!

I've got a chaotic property in my JSON, where the keys represent identifiers, so they are dynamic. It sadly can't be represented as a `[String: String]` though, as some values are nested. Here's an example:

``` json
{
  "1": "one",
  "2": "two",
  "3": {
    "4": "four",
    "5": "five"
  }
}
```

I've tried to tackle this with an enum, as values can either be a `String`s or another `[String: Foo]` but I'm stuck on its `Decodable` extension:

``` swift
public enum Foo {
    case Value(String)
    case Instance([String: Foo])
}

// MARK: Decodable

extension Foo: Decodable {

    public static func decode(json: JSON) -> Decoded<Foo> {
        switch json {
        case let .String(string):
            return pure(.Value(string))
        case .Object:
            return // Not sure what to return here.
        default:
            return .typeMismatch("Foo", actual: json)
        }
    }
}
```

Not sure if I'm overthinking things here but even a solution where I can keep this property as is (a `[String: AnyObject]` dictionary) would be quite helpful.

Cheers!

**Comment by gfontenot** [comment]
We don't currently have a great way to go from `JSON` back to `[String: AnyObject]`, unfortunately. You _could_ parse directly back to `[String: JSON]` if that works for you?

Dynamic keys are also going to be difficult to work with here, and I'm not sure I have a great answer for you. I'll think on this a bit and get back to you, but please feel free to update this issue if you find a solution in the meantime, as I'd love to see it!

**Comment by gfontenot** [comment]
I'm going to go ahead and close this due to inactivity but please feel free to reopen if this is still an issue.
