### ISSUE TITLE
Extending Subclass of NSManagedObject

### ISSUE THREAD

**Issue by mikkelharris** [thoughtbot/Argo#41]
Hi,

I would switch to I’m trying to implement argo on an NSManagedObject subclass however when I implement JSONDecodable Xcode is unable to finish building.

Is this an issue with how I am trying to use Argo or something else?

Thanks

**Comment by tonyd256** [comment]
Hi @mikkelharris, I haven't seen this issue before. It might have something to do with subclasses of NSManagedObject. Would you be able to post the code that you're trying to get working in here? It could also be a problem with your setup as well. Either way, this should be something that can work so let's figure it out.

**Comment by mikkelharris** [comment]
Thanks for the help @tonyd256 

I think it has something to do with how Argo is interacting with my NSManagedObject subclass.  I was able to copy your example from the README and it built fine.  Here’s what I’m working with:

```swift
import Foundation
import CoreData
import Argo
import Runes

class Program: NSManagedObject {

    @NSManaged var hollandCodes: String
    @NSManaged var programGroupID: NSNumber
    @NSManaged var summary: String
    @NSManaged var url: String
    @NSManaged var programGroup: ProgramGroup

    convenience init(hollandCodes:String, programGroupID:NSNumber,summary: String,url: String, entity: NSEntityDescription, insertIntoManagedObjectContext context: NSManagedObjectContext!) {
        self.init(entity: entity, insertIntoManagedObjectContext: context)
        self.hollandCodes = hollandCodes
        self.programGroupID = programGroupID
        self.summary = summary
        self.url = url
    }
}

extension Program: JSONDecodable {
    class func create(hollandCodes:String)(programGroupID:NSNumber)(summary:String)(url:String) -> Program{
        return Program(hollandCodes:hollandCodes, programGroupID:programGroupID, summary:summary, url:url)
    }
    
    class func decode(j:JSONValue) -> Program? {
        return Program.create
        <^> j <| "HollandCodes"
        <*> j <| "ProGroupID"
        <*> j <| "Description"
        <*> j <| "URL"
    }
}
```

**Comment by tonyd256** [comment]
We've seen issues with class types that aren't final. The workaround is to set the `DecodedType` of the `JSONDecodable` protocol. Check out the tests in the Model folder `NSURL.swift`. Try setting this in the extension on `Program`:
`typealias DecodedType = Program`

**Comment by tonyd256** [comment]
You'll also need to make sure `NSNumber` conforms to `JSONDecodable`. I haven't done this since I've only considered `Int`. You can take a look at how Argo does this in Argo/Globals/JSON.swift. And finally, it looks like you're missing the `ProgramGroup` variable in your `create` function and in the init inside. Then you'll need to make `ProgramGroup` `JSONDecodable` and add it to the bottom of the `decode` function.

**Comment by mikkelharris** [comment]
My issue was in the fact that I was using an NSNumber as one of the argument types in my create function. Instead of throwing an error, Xcode would just hang. 

After trying to replicate my situation from scratch, I started receiving an error, "Type 'NSNumber' does not conform to protocol 'JSONDecodable'" for my new test objects. 

However when I went back to my original object it would just hang Xcode. Not sure why this is the case but at least I've discovered why it was not working for me

**Comment by tonyd256** [comment]
Argo is pushing the limits of the compiler. If types don't match up properly it usually just hangs as you've been seeing. If you experience it again I would just make sure that all your types that you try to parse from the JSON conform to JSONDecodable, that you've included all the parameters in your create function and in your decode function, and that you've made sure to use the correct Argo operator for arrays and optionals.

Closing this now.
