### ISSUE TITLE
Cannot convert value of type ... to expected argument type '(_) -> (_) -> ... 

### ISSUE THREAD

**Issue by nawar** [thoughtbot/Argo#415]
I took over a code base from a team of developers and I noticed they were using your library for Swift version 2.2. When I upgraded the code base to Swift 3 and cloned your master I'm getting this error message. I'd appreciate if I can get some insight since it's not using `Curry(JobFeedResponse.init)`. This is the error message the compiler is complaining about:
### Error Messages

```
Cannot convert value of type '(Int, String, [JobFeedItem]?) -> JobFeedResponse' to expected argument type '(_) -> (_) -> (_) -> JobFeedResponse'
```

Any help would be appreciated. 
### Models

``` Swift
struct JobFeedResponse
{
    let jobs: [JobFeedItem]?
    let offset: Int
    let posterPath: String
}

extension JobFeedResponse: Decodable
{
    static func create(_ offest: Int, _ posterPath :String, _ jobs: [JobFeedItem]?) -> JobFeedResponse { 
        return JobFeedResponse(jobs: jobs,offset: offest, posterPath: posterPath)
    }

    static func decode(_ json: JSON) -> Decoded<JobFeedResponse> { 
        return JobFeedResponse.create
            <^> json <| ["response", "offset"]
            <*> json <| ["response", "posterPath"]
            <*> json <||? ["response", "jobs"]
    }
}
```
### Argo Version

Argo (master) - Swift 3 
### Dependency Manager

 Carthage

**Comment by tonyd256** [comment]
Hi @nawar 

I think the issue here is that the decoding steps aren't in the same order as the params. Try rearranging your decode function like so:

```swift
<^> json <||? ["response", "jobs"]
<*> json <| ["response", "offset"]
<*> json <| ["response", "posterPath"]
```

Alternatively, you could change the oder of your object's properties to match the decode function order.

**Comment by nawar** [comment]
Thanks @tonyd256 for the speedy response. I went ahead and changed the order in both scenarios but with no luck. I have other classes having the same issue as well. Any ideas?

**Comment by tonyd256** [comment]
This error usually means the types are not lining up somewhere. The only thing I can think of is to make sure all the types are absolutely correct and in the correct positions.

**Comment by tonyd256** [comment]
Sorry didn't mean to close this.

**Comment by nawar** [comment]
I changed the order as you requested and still getting this error
```Swift
struct JobFeedResponse
{
    let offset: Int
    let posterPath: String
    let jobs: [JobFeedItem]?
}

extension JobFeedResponse: Decodable
{
    static func create(_ offest: Int, _ posterPath :String, _ jobs: [JobFeedItem]?) -> JobFeedResponse { 
        return JobFeedResponse(offset: offest, posterPath: posterPath,jobs: jobs)
    }

    static func decode(_ json: JSON) -> Decoded<JobFeedResponse> { 
        return JobFeedResponse.create
            <^> json <| ["response", "offset"]
            <*> json <| ["response", "posterPath"]
            <*> json <||? ["response", "jobs"] 
    }
}
```
and I'm still getting the same error. I'll do some digging and get to the bottom of this.

**Comment by gfontenot** [comment]
Does `JobFeedItem` implement `Decodable`?

**Comment by nawar** [comment]
Yes, it implements it
```Swift
extension JobFeedItem : Decodable { 
...
}
```

**Comment by gfontenot** [comment]
Good question! Are you importing `Runes` now? We've exposed that as an external dependency now so you need to manually link/import that accordingly. It doesn't look like you're using Curry from your snippets so I don't think that's the issue.

**Comment by nawar** [comment]
Thanks for tips. I followed them and made sure to "import Runes" and followed Carthage's doc on placing Runes.framework (and Argo.framework) in the project's target "Linked Frameworks and Libraries". I'm still seeing the compiler complaining about the same error.
I'll include my Cartfile.resolved as well in case it would be of use. 
```
github "Alamofire/Alamofire" "4.0.1"
github "thoughtbot/Curry" "863ec7b235448ca53e682cf6958df4c30880c78e"
github "Haneke/HanekeSwift" "6e48f795c5928101043a5e11e1377877e042012d"
github "jessesquires/JSQSystemSoundPlayer" "4.4.0"
github "thoughtbot/Runes" "v4.0.0"
github "socketio/socket.io-client-swift" "v8.0.2"
github "thoughtbot/Argo" "14cc4f84842fad52aae12de8479048e433967392"
```

**Comment by gfontenot** [comment]
I'm not totally sure, but something to try would be to not point to specific SHAs/tags and instead use semantic versioning for dependencies. For Curry/Runes/Argo that would look something like:

```
github "thoughtbot/Curry" ~> 3.0
github "thoughtbot/Runes" ~> 4.0
github "thoughtbot/Argo" ~> 4.0
```

**Comment by gfontenot** [comment]
Oh, I see the issue now. Your `create` function isn't curried. Sorry for missing that. Try removing that method and using `Curry.framework` instead:

```diff
+import Curry
+
 struct JobFeedResponse
 {
     let offset: Int
     let posterPath: String
     let jobs: [JobFeedItem]?
 }

 extension JobFeedResponse: Decodable
 {
-    static func create(_ offest: Int, _ posterPath :String, _ jobs: [JobFeedItem]?) -> JobFeedResponse { 
-        return JobFeedResponse(offset: offest, posterPath: posterPath,jobs: jobs)
-    }
-
     static func decode(_ json: JSON) -> Decoded<JobFeedResponse> { 
-        return JobFeedResponse.create
+        return curry(JobFeedResponse.init)
             <^> json <| ["response", "offset"]
             <*> json <| ["response", "posterPath"]
             <*> json <||? ["response", "jobs"] 
     }
 }
```

**Comment by nawar** [comment]
I'll try your tip about including the specific versions. As for not curing my `create`, I know by curing it it'll solve the issue instantly; however, I have a code base like the below where the existence of `create` is useful to do some post-processing on the received values:

```swift 
import CoreLocation
import Argo
import Curry
import Runes

struct Venue {
    let id :Int
    let coordinate: CLLocationCoordinate2D
    let name :String
    let address :String
    let distance :Double
    let timezone :String
    
    let opentimes :[Opentime]?
    
    func getFormattedDistance() -> String {
        let roundedDistance = Double(round(100*distance)/100)
        return "\(roundedDistance) Mi."
    }
}

extension Venue : Decodable {
    
    static func create(_ id: String, _ lat: String, _ lng: String, _ name :String, _ distance :String?, _ address :String, _ timezone :String, _ opentimes: [Opentime]?) -> Venue {
        let latFloat = (lat as NSString).doubleValue
        let lngFloat = (lng as NSString).doubleValue
        let coordinate = CLLocationCoordinate2DMake(latFloat, lngFloat)
        var distanceFloat = 0.0
        if distance != nil {
            distanceFloat = (distance! as NSString).doubleValue
        }

        return Venue(id: Int(id)!, coordinate: coordinate, name: name, address: address, distance: distanceFloat, timezone: timezone, opentimes: opentimes)
    }
    
    static func decode(_ j: JSON) -> Decoded<Venue> {
        return Venue.create
            <^> j <| "id"
            <*> j <| "lat"
            <*> j <| "lng"
            <*> j <| "name"
            <*> j <|? "distance"
            <*> j <| "address"
            <*> j <| "timezone"
            <*> j <||? "opentimes"
    }
}
```

**Comment by gfontenot** [comment]
In that case, you can curry the `create` function (`return curry(Venue.create)`). But at the end of the day, you _need_ to be using a curried function for this.

**Comment by nawar** [comment]
Okay. As you suggested, I forced the currying and it resolved these errors for now. I'll close this question, but before that, I want to thank you for the provided support.

**Comment by gfontenot** [comment]
Great! Glad it worked out for you.

For reference: You could also avoid the `Curry` dependency if you really wanted to by writing your `create` function to be explicitly curried, but it would be ugly:

```swift
  static func create(_ id: String) -> (String) -> (String) -> (String) -> (String?) -> (String) -> (String) -> ([Opentime]?) -> Venue {
    return { id in
      { lat in
        { lng in
          { name in
            { distance in
              { address in
                { timezone in
                  { opentimes in
                    let latFloat = (lat as NSString).doubleValue
                    let lngFloat = (lng as NSString).doubleValue
                    let coordinate = CLLocationCoordinate2DMake(latFloat, lngFloat)
                    var distanceFloat = 0.0
                    if distance != nil {
                      distanceFloat = (distance! as NSString).doubleValue
                    }

                    return Venue(id: Int(id)!, coordinate: coordinate, name: name, address: address, distance: distanceFloat, timezone: timezone, opentimes: opentimes)
                  }
                }
              }
            }
          }
        }
      }
    }
  }
```

This is why we wrote `Curry.framework` in the first place.

Some more thoughts/tips:

It seems like your JSON response isn't really sending the data you want. Is this an API you control? Some things that could be improved on the API side:
 - Right now you're decoding `id` to a string and then forcing it to an Int. Is there a reason that the API can't send this as an Int from the start? Alternatively, if your API is sending IDs as strings maybe it's best to store them as strings?
 - We could clean up the `CLLocation` stuff really easily if the API were to send the lat/long in a nested key (`"location": {"lat": 1234, "lng": 1234}}`) instead of inline. If that were the case, then we could make `CLLocation` conform to `Decodable` and we'd be able to extract the logic around decoding that type appropriately. And as with the ID, I'd wonder why the API was sending these back as strings instead of ints.

In any case, I might still move towards removing the need for your `create` function entirely by adding some info to your parser (Note that most of the complexity in this parser comes from the mistyped API):

```swift
struct Venue {
  let id :Int
  let coordinate: CLLocationCoordinate2D
  let name :String
  let address :String
  let distance :Double
  let timezone :String

  let opentimes :[Opentime]?

  func getFormattedDistance() -> String {
    let roundedDistance = Double(round(100*distance)/100)
    return "\(roundedDistance) Mi."
  }
}

extension Venue: Decodable {
  static func decode(_ j: JSON) -> Decoded<Venue> {
    return curry(Venue.init)
    <^> j <| "id" >>- intFromString
    <*> decodeLocation(j)
    <*> j <| "name"
    <*> j <| "address"
    <*> (j <| "distance" >>- doubleFromString) <|> pure(0.0)
    <*> j <| "timezone"
    <*> j <||? "opentimes"
  }

  private static func doubleFromString(_ string: String) -> Decoded<Double> {
    let double = (string as NSString).doubleValue
    return pure(double)
  }

  private static func intFromString(_ string: String) -> Decoded<Int> {
    return .fromOptional(Int(string))
  }

  private static func decodeLocation(_ json: JSON) -> Decoded<CLLocationCoordinate2D> {
    return curry(CLLocationCoordinate2DMake)
      <^> json <| "lat" >>- doubleFromString
      <*> json <| "lng" >>- doubleFromString
  }
}
```

Happy to answer any questions you have about this.

**Comment by gfontenot** [comment]
Just for further clarity, if you were able to modify the API as I suggested, we could end up with this:

```swift
extension Venue: Decodable {
  static func decode(_ j: JSON) -> Decoded<Venue> {
    return curry(Venue.init)
    <^> j <| "id"
    <*> j<| "location"
    <*> j <| "name"
    <*> j <| "address"
    <*> (j <| "distance") <|> pure(0.0)
    <*> j <| "timezone"
    <*> j <||? "opentimes"
  }
}

extension CLLocationCoordinate2D: Decodable {
  private static func decode(_ json: JSON) -> Decoded<CLLocationCoordinate2D> {
    return curry(CLLocationCoordinate2DMake)
      <^> json <| "lat"
      <*> json <| "lng"
  }
}
```
Which I find very nice indeed.

**Comment by nawar** [comment]
Thanks for the tips buddy, I really appreciate them and I'll come back and use them when refactoring the code base which I inherited from the offshore team. Changing the API to reflect the right types should also be straightforward since I have access to the backend code. This is just part of the tech debt that needs to be paid anyway :anger: 
Thanks again for your support guys.
