### ISSUE TITLE
Argo fails to build for non-iOS targets

### ISSUE THREAD

**Issue by sgoodwin** [thoughtbot/Argo#417]
We are using Argo on my client's project right now. Currently we only use the iOS target, but this is the error we get when we don't add the ```--platform iOS``` flag to prevent it from trying to build other targets:

```
*** Building scheme "Argo-Mac" in Argo.xcworkspace
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
/Users/sgoodwin/Desktop/Schiphol/Carthage/Checkouts/Argo/Argo/Types/Decoded/Applicative.swift:1:8: error: no such module 'Runes'
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/sgoodwin/Desktop/Schiphol/Carthage/Checkouts/Argo/Argo.xcworkspace -scheme Argo-Mac -configuration Release ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** BUILD FAILED **


The following build commands failed:
	CompileSwift normal x86_64
	CompileSwiftSources normal x86_64 com.apple.xcode.tools.swift.compiler
(2 failures)
```

### Argo Version

_example: Argo 3.0.0_ (master)

### Dependency Manager

Carthage

**Comment by tonyd256** [comment]
We are able to build the all the targets on our end. Which version of Argo & Carthage are you using?

**Comment by sgoodwin** [comment]
Carthage: 0.17.2

Argo: github "thoughtbot/Argo" "4b57653f7760bd3eedfd1c1fbc821bde191e603d" (the one Swish's swift-3 branch is using)

It occurs to me now that it could just be that Swish isn't using the latest commits from here. Now I feel silly.

**Comment by tonyd256** [comment]
No worries! I hope to get a Swish release out soon with official Swift 3 support. Maybe that will help fix things. I'll close this for now but feel free to open a new one or comment here if the updated version is still giving you issues!
