### ISSUE TITLE
'carthage update' clean/build failure during building scheme 'Argo-Mac'

### ISSUE THREAD

**Issue by garfbargle** [thoughtbot/Argo#419]
I'm attempting to upgrade my project to Xcode 8 / Swift 3.0 and all my other carthage packages are able to build correctly. However I am getting a failure while building the scheme 'Argo-Mac'. 

### Error Messages

```sh
cobo$ carthage update
*** Checking out Alamofire at "4.0.1"
*** Checking out Curry at "v3.0.0"
*** Checking out Eureka at "2.0.0-beta.1"
*** Checking out Runes at "v4.0.0"
*** Checking out Argo at "v4.0.0"
*** Building scheme "Alamofire watchOS" in Alamofire.xcworkspace
*** Building scheme "Alamofire iOS" in Alamofire.xcworkspace
*** Building scheme "Alamofire tvOS" in Alamofire.xcworkspace
*** Building scheme "Alamofire macOS" in Alamofire.xcworkspace
*** Building scheme "Curry-tvOS" in Curry.xcodeproj
*** Building scheme "Curry-Mac" in Curry.xcodeproj
*** Building scheme "Curry-watchOS" in Curry.xcodeproj
*** Building scheme "Curry-iOS" in Curry.xcodeproj
*** Building scheme "Eureka" in Eureka.xcworkspace
*** Building scheme "Runes-iOS" in Runes.xcodeproj
*** Building scheme "Runes-Mac" in Runes.xcodeproj
*** Building scheme "Runes-watchOS" in Runes.xcodeproj
*** Building scheme "Runes-tvOS" in Runes.xcodeproj
*** Building scheme "Argo-Mac" in Argo.xcworkspace
** CLEAN FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
A shell task (/usr/bin/xcrun xcodebuild -workspace /Users/cobo/Developer/an_ios_project/Carthage/Checkouts/Argo/Argo.xcworkspace -scheme Argo-Mac -configuration Release ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES clean build) failed with exit code 65:
** CLEAN FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
** BUILD FAILED **


The following build commands failed:
	Check dependencies
(1 failure)
```

### Argo Version

Argo 4.0.0

### Dependency Manager

Carthage

[carthage-xcodebuild.1ESkeu.txt](https://github.com/thoughtbot/Argo/files/528845/carthage-xcodebuild.1ESkeu.txt)

**Comment by sharplet** [comment]
What versions of Xcode and Carthage are you using?

**Comment by garfbargle** [comment]
Hey Sharplet, sorry about not including that.

Carthage is 0.18.1
Xcode is Version 8.0 (8A218a)

**Comment by sharplet** [comment]
I wasn't able to reproduce this error in any combination of Carthage 0.18.0/0.18.1 and Xcode 8.0/8.1-beta. The command I ran was `carthage build --platform macOS --no-skip-current` after checking out the Argo repo at `v4.0.0`.

Could you try removing your `Carthage/Checkouts/Argo` folder and building again? It may also be worthwhile deleting `~/Library/Caches/org.carthage.CarthageKit/dependencies/Argo`.

**Comment by garfbargle** [comment]
I removed the two directories and changed my command to ```carthage build --platform iOS``` which I should have been doing anyways and now it works! :) Thank you.
