### ISSUE TITLE
Add JSONEncodable as well?

### ISSUE THREAD

**Issue by nvh** [thoughtbot/Argo#42]
I don't know if it's seen as in the scope of this project, but wouldn't it be nice to have a JSONEncodable protocol as well? Something like this:
```swift
public protocol JSONEncodable {
  func encode() -> JSONValue
}
```

With some smart use of the LiteralConvertible protocols the implementation could look something like this:
```swift
extension User: JSONEncodable {
  func encode() -> JSONValue {
    return ["id":id,"name":name,"email":email]
  }
}
```
I've made an example of this in my fork of Argo: https://github.com/nvh/Argo/blob/master/Argo/Globals/JSONValue.swift#L95

Will this be something worth making a pull request from?

**Comment by tonyd256** [comment]
@nvh what have you been using this for? I have been thinking about adding this but not to a `JSONValue`. Are you finding benefit in having the JSONValue type? I was thinking about adding it as such: `func encode() -> AnyObject`. This way you can return the dictionary or whatever directly.

it would still look like this:
```
extension User: JSONEncodable {
  func encode() -> AnyObject {
    return ["id":id,"name":name,"email":email]
  }
}
```

**Comment by nvh** [comment]
@tonyd256 Well, if you return AnyObject, you loose all type information. So when transforming to a json string, you have to figure out all the types again.

When returning JSONValue, you could do something like:

```swift
extension JSON {
  public func toString() -> String {
    switch(self) {
    case let .string(string):
      return "\"\(string)\""
    case let .number(number):
      return "\(number)"
    case let .object(object):
      let result = join(",",map(object,{ (key,value) in "\"\(key)\":\(value.description)"}))
      return "{\(result)}"
    case let .array(array):
      let result = join(",",map(array,{$0.description}))
      return "[\(result)]"
    case let .boolean(boolean):
      return boolean ? "true" : "false"
    case .null:
      return "null"
    }
  }
}
``` 

And have it return a valid json string. 
I know the above example doesn't map 100% to the current JSONValue type in Argo (this example is taken from one of my own projects). But it's a really nice way of recursively constructing JSON

**Comment by tonyd256** [comment]
I don't understand why you need to convert it to a string? I've just been using `NSJSONSerialization.dataWithJSONObject:error:` to convert my `AnyObject` to the appropriate `NSData` then attach it to the `NSRequest`. You don't need to maintain type info or worry about converting it to a string manually.

**Comment by nvh** [comment]
You're right. You can use that to convert AnyObject to json, but it can fail. Of course you can look at the error or use `NSJSONSerialization.isValidJSONObject(AnyObject) -> Bool` to check if AnyObject is actually a valid json object, but wouldn't it be nice to be able to detect an error in your json encoding at compile time instead of at runtime?
I think it's nice to have a more strict API so that it's less easy to shoot yourself in the foot. Especially if the library can lay the groundwork to make it easy to use the API, but I can understand if your disagree, because it also increases the complexity of the library.

You could of course easily create a reverse of `JSONValue.parse(json: AnyObject) -> JSONValue`, to be able to use a `JSONValue` with the Apple provided serialisation API's. That feels as the right place for that functionality to me, so you can keep the symmetry in the encode and decode protocols.

**Comment by tonyd256** [comment]
Hmm I can see that. Ok feel free to PR or we can take a look into it as well.

**Comment by nvh** [comment]
Ok, great. You'll hear from me :)

**Comment by gfontenot** [comment]
Closing this along with #47. tl;dr: This feels out of scope for Argo.
