### ISSUE TITLE
Decoding direct arrays

### ISSUE THREAD

**Issue by FranciscoAmado** [thoughtbot/Argo#421]
Hi, 

This ain't much an error issue but more of a question.

If you have a valid JSON that is a direct collection of objects, how do you try to decode it if you have no key for the collection?

### Sample JSON

```
[
 {
   "key": "value"
 },
 {
   "key": "value"
 },
...
]
```

### Models

Foo -> the struct with the collection of objects
Bar -> the objects

```
struct Foo {
  let values: [Bar]
}

extension Foo: Decodable {
    static func decode(j: JSON) -> Decoded<Foo> {
        // HOW do you decode Foo?
    }
}

struct Bar {
  let value: String
}

extension Bar: Decodable {
    static func decode(j: JSON) -> Decoded<Bar> {
        return curry(Bar.init)
            <^> j <| "key"
    }
}
```

### Argo Version

 Argo 3.1

### Dependency Manager

 Carthage

Thanks for the help 
and building Argo!

Francisco

**Comment by tonyd256** [comment]
I would probably not make a new model simply to house the array. Instead, call `let arr: [Bar] = Array<Bar>.decode(j)` where ever you need to decode the json.

**Comment by FranciscoAmado** [comment]
I could but I want to encapsulate it in a model too operate on it there.

I could also do
```
    static func decode(j: JSON) -> Decoded<Foo> {
        
        return curry(Foo.init)
            <^> Array<Bar>.decode(j)
    }
```

Right?

**Comment by gfontenot** [comment]
fwiw, `decodeArray` is a nicer (IMO) synonym for `Array<Bar>.decode` or `[Bar].decode`.
