### ISSUE TITLE
Compiler error converting from Decoded<[String : A]> to Decoded<[String : _]>

### ISSUE THREAD

**Issue by edwardaux** [thoughtbot/Argo#423]
I'm porting my app to Swift 3 and am updating some Swift 2 code I originally wrote to cater for extracting dictionaries from JSON. I'm getting an odd compiler error that I'm struggling to resolve when I'm trying to make the call to `Decoded.optional(decoded)`.

I was wondering if you guys had seen something like this before. My Swift 3 code looks like:

	import Foundation
	import Argo
	import Runes

	infix operator <|~ : ArgoDecodePrecedence
	infix operator <|~? : ArgoDecodePrecedence

	// Pull dictionary from JSON
	public func <|~ <A: Decodable>(json: JSON, key: String) -> Decoded<[String:A]> where A == A.DecodedType {
		return json <|~ [key]
	}

	// Pull optional dictionary from JSON
	public func <|~? <A: Decodable>(json: JSON, key: String) -> Decoded<[String:A]?> where A == A.DecodedType {
		let decoded: Decoded<[String:A]> = json <|~ [key]
		return Decoded.optional(decoded)  // <<<<<<< ****** ERROR ******
	}

	// Pull dictionary from JSON using key path
	public func <|~ <A: Decodable>(json: JSON, keys: [String]) -> Decoded<[String:A]> where A == A.DecodedType {
		return flatReduce(keys, initial: json, combine: decodedJSON) >>- Dictionary<String,A>.decode
	}

	// Pull optional dictionary from JSON using key path
	public func <|~? <A: Decodable>(json: JSON, keys: [String]) -> Decoded<[String:A]?> where A == A.DecodedType {
		let decoded: Decoded<[String:A]> = json <|~ keys
		return Decoded.optional(decoded)  // <<<<<<< ****** ERROR ******
	}

	extension Decoded {
		static func optional<T>(_ decoded: Decoded<T>) -> Decoded<T?> {
			switch decoded {
			case let .success(value): return .success(.some(value))
			case     .failure(.missingKey): return .success(.none)
			case let .failure(.typeMismatch(exp, act)): return .failure(.typeMismatch(expected: exp, actual: act))
			case let .failure(.custom(x)): return .failure(.custom(x))
			case let .failure(.multiple(x)): return .failure(.multiple(x))
			}
		}
	}

### Error Messages

`cannot convert value of type 'Decoded<[String : A]>' (aka 'Decoded<Dictionary<String, A>>') to expected argument type 'Decoded<[String : _]>' (aka 'Decoded<Dictionary<String, _>>')`

### Argo Version

Argo 4.0.0

**Comment by edwardaux** [comment]
Interestingly, if I literally copy the exact switch statement from the `optional` function into the operator body, everything works perfectly.

**Comment by gfontenot** [comment]
Well _that's_ disconcerting. Can you clarify where you're hitting the error?

One thing I wonder is if your implementation of `.optional` is shadowing the implementation we ship in Argo?

**Comment by edwardaux** [comment]
Apologies... I've just updated the original snippet to indicate which lines emit the error.

Does the Swift 3 Argo code contain a static `Decoded.optional` function? The Swift 2 code definitely did (which I used to call), but the reason I've implemented the above function is because I couldn't find the equivalent Swift 3 function.

I suspect it is a compiler bug... I'm up and running by duplicating the code in my two operator functions so it isn't holding me back. I just thought you guys may have seen something like it before. I'm in the midst of trying to distil it into a simple reproducible error that is (hopefully) unrelated to Argo.

**Comment by edwardaux** [comment]
Aha... once I pulled it out into a playground and simplified things, I found that I can get it to work with a very simple modification.

```
Decoded.optional(decoded)        // this is broken
Decoded<A>.optional(decoded)     // this one works 
```

As suspected, nothing to do with Argo, but it has been an interesting journey nonetheless. Apologies for the noise.

**Comment by gfontenot** [comment]
Ah, interesting. That's... not a particularly helpful error. Glad you got it figured out.

One note: You might (should) be able to omit the type entirely and just use `.optional`. Swift's type inference _should_ be able to figure the `Decoded<A>` bit out. _should_. No promises.

> Does the Swift 3 Argo code contain a static `Decoded.optional` function?
Yeah, sorry, I forgot that we had removed it. I'm going to be shipping a 4.1 release on Friday (if not sooner) that re-adds `.optional` to the lib. See #420 for more info.

**Comment by edwardaux** [comment]
Ah, yes. Using `.optional` is enough to let the inference engine do its stuff. Nice... thanks.

#420 looks good. I feel a bit embarrassed now... I searched for optional in the code, but neglected to look at the Issues list 😊 I'll pull it in once its released.

**Comment by gfontenot** [comment]
No worries! I definitely would have missed it there myself.
