### ISSUE TITLE
Unable to update to latest release v4.1.0

### ISSUE THREAD

**Issue by lscheeler** [thoughtbot/Argo#431]
I am trying to update my pod to the latest release (4.1.0). However when I run pod update I receive the first error shown below. I then realized that version 4.1.0 hasn't been published on [CocoaPods ](https://cocoapods.org/pods/Argo) and was wondering when this would be published. Also to get around this I tried to use the tag of the repo in my podfile as follows:

`pod 'Argo', :git => 'https://github.com/thoughtbot/Argo.git', :tag => 'v4.1.0'`

However after running pod update I receive the error in Xcode 8: framework not found Argo, linker command failed with exit code 1. I then noticed that the only files that installed were the License and Readme.md files. 

### Error Messages

1.)

`Argo (~> 4.1.0)` required by `Podfile`

None of your spec sources contain a spec satisfying the dependency: `Argo (~> 4.1.0)`.

You have either:
 * out-of-date source repos which you can update with `pod repo update`.
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile..

2.)

ld: framework not found Argo
clang: error: linker command failed with exit code 1 (use -v to see invocation)

### Argo Version

_Argo 4.1.0_

### Dependency Manager

_Cocoapods_

**Comment by gfontenot** [comment]
Oops! Sorry about that. I just pushed 4.1 to CocoaPods.
