### ISSUE TITLE
Supporting XML Parsing

### ISSUE THREAD

**Issue by hossamghareeb** [thoughtbot/Argo#433]
Is there any possibility to support XML parsing in the future? If I wanted to do it myself, is there any advices to tips to know about?

**Comment by gfontenot** [comment]
There's actually nothing JSON specific to Argo other than some naming. As a part of our test suite we're actually already [parsing Plists][plist-decoding] and [native Swift dictionaries][dict-decoding].

So if you already have an XML parser that goes from XML -> NSDictionary, and the basic types line up with what Argo expects (strings, numbers, bools, null as raw values, arrays and string-to-value dictionaries as collections), then you shouldn't have any problems using Argo to perform the Dictionary -> Model transformation.

[plist-decoding]: https://github.com/thoughtbot/Argo/blob/master/Tests/ArgoTests/Tests/PListDecodingTests.swift
[dict-decoding]: https://github.com/thoughtbot/Argo/blob/master/Tests/ArgoTests/Tests/SwiftDictionaryDecodingTests.swift

**Comment by hossamghareeb** [comment]
Yes true, actually the naming confused me so I thought it only works with JSON. I found some parser to convert XML to dictionary so I think it would work. 

Thanks a lot.

**Comment by gfontenot** [comment]
@hossamghareeb Glad I could help! I'm going to go ahead and close this issue but feel free to re-open or add more comments if you have any questions in the future.
