### ISSUE TITLE
Decode a class?

### ISSUE THREAD

**Issue by andrew8712** [thoughtbot/Argo#435]
I noticed all the examples here use `struct`s. Is the library able to decode classes along with separating the decoding logic from the model itself?

**Comment by gfontenot** [comment]
Decoding classes is the same as decoding structs. There's no difference as far as Argo is concerned. Not sure what you mean by separating the decoding logic. The `Decodable` conformance needs to be done on the class/struct/enum, it can't live on a different object. But you can always put that conformance in a different file if you prefer.

**Comment by gfontenot** [comment]
I'm going to go ahead and close this due to inactivity but please feel free to reopen if this is still an issue.
