### ISSUE TITLE
Number parsing failing on Linux

### ISSUE THREAD

**Issue by gfontenot** [thoughtbot/Argo#438]
It looks like parsing numbers into `JSON` is failing under linux. I'm not sure what the deal is, but you can [see the failure in this REPL](http://swiftlang.ng.bluemix.net/#/repl/5845c1ba4d3ed316f53338f0)

**Comment by sharplet** [comment]
Not sure why, but I can't load that REPL:

![image](https://cloud.githubusercontent.com/assets/147686/20900187/5c0bc624-bafb-11e6-93ef-7b715c7a2ed1.png)

**Comment by gfontenot** [comment]
That repl thing is dead, and I think this is the same issue as #455. Closing.
