### ISSUE TITLE
Default value for null array property fails during decode

### ISSUE THREAD

**Issue by Marcin-Kapusta** [thoughtbot/Argo#439]
I don't know why this is not working. I would like to have non optional array in my struct model. If JSON contains null value for array I would like to transform it to empty array. Maybe this is a Bug?

### Error Messages

Failure(TypeMismatch(Expected Object, got Null))

### Output in terminal with JSON

```
{
  "array" : null,
  "number" : 5.5
}
Failure(TypeMismatch(Expected Object, got Null))
```

### Models and Test Method to show Issue

```
struct ArgoTestInfo {
    let array: [Int]
    let number: Double
}

extension ArgoTestInfo: Decodable {
    static func decode(_ json: JSON) -> Decoded<ArgoTestInfo> {
        let tmp = curry(self.init)
        return tmp
            <^> (json <|| "array" <|> Decoded<[Int]>.success([]))
            <*> (json <| "number")
    }
}

func testArgo() {
    var dict = [String: Any]()
    dict["array"] = NSNull()
    dict["number"] = 5.5
    let jsonData = try! JSONSerialization.data(withJSONObject: dict, options: [.prettyPrinted])
    let jsonString = String(bytes: jsonData, encoding: .utf8)!
    
    print(jsonString)
    let testInfo: Decoded<ArgoTestInfo> = decode(jsonData)
    print(testInfo)
}
```

### Argo Version

- Argo (4.1.1):
- Runes (>= 4.0.0)
- Curry (3.0.0)
- Swift (3.0.1)

### Dependency Manager

Cocoapods
xCode 8.1

**Comment by jshier** [comment]
Most likely you need to use `pure([]` for your alternate result

**Comment by Marcin-Kapusta** [comment]
Using `pure([])` does not solve this issue.

**Comment by jshier** [comment]
Ah, your error message is about an `Object` not an `Array`, so it seems like perhaps your JSON isn't quite what you expected. Find out what's causing that error and you should have the source of your issue.

**Comment by Marcin-Kapusta** [comment]
@jshier I updated my initial Issue with some more info and test method so Everybody can easily run and check if problem exists on their environments.

**Comment by jshier** [comment]
I'm not sure how your code works, but you should be decoding a JSON object, not data. This code works fine:

```swift
  struct ArgoTestInfo {
    let array: [Int]
}

extension ArgoTestInfo: Decodable {
    static func decode(_ json: JSON) -> Decoded<ArgoTestInfo> {
        return self.init
            <^> (json <|| "array" <|> pure([]))
    }
}

let jsonString = "{\"array\":null}"
let jsonObject = try! JSONSerialization.jsonObject(with: jsonString.data(using: .utf8)!, options: [])
let decodedTest = ArgoTestInfo.decode(JSON(jsonObject))
print(decodedTest)
```

**Comment by Marcin-Kapusta** [comment]
For me this looks like this  `<|>` operator is not working really well with Arrays.

**Comment by Marcin-Kapusta** [comment]
@jshier Thank You my friend for explanation. Yes Indeed this works and I was very tired to not see this silly mistake in my tests. Now my test method looks like this and it works as expected. Thanks!

```
func testArgo() {
    var dict = [String: Any]()
    dict["array"] = NSNull()
    dict["number"] = 5.5
    let jsonData = try! JSONSerialization.data(withJSONObject: dict, options: [.prettyPrinted])
    let jsonString = String(bytes: jsonData, encoding: .utf8)!
    print(jsonString)
    
    let jsonObject = try! JSONSerialization.jsonObject(with: jsonString.data(using: .utf8)!, options: [])
    
    //let jsonObject = JSON(dict)
    let testInfo1: Decoded<ArgoTestInfo> = decode(jsonObject)
    print("1: \(testInfo1)")
    
    let testInfo2: Decoded<ArgoTestInfo> = decode(dict)
    print("2: \(testInfo2)")  
}
```

**Comment by proactive-solutions** [comment]
Can I use this library from objective-C Code?

**Comment by gfontenot** [comment]
@proactive-solutions No, sorry. This is only usable from Swift.

I'm going to close this thread due to inactivity (and because it looks like the issue was resolved?). Feel free to reopen or continue the discussion if that isn't the case.
