### ISSUE TITLE
In search of an operator for inconsistent JSON format. Does it exist?

### ISSUE THREAD

**Issue by btc** [thoughtbot/Argo#443]
I am searching for an operator to help me concisely parse a JSON format that comes in two variants. Is this currently possible? If not, is it possible to define such an operator?

### Sample JSON

``` json
{
  "name_tag": "Brian"
}
```
``` json
{
  "name-tag": "Brian"
}
```

### Models

``` swift
struct User {
    let nameTag: String
}
```

Ideally, I would write:

``` swift
extension User: Decodable {
    static func decode(_ j: JSON) -> Decoded<User> {
        return curry(self.init)
            <^> j <| "name-tag" <?OPERATOR?> "name_tag"
    }
}
```

### Argo Version

4.1.1

### Dependency Manager

Carthage

**Comment by jshier** [comment]
This may work:

`(j <| "name-tag") <|> (j <| "name_tag")`

I'm not sure whether the parentheses are necessary.

**Comment by btc** [comment]
I tried to add that but couldn't get it to compile without expression complexity errors. Hmm.

**Comment by jshier** [comment]
In that case move the curried initializer to a separate value.

**Comment by jshier** [comment]
Or since you only have one value there you don't need the curried initializer at all.

**Comment by gfontenot** [comment]
I'm fascinated by the frequency with which you (@btc) are running into these compiler complexity errors. I'm really sorry about that.

@jshier is correct, the operator you are looking for is `<|>` (alternatively, using the `.or(_:)` instance method on `Decoded`), and I'd write it the way he did.

I'd definitely try saving the curried function off to an intermediate constant first, but if that doesn't work, you could also try saving the result of this decoding operation off to an intermediate constant:

```swift
extension User: Decodable {
  static func decode(_ j: JSON) -> Decoded<User> {
    let tag: Decoded<String> = (j <| "name-tag") <|> (j <| "name_tag")

    return curry(self.init)
      <^> tag
  }
}
```

**Comment by btc** [comment]
Also: 

``` swift
func eitherO(_ j: JSON, _ field: String, _ alt: String) -> Decoded<String> {
    return  j <|? field <|> j <|? alt
}
```
