### ISSUE TITLE
Decode "Any" and decoding keys arbitrarily  

### ISSUE THREAD

**Issue by fedtuck** [thoughtbot/Argo#444]
I need to decode the following JSON, its keys could be anything
```
"DeviceStateVariables": {
                          "FanMode": "Auto",
                          "Mode": "CoolOn",
                          "Heating": 68,
                          "Cooling": 67,
                          "Temperature": 67
                          "AnyKey": AnyValue of AnyType
                        }
```

to get StateVariable objects like:
```
class StateVariable {
	type: String
	value: Any
}
```

```
StateVariable(type:"FanMode",value:"Auto")
StateVariable(type:"Mode",value:"CoolOn")
StateVariable(type:"Heating",value:68)
StateVariable(type:"Cooling",value:67)
StateVariable(type:"Temperature",value:67)
```

is this possible? AFAIK it is not possible to decode to Any and ecoding keys arbitrarily also isn't really well supported

### Argo Version
Argo 3.0.0_

**Comment by tonyd256** [comment]
Hey @fedtuck, I think the easiest thing to do here would be to decode to `[String: String]` then map over that to get your `[StateVariables]`. Something like
```
let variables: Decoded<[String: String]> = json <| "DeviceStateVariables"
let states Decoded<[StateVariables]> = variables.map { vars in
  vars.map { item in
    let (key, value) = item
    return StateVariable(type: key, value: value)
  }
}
```
or you could fancy that up a bit to get
```
let variables: Decoded<[String: String]> = json <| "DeviceStateVariables"
let states Decoded<[StateVariables]> = variables.map { $0.map { StateVariable(type: $0.0, value: $0.1) } }
```
I think that should do it.

**Comment by fedtuck** [comment]
@tonyd256 thanks a lot for your help. The issue Im still having is that DeviceStateVariables is actually [String:Any], so I cannot use Decoded<[String: String]. Do you know any workaround for that?

**Comment by tonyd256** [comment]
If you conform `Any` to `Decodable` that should do the trick. That would mostly involve simply returning the value from all the cases of `JSON` in the `decode` function.

**Comment by fedtuck** [comment]
@tonyd256 Im trying to implement this, but the line 
```
let variables: Decoded<[String: String]> = json <| "DeviceStateVariables"
```

doesn't work for me. I get an error 
<img width="669" alt="screen shot 2017-01-05 at 00 01 11" src="https://cloud.githubusercontent.com/assets/1207092/21667993/59d499f0-d2dc-11e6-8159-2ed4eca88d31.png">

Do you happen to know what could it be?

**Comment by tonyd256** [comment]
hmm, this (https://github.com/thoughtbot/Argo/blob/f494b057b12c36239892a820262b566f09a5275d/Argo/Types/StandardTypes.swift#L202) should allow you to do that ... I'll try it out in a playground tomorrow and get back to you.

**Comment by gfontenot** [comment]
We don't have a definition of `<|` that works with dictionaries. You'll need to do use `decodeObject` instead:

```swift
let variables: Decoded<[String: String]> = (json <| "DeviceStateVariables").flatMap(decodeObject)
```

That _should_ work for you.

**Comment by tonyd256** [comment]
@fedtuck any update here? Did that end up doing the trick?

**Comment by gfontenot** [comment]
I'm going to go ahead and close this due to inactivity but please feel free to reopen if this is still an issue.
