### ISSUE TITLE
Add a known issues paragraph to README

### ISSUE THREAD

**Issue by intonarumori** [thoughtbot/Argo#451]
Thanks for the library but you need to add a known issues / limitations section to your readme file.
Once you reach 15-20 properties on a model you will have serious issues adding new properties without properly breaking down the expression into partials.
Please provide a clear best practices for this as reading through multiple issue tickets with multi-year conversations is not fun.

This issue had a major productivity loss on our team, it either works in 5 minutes or you will spend hours trying to please the compiler.

I think not stating this limitation is misleading the community.

Thank you.

**Comment by intonarumori** [comment]
Ok, I found these documents in the Argo documentation, but still I would strongly recommend to put a link in the README file as this is a serious time drain.

You _have_ to structure your code differently to make Argo work and not stating it upfront is disingenous in my book. That's a major concern when selecting a library for your project.

**Comment by gfontenot** [comment]
Hey @intonarumori, sorry about these issues you ran into. We do have a link to the documentation directory in the README, at the end of the usage section. I'd love to hear ideas on how to make this more prominent, and would especially love to see a PR making the change that would have solved your specific issues.

**Comment by gfontenot** [comment]
I'm going to go ahead and close this due to inactivity but please feel free to reopen if this is still an issue.
