### ISSUE TITLE
How to decode the value from a type to another type

### ISSUE THREAD

**Issue by MrCoderMSH** [thoughtbot/Argo#457]
_[Description of the issue you are experiencing]_
I want to konw how to decode that value of type long long or String  to Date.
### Error Messages

_List all the error messages or warnings you are seeing, if any._

### Sample JSON

```
{
  "birthdate": "1992-11-11" // or "birthdate": 1494335162000
}
```

### Models

_All models involved, including their `Decodable` implementations._

```
struct User {
   let birthdate: Date?
}

extension User: Decodable {
  // ... I want to konw how to decode the value of "birthdate".
}
```

### Argo Version

_example: Argo 3.0.0_

### Dependency Manager

_examples: Carthage, Cocoapods, git submodules, copied code, etc._

**Comment by tonyd256** [comment]
Hi @MrCoderMSH, so you have 2 pretty good options here.

1. Conform `Date` to `Decodable`. The way Argo works, any type that conforms to `Decodable` can be decoded from JSON using the standard `json <| "date"` syntax. You'd want to implement it kind of like we did with `URL` in [our tests](https://github.com/thoughtbot/Argo/blob/master/Tests/ArgoTests/Models/URL.swift). Create a global or lazy date formatter and use it to parse the string or long long.

The major downside to this is that you can only implement it once so if your project needs to parse multiple kinds of date strings into `Date` types this might not be the best approach.

2. Write a function (or use a formatter) to convert the `String` into a `Date` on the fly. You can apply any function to the decoded json type during decoding. The hard part is lining up the types so let's take a look. Using the `User` model above:

```
extension User: Decodable {
  static func decode(_ json: JSON) -> Decoded<User> {
    return User.init <^> convertDate(json <| "date")
  }
}
```

Let's start with this base. So we need to write a function `convertDate` to help us convert our `String` to our `Date`.

```
func convertDate(_ string: String) -> Date {
  return someFormatter.date(from: string) ?? Date()
}
```

`someFormatter` is a `DateFormatter` that you've created to parse your date string. That's our basic converter function. The only issue is that Argo works with `Decoded` values to wrap possible decoding failure messages. So we need to modify our function a bit:

```
func convertDate(_ string: Decoded<String>) -> Decoded<Date> {
  return string.map { someFormatter.date(from: $0) ?? Date() }
}
```

Now that will compile; however, a function with `Decoded<> -> Decoded<>` is a bit of a smell in functional programming (won't go into that here) so we can pull out the first `Decoded<>`.

```
func convertDate(_ string: String) -> Decoded<Date> {
  return .success(someFormatter.date(from: string) ?? Date())
  // you could also have a better failure message
  return someFormatter.date(from: string).map(pure) ?? .failure(.custom("Could not parse date string \(string)"))
}
```

Great! Now the last part is to change the decode function to use the latest convert function:

```
extension User: Decodable {
  static func decode(_ json: JSON) -> Decoded<User> {
    return User.init <^> (json <| "date" >>- convertDate)
  }
}
```

We use `>>-` (aka `flatMap`) to pass the decoded `String` into `convertDate` only if it successfully decoded that `String`. Unsure about paren placement, but that should do it for you. Then you can have different convert functions to handle different ways to parse a date.
