### ISSUE TITLE
Decoding JSON API Relationships

### ISSUE THREAD

**Issue by hugobast** [thoughtbot/Argo#461]
I find that using Argo to decode JSON API (jsonapi.org) JSON is really difficult. This is a request for documentation which I could do but I need some guidance. Honestly I think my solution requires too much code and that I am missing something simpler. I'll continue working on it.

### Sample JSON

```json
{
  "data": {
    "id": "1",
    "type": "order",
    "attributes": {
      "number": "NUM12345",
      "total": "$0.00"
    },
    "relationships": {
      "line_items": {
        "data": [{
          "type": "line_item",
          "id": "12"
        }]
      }
    },
    "included": [{
      "id": "12",
      "type": "line_item",
      "attributes": {
        "quantity": 1
      }
    }]
  }
}
```

### Current Solution

```swift
protocol Model {
  var id: String { get }
  static var type: String { get }
}

extension Model {
  static var type: String {
    return String(describing: self).underscore ?? ""
  }
}

struct Order: Decodable, Model {
  let id: String
  let number: String
  let total: String
  let lineItems: [LineItem]

  static func decode(_ json: JSON) -> Decoded<Order> {
    return curry(Order.init)
      <^> json <| "id"
      <*> json <| ["attributes", "number"]
      <*> json <| ["attributes", "total"]
      <*> RelationshipParser.decode(json)
  }
}

struct LineItem: Decodable, Model {
  let id: String
  var quantity: Int

  static func decode(_ json: JSON) -> Decoded<LineItem> {
    return curry(LineItem.init)
      <^> json <| "id"
      <*> json <| ["attributes", "quantity"]
  }
}

struct RelationshipParser {
  let json: JSON
  let type: String

  static func decode<A>(_ json: JSON) -> Decoded<[A]> where A: Decodable, A: Model, A.DecodedType == A {
    return RelationshipParser(json: json, type: A.type).decode()
  }

  func decode<A>() -> Decoded<[A]> where A: Decodable, A: Model, A.DecodedType == A {
    let decoded: Decoded<[JSON]> = json <|| "included"
    let objects = (decoded.value ?? []).map { A.decode($0) }

    return pure(catDecoded(objects).filter { ids.contains($0.id) })
  }

  private var ids: [String] {
    let decoded: Decoded<[JSON]> = json <|| ["relationships", type, "data"]

    return decoded.flatMap { sequence($0.map { $0 <| "id" }) }.value ?? []
  }
}

```

### Argo Version

_Argo 4.1.2_

### Dependency Manager

_Carthage_

**Comment by Arcovv** [comment]
Hi, @hugobast 
My company is using` JSON:API` now. And I used Argo to decode the JSON Document.But overall, I can not be very comfortable to solve this serialization process. The main problem will be `included` and `relationship`, and `linked object`. My company's Networking Layer has open source, you can get some reference from the inside. [MooApi](https://github.com/eCrowdMedia/MooApi)

**Comment by hugobast** [comment]
Ok my solution suffers from a pretty big flaw, when decoding a list of objects at the root we lose the `included` when decoding each individual items since that lives at the same level as `data`.

**Comment by Arcovv** [comment]
Yeah, so I think we should use `NSObject` and key-value programming to serialize the JSON:API objects. In out app, we also need to save all objects to database. So I just saved the `data` id and used  Realm `to-one-relationship` to bind any `relationship`.

**Comment by hugobast** [comment]
Ok so this is all incorrect I started with a wrong json fixture that put `included` within `data` but they are siblings, I'll close and re-open if I have a better solution
