### ISSUE TITLE
Pitch: JSON API support

### ISSUE THREAD

**Issue by sharplet** [thoughtbot/Argo#464]
There have been a couple of issues recently on the topic of parsing [JSON API](jsonapi.org). I've had an idea in the back of my mind for a while now about how we might provide a nice API for handling this. Before I go into too much detail, here's an example that I have working:

```swift
protocol JSONAPIDecodable {
    associatedtype DecodedType
    static func decode(_ object: JSONAPI.Object) -> Decoded<DecodedType>
}

struct Article {
    var id: String
    var title: String
}

extension Article: JSONAPIDecodable {
    static func decode(_ object: JSONAPI.Object) -> Decoded<Article> {
        guard object.type == "articles" else {
            return .typeMismatch(expected: "articles", actual: object)
        }
        
        let json = JSON.object(object.attributes)
        
        return curry(Article.init)
            <^> pure(object.id)
            <*> json <| "title"
    }
}

let json = // ...
let document: JSONAPI.Document<Article>? = decode(json)
```

The core idea is that instead of parsing the model directly out of the JSON API document, we would instead decode via a generic `JSONAPI.Document` type that encapsulates the JSON API–specific structure.

Here's the top level types I have so far:

```swift
enum JSONAPI {
    enum Document<Model: JSONAPIDecodable> {
        case resource(Model.DecodedType)
        case collection([Model.DecodedType])
        // case error([JSONAPI.Error])
    }
    
    enum Data {
        case object(Object)
        case collection([Object])
    }
    
    struct Object {
        var id: String
        var type: String
        var attributes: [String: JSON]
    }
}

// along with Decodable conformance for these various intermediate types
```

Currently this handles single resources and collections. The biggest thing missing right now is [compound documents](http://jsonapi.org/format/#document-compound-documents) (a.k.a. `"included"` resources). I'm imagining a second parameter to `JSONAPIDecodable.decode()` that you could query for `Decoded<Relationship>` (similar to how the various decode operators allow you to extract things from `JSON` already).

I have a playground with all this working — I'll either post that here or push up a PR with an initial implementation.

Thoughts? Has anyone already tried this and it completely fell apart?

**Comment by sharplet** [comment]
Another cool thing about this is that you can derive `Decodable` conformance for free from JSON API documents:

```swift
extension Decodable where Self: JSONAPIDecodable {
    static func decode(_ json: JSON) -> Decoded<DecodedType> {
        return JSONAPI.Document<Self>.decode(json).flatMap { document in
            switch document {
            case let .collection(collection):
                return .typeMismatch(expected: String(describing: Self.self), actual: type(of: collection))
            case let .resource(model):
                return pure(model)
            }
        }
    }
}
```

**Comment by stephencelis** [comment]
Neat idea! JSON API is pretty specific, though, so might make sense to live as its own `ArgoJSONAPI` lib?

**Comment by sharplet** [comment]
Having a separate lib seems reasonable to me.

**Comment by tonyd256** [comment]
Having a separate lib that is built on top of Argo to handle JSONAPI nicely has been a dream of mine. Excited to see the first steps being taken here!

**Comment by sharplet** [comment]
Another note: I think this is suitable as a general signature:

```swift
static func decode(_ object: JSONAPI.Object) -> Decoded<DecodedType>
```

But in practice I think it makes sense to add `static var jsonAPIType: String { get }` (or similar) to the `JSONAPIDecodable` protocol, to allow this logic to provided automatically:

```swift
        guard object.type == "articles" else {
            return .typeMismatch(expected: "articles", actual: object)
        }
        
        let json = JSON.object(object.attributes)

        // from here on is the only bit I care about when implementing for my custom type
```

So perhaps we could have something like this instead:

```swift
static func decode(id: String, attributes: JSON) -> Decoded<DecodedType>
```

And provide a default implementation for the `JSONAPI.Object` form.

**Comment by gfontenot** [comment]
I'm very interested in this, and I'm _extremely_ interested in it being a supplemental framework as opposed to something built into Argo directly.

**Comment by sharplet** [comment]
You can follow along with https://github.com/thoughtbot/ArgoJSONAPI if you're interested! (there's nothing there right now)

**Comment by gfontenot** [comment]
I'm going to go ahead and close this issue, since it seems like we're going to push this functionality into a companion library.
