### ISSUE TITLE
Parse nested array failed

### ISSUE THREAD

**Issue by wongzigii** [thoughtbot/Argo#476]
How can I parse a nested array JSON type?

### Error Messages

> Type '[Exercise.Reference]' does not conform to protocol 'Decodable'

### Sample JSON

```json
{
    "exercise": {
        "analyses": [
            [
                {
                    "type": 0,
                    "content": "주스"
                }
            ]
        ]
    }
}
```

### Models

_All models involved, including their `Decodable` implementations._

```swift
struct Exercise {
    var analyses: [[Reference]]?

    struct Reference {

        var type: ReferenceType

        var content: String

        var width: Int?

        var height: Int?
    }

    enum ReferenceType: Int {
        case text = 0
        case pic = 1
        case audio = 2
        case unknown = 3
    }
}

extension Exercise: Decodable {
    return curry(Exercise.init)
        <^> json <||? "analyses"
}

extension Exercise.Reference: Argo.Decodable {

    static func decode(_ json: JSON) -> Decoded<Exercise.Reference> {
        return curry(Exercise.Reference.init)
        <^> json <| "type"
        <*> json <| "content"
        <*> json <|? "width"
        <*> json <|? "height"
    }
}

extension Exercise.ReferenceType: Argo.Decodable {
    public static func decode(_ json: JSON) -> Decoded<Exercise.ReferenceType> {
        switch json {
        case let .number(type):
            return .success(Exercise.ReferenceType(rawValue: Int(type)) ?? .unknown)
        default:
            return .failure(.typeMismatch(expected: "Int", actual: json.description))
        }
    }
}
```

### Argo Version

_example: Argo 3.0.0_

### Dependency Manager

_examples: Carthage, Cocoapods, git submodules, copied code, etc._

**Comment by wongzigii** [comment]
If would appreciate if you can take a look at this issue. :D

**Comment by jshier** [comment]
Argo doesn't actually support decoding arrays of arrays by default. Perhaps with Swift 4.1's conditional conformances, but for now you'll need to do it manually and define a `decode` method within an extension on `Array`. Something like `extension Array where Element == [Reference]`.

**Comment by wongzigii** [comment]
@jshier Thanks for your reply.

````
extension Array where Element == [Exercise.Reference] {
    func decode() -> Decoded<[Decoded<Exercise.Reference>]> {
        var result: [Decoded<Exercise.Reference>] = []
        self.forEach { inner in
			let r = Exercise.Reference.decode(JSON(inner))
            result.append(r)
        }
        return .success(result)
    }
}
````

I finally get this code, however, I don't know how to call this method on `extension Exercise.Analyse: Argo.Decodable`

````
extension Exercise.Analyse: Argo.Decodable {

    static func decode(_ json: JSON) -> Decoded<Exercise.Analyse> {
        // How?
    }
}
````

Can you guide me a little bit more? Thanks

**Comment by gfontenot** [comment]
I think you can do this without a custom decode function, actually. This is going to be _so much easier_ with Swift 4.1 and conditional conformance, but the gist now is that you'll want to move from `JSON` to `[JSON]` then to `[[Reference]]`:

```swift
extension Exercise: Argo.Decodable {
  static func decode(_ json: JSON) -> Decoded<Exercise> {
    let djs: Decoded<[JSON]> = json <|| "analyses"
    let ans: Decoded<[[Reference]]> = djs.flatMap { js in
      sequence(js.map([Reference].decode))
    }

    return curry(Exercise.init)
      <^> .optional(ans)
  }
}
```

This can be reduced to single expressions if you prefer. Alternatively, if you do this kind of thing frequently you can add a generic global function like so:

```swift
func decodeNested<T: Argo.Decodable>(_ json: JSON, key: String) -> Decoded<[[T]]> where T.DecodedType == T {
  return (json <|| key)
    >>- { sequence($0.map([T].decode)) }
}

extension Exercise: Argo.Decodable {
  static func decode(_ json: JSON) -> Decoded<Exercise> {
    let ans: Decoded<[[Reference]]> = decodeNested(json, key: "analyses")

    return curry(Exercise.init)
      <^> .optional(ans)
  }
}
```

Once we implement conditional conformance this will simplify to what you have now:

```swift
extension Exercise: Argo.Decodable {
  static func decode(_ json: JSON) -> Decoded<Exercise> {
    return curry(Exercise.init)
      <^> json <||? "analyses"
  }
}
```

FWIW, I don't _think_ you should need to explicitly make `ReferenceType` conform to `Decodable` either. I believe our default implementation should handle that if you just declare the conformance:

```swift
extension Exercise.ReferenceType: Argo.Decodable { }
```

**Comment by gfontenot** [comment]
Good news! This will Just Work in the next release! I'm going to close this now in anticipation of that release, but feel free to re-open this if you have any other questions.
