### ISSUE TITLE
Convert all wrong type return JSON to specific type

### ISSUE THREAD

**Issue by wongzigii** [thoughtbot/Argo#482]
Say I am facing this situation: The server might somehow return a wrong type from server, eg, Int, 

How can I *force cast* the wrong `Int` type into the correct `String` type?

In my case, I will get an `typeMismatch` error, when running into the second decoded object.

### Error Messages

_List all the error messages or warnings you are seeing, if any._

### Sample JSON

```json
{"result": 
[
    {
      "title": "Title1",
      "balance": "1234" // or somehow might be 1234
    },
    {
      "title": "Title2",
      "balance": 1234
    }
]}
```

### Models

_All models involved, including their `Decodable` implementations._

```swift
struct User {
  title: String,
  balance: String
}

extension User: Decodable {
  // ...
}
```

### Argo Version

_example: Argo 4.1.2
### Dependency Manager

_examples: Carthage, Cocoapods, git submodules, copied code, etc._

**Comment by gfontenot** [comment]
Ideally this shouldn't happen. If you control the API you should definitely try to ensure that objects are sent back with a consistent type for a specific key.

That being said: You can handle this on the client side by leveraging Alternative. In your case, if you want to store the result as a String, it's fairly straightforward because you don't need to handle potential failures when converting to Int. Maybe something like:

```swift
// this can be put wherever you want, based on preference
extension Int {
  static func toString(_ int: Int) -> String {
    return "\(int)"
  }
}

extension User: Argo.Decodable {
  static func decode(_ json: JSON) -> Decoded<User> {
    return curry(User.init)
      <^> json <| "title"
      <*> (json <| "balance") <|> (json <| "balance).map(Int.toString)
  }
}
```

**Comment by sharplet** [comment]
FWIW, you could use `String.init(describing:)` too:

```swift
(json <| "balance").map(String.init)
```

**Comment by gfontenot** [comment]
oh yeah right sure

**Comment by wongzigii** [comment]
Closing now. Thanks!

**Comment by wongzigii** [comment]
@gfontenot Oh I figure out the alternative operator `<|>` need to wrap a parenthesis to work around.

**Comment by gfontenot** [comment]
Ah, yeah, I still don't have a great mental-model for the operator precedence (which is why I'm proposing [removing some of them](https://github.com/thoughtbot/Argo/issues/479))
