### ISSUE TITLE
Xcode 11.2.1 Binary operator '<^>' cannot be applied to operands of type

### ISSUE THREAD

**Issue by MervinFlores** [thoughtbot/Argo#499]
I has the follow code implemented to work with Argo framework, has been working until the Xcode 11.2.1 update. when I updated my Xcode Version the follow error appears:

### Error Messages

Binary operator '<^>' cannot be applied to operands of type '(()) -> VoiceMailNumberResponse' and 'Decoded<_?>'

### Models
Here's my code:

```
struct VoiceMailNumberResponse{
    var name: String?
    var value: String?
}

extension VoiceMailNumberResponse: Argo.Decodable {
    static func decode(_ json: JSON) -> Decoded<VoiceMailNumberResponse> {
        let voiceMailNumberResponse = curry(VoiceMailNumberResponse.init)
        return voiceMailNumberResponse
            <^> json <|?  "name"
            <*> json <|?  "value"
    }
}
```
Error appears on line: 
```
"<^> json <|?  "name"
```
In addition I'm using Argo, Curry and Runes for parsing JSON.

### Argo Version

Argo 4.2.0

### Dependency Manager

Cocoapods

**Comment by dahuanghuang** [comment]
I have similar errors in my project

**Comment by gfontenot** [comment]
It sounds like something changed with precedence or type inference. I don't have much time to dig into this right now, but if someone wants to look into this I'm happy to help however I can.

**Comment by gfontenot** [comment]
Oh it might also be something that changed with the type of the initializer? That type signature implies that the curried initializer doesn't take any arguments.

**Comment by dahuanghuang** [comment]
This error is accompanied by a hint

### Messages
"1. Overloads for '<^>' exist with these partially matching parameter lists: ((T) -> U, Decoded<T>), ((T) -> U, Result<T, E>), ((T) -> U, T?), ((T) -> U, [T])"

**Comment by MervinFlores** [comment]
I found a partial solution here 

https://stackoverflow.com/questions/58905411/binary-operator-cannot-be-applied-to-operands-of-type

But now I got  **error: Abort trap: 6 (in target 'myProject' from project 'myProject')**

**Comment by MervinFlores** [comment]
**Here's the solution:**

https://stackoverflow.com/questions/58905411/binary-operator-cannot-be-applied-to-operands-of-type

**Comment by gfontenot** [comment]
Makes sense, although it's unfortunate. I assume the other way to fix this would be to define an explicit initializer, which would keep Swift for synthesizing them for you.

**Comment by gfontenot** [comment]
I'm going to go ahead and close this due to inactivity but please feel free to reopen if this is still an issue.
