### ISSUE TITLE
Error: Expression was too complex to be solved in reasonable time

### ISSUE THREAD

**Issue by rastersize** [thoughtbot/Argo#5]
I’m getting an error `Expression was too complex to be solved in reasonable time; consider breaking up the expression into distinct sub-expressions` when using Argo to parse GitHub’s pull request JSON into my struct. I have the following decoder:

``` swift
static var decoder: JSONValue -> PullRequest? {
        return PullRequest.create
            <^> <|"number"
            <*> <|"state"
            <*> <|"title"
            <*> <||"labels"
            <*> <|*"created_at"
            <*> <|*"updated_at"
            <*> <|*"merged_at"
            <*> <|*"closed_at"
            <*> <|["user", "login"]
            <*> <|*"assignee"
            <*> <|["repository", "owner", "login"]
            <*> <|"comments"
            <*> <|"html_url"
            <*> <|*"statuses_url"
}
```

That is 14 properties for the pull request entity from GitHub’s API (which returns a ton more). I’m currently using the code in #2 as `master` would lead to the compiler and indexer more or less hanging (they did not but they never finished in reasonable time ^^).

This seems to be [caused by a bug in swiftc](http://stackoverflow.com/questions/25412198/limit-to-number-of-terms-in-an-expression) where only 11 statements per expression works.

Do you have a suggestion for workaround of this? As it would be great to be able to have more than 11 properties :smile:

**Comment by sebbean** [comment]
@tonyd256 this limitation should probably be stated somewhere in the README or leave the issue open until it's been resolved (on Swift's end I suppose)

I looked at the GH issues when I noticed this happening in my project - I imagine it'll happen to others in the future.

Love the project! Excited to switch over to it when it can handle my beefy models :wink:

**Comment by tonyd256** [comment]
Glad that you like it! Since this is an "issue" with Swift I'd like to keep it off the issues of Argo. But I will add a note to the readme about this.

**Comment by Blackjacx** [comment]
I have this issue too, oh man I love your project! Can this issue be fixed somehow?

**Comment by tonyd256** [comment]
@Blackjacx You could try making your models smaller if that's possible. If that isn't possible you could try adding intermediate variables to the decoding process. Here is an example:

```swift
static func decode(j: JSONValue) -> OverTwelve? {
  let f = OverTwelve.create
    <^> j <| "int"
    <*> j <| ["user_opt", "name"]
    <*> j <| "double"
    <*> j <| "bool"
    <*> j <|? "int_opt"
    <*> j <| "int2"
    <*> j <| ["user_opt2", "name"]
    <*> j <| "double2"

  return f
    <*> j <| "bool2"
    <*> j <|? "int_opt2"
    <*> j <|| "string_array"
    <*> j <||? "string_array_opt"
    <*> j <|| ["embedded", "string_array"]
    <*> j <||? ["embedded", "string_array_opt"]
    <*> j <|? "user_opt"
}
```

Use as many intermediate variables as you need. I tried it with 14 properties but it worked for me with no intermediate variable as well. This makes me think it's a case by case basis. Try this and if it works for you let us know and we'll add something in the notes.

**Comment by Blackjacx** [comment]
No sorry, using intermediate variables doesn't help me. Maybe I need to split the model. But dosen't need the compiler have the same work even if I split my model? The variables exist in either instance.

**Comment by gilesvangruisen** [comment]
For posterity: breaking up the expression per @tonyd256's suggestion goes a long way to speeding up build times and getting around the complex expression issue, though it is far less elegant.

@Blackjacx I'm curious, besides style/elegance, what was the issue you faced when breaking up the expression?

**Comment by Blackjacx** [comment]
Even when I break up the statement, the compiler stopped working for me. Maybe this is different with swift 1.2?

**Comment by gilesvangruisen** [comment]
Very odd, working fine in 1.1 (Xcode 6.1). I've got a total of 16 properties split into two groups. It's definitely a solid 1-2 seconds faster when split into more than two groups but I've not had any trouble with this yet.

```Swift
public static func decode(json: JSONValue) -> Product? {
    let a = Product.create
        <^> json <| "id"
        <*> json <| "brand"
        <*> json <| "donation_category"
        <*> json <| "price"
        <*> json <| "amount_to_charity"
        <*> json <| "msrp"
        <*> json <| "percent_off"
        <*> json <| "charity_id"

    return a
        <*> json <| "url"
        <*> json <| "color"
        <*> json <| "materials"
        <*> json <| "sizing_details"
        <*> json <| "condition"
        <*> json <| "is_final_sale"
        <*> json <|| "images"
        <*> json <|| "sizes"
}
```

**Comment by nathankot** [comment]
On 1.2 I had to type hint as well to get it compiling (assuming due to the new `Decoded` box?):

```swift
  public static func decode(j: JSON) -> Decoded<Stock> {
    typealias Halved = Decoded<String? -> String? -> Int -> Bool -> String? -> String? -> String? -> Stock> 
    let a: Halved = Stock.create <^> j <| "id"
                                 <*> j <| "userId"
                                 <*> j <| "name"
                                 <*> j <| "price"
                                 <*> j <| "priceCurrency"
    return a                     <*> j <|? "costPrice"
                                 <*> j <|? "costPriceCurrency"
                                 <*> j <| "inventory"
                                 <*> j <| "visible"
                                 <*> j <|? "created"
                                 <*> j <|? "updated"
                                 <*> j <|? "deleted"
  }
```

**Comment by tonyd256** [comment]
You shouldn't have to give `a` a type. It can infer the type from `Stock.create`. You can then eliminate the `Halved` typealias. This probably isn't going to solve your problem but thought I'd let you know.

**Comment by nathankot** [comment]
@tonyd256 unfortunately when the type is removed:

![screen shot 2015-06-24 at 1 25 51 am](https://cloud.githubusercontent.com/assets/1400871/8306958/01cbd2e0-1a10-11e5-891c-e199d7e2105d.png)

**Comment by tonyd256** [comment]
@nathankot What does your `create` function look like? There is an issue with Swift where you need to have `_` before all the parameter names in the `create` function when you break it up like this. Try adding those `_`s to all the parameter names after the break.

**Comment by gilesvangruisen** [comment]
@tonyd256 @nathankot I seem to be having the same issue (same compiler error). Adding `_`s doesn't seem to be helping :/ 

```Swift
static func create
        (id: String)
        (_ brandID: String)
        (_ brandName: String)
        (_ donationCategory: String)
        (_ price: String)
        (_ msrp: String)
        (_ charityID: String)
        (_ charityName: String)
        (_ isSold: Bool)
        (_ mainImage: Image)
        (_ altImage: Image) -> Product {

            return Product(…)
    }

    /** Attempt to decode JSON into Product */
    public static func decode(json: JSON) -> Decoded<Product> {

        // Split expression into intermediate assignments to get past Swift's compiler limitations - feels super wrong
        // See https://github.com/thoughtbot/Argo/issues/5

        let a = Product.create
            <^> json <| "id"
            <*> json <| ["brand", "id"]
            <*> json <| ["brand", "name"]
            <*> json <| ["donation-category", "name"]
            <*> json <| "price"
            <*> json <| "compare-price"

        return a
            <*> json <| ["org", "id"]
            <*> json <| ["org", "name"]
            <*> json <| "status-sold"
            <*> json <| "main-image"
            <*> json <| "alt-image"

    }
```

**Comment by tonyd256** [comment]
@gilesvangruisen are you saying that you are getting the "expression too complex" error or the error "could not find an overload for <*>" that @nathankot is getting without the `_`s?

**Comment by gilesvangruisen** [comment]
My apologies… I'm getting the "could not find an overload for <*>…"

**Comment by tonyd256** [comment]
@gilesvangruisen Thanks for the clarification. So you're importing Runes and Argo right? (sanity check)

**Comment by gilesvangruisen** [comment]
@tonyd256 I am indeed. Both Argo and Runes on latest versions, 1.0.3 and 2.0.0 respectively.

**Comment by nathankot** [comment]
I ended up removing some properties that were YAGNI but @tonyd256 my first
example should get it compiling if you don't mind the mess :)

On Fri, Jun 26, 2015 at 7:51 AM, Giles Van Gruisen <notifications@github.com

**Comment by nhatlee** [comment]
Hi all, I separate my model but still got error. Below is my code:

struct UserModel {
    let user_Id: Int
    let user_Email: String
    let user_FirstName: String
    let user_MemberToken: String
    let user_LastName: String
    let user_SurName: String
    let user_Bithday: String
    let user_ProfilePhoto: String
    let user_Role: Int //role: 1-Coach; 2: Requester
}

extension UserModel: Decodable{
    static func decode(json: JSON) -> Decoded<UserModel> {
        let a = UserModel.init
            <^> json <| "id"
            <*> json <| "email"
            let a1 = a
            <*> json <| "firstName"
            <*> json <| "memberToken"
            <*> json <| "lastName"
        let a2 = a1
            <*> json <|? "sureName"
            <*> json <|? "birthDay"
            return a2
            <*> json <|? "profilePhoto"
            <^> json <|? "role"
}

The error is: "cannot convert value of type ‘(user_Id: Int, user_Email: String, user_FirstName: String….)". Please help me fix it.

**Comment by gfontenot** [comment]
This is a different error. Looks like you're using the optional decode operator (`<|?`) for `user_SurName`, `user_Bithday` (sic), `user_ProfilePhoto`, and `user_Role` when you haven't typed those properties as being optional. You should still be using the normal decode operator for these (`<|`), or you should properly type your optional properties.

**Comment by nhatlee** [comment]
HI @gfontenot I still got the same error when replace all "<|?" by "<|". Don't know the reason :(

**Comment by gfontenot** [comment]
@nhatlee I'm happy to help you, but do you mind opening a new issue for this? No need to spam the other people in this thread.

**Comment by nhatlee** [comment]
@gfontenot Ok. opened new issue as your suggestion.

**Comment by clayellis** [comment]
![screen shot 2016-04-26 at 12 28 42 am](https://cloud.githubusercontent.com/assets/10712068/14808844/e0b855e2-0b45-11e6-9950-6e867aaa82a4.png)

Looks like using intermediate variables isn't going to be an option for much longer. Any other workarounds that anyone is aware of?

**Comment by gfontenot** [comment]
@clayellis that's not actually what that warning is talking about. That implicit currying syntax you used to write your `create` function is being removed, not the ability to use intermediate variables. I'd suggest removing that `create` function and using a `curry` function (like those found in [Curry.framework](https://github.com/thoughtbot/Curry)) to curry your model's initializer. See the code snippet [in the README](https://github.com/thoughtbot/Argo#usage-tldr) for an example.

**Comment by clayellis** [comment]
@gfontenot Refer to @gilesvangruisen's comment made on June 25, 2015. 

A better workaround to all of this without creating a create function is this:
<img width="618" alt="screen shot 2016-04-26 at 6 35 46 pm" src="https://cloud.githubusercontent.com/assets/10712068/14838352/bb4ea0ca-0bdd-11e6-887b-1ebeeca2b32d.png">

This way you don't have to make a create function and can just continue currying. (Basically, what you were referring to, @gfontenot. But it seems like no one else had suggested it explicitly so I figured I'd post.)

**Comment by gfontenot** [comment]
@clayellis Yes, thanks, that's what I was talking about. I just wanted to make sure there wasn't any confusion around what was being removed. Using intermediate variables is going to be possible moving forward, it's just using the implicit currying syntax that's being removed.

**Comment by intonarumori** [comment]
Best practices for solving compiler issues can now be found at:
https://github.com/thoughtbot/Argo/blob/master/Documentation/Curry-Limitations.md
https://github.com/thoughtbot/Argo/blob/master/Documentation/Compilation-Errors.md
