### ISSUE TITLE
EXC_BAD_ACCESS when running tests on 32-bit simulator

### ISSUE THREAD

**Issue by jsslai** [thoughtbot/Argo#54]
I'm using the Xcode 6.3-Beta and the latest Argo from master. When I'm running tests for example on iPhone 5 simulator it crashes on first attempt to map json property to model property. For example in

EmbeddedJSONDecodingTests.swift:
```
func testCommentDecodingWithEmbeddedUserName() {
    let json = JSONValue.parse <^> JSONFileReader.JSON(fromFile: "comment")
    self.json2 = json
    let comment = self.json2 >>- Comment.decode

    XCTAssert(comment != nil)
    XCTAssert(comment?.id == "6")
    XCTAssert(comment?.text == "Cool story bro.")
    XCTAssert(comment?.authorName == "Cool User")
  }
```
Comment.swift:
```
return Comment.create
      <^> j <| "id" // Crashes on this line
      <*> j <| "text"
      <*> j <| ["author", "name"]
```

This happens also when running app which uses Argo on the simulator. When running tests on iPhone 6 simulator it does not crash.

**Comment by gfontenot** [comment]
Thanks for the report. Looks like this problem isn't as fixed as we thought. We have a workaround up as version 0.4.2

**Comment by jsslai** [comment]
Thanks for quick response. It's working now. FYI it also crashed on the real device (iPhone 6).

**Comment by gfontenot** [comment]
@jsslai Just to be clear, it _was_ crashing before the fix, and now it isn't, right?

**Comment by jsslai** [comment]
Yes, before the fix it also crashed on the iPhone 6. I just noticed it after opening this issue.
