### ISSUE TITLE
Get crazy with documentation

### ISSUE THREAD

**Issue by gfontenot** [thoughtbot/Argo#61]
Because of the amount of overhead for this library, we really need to up our documentation game. We should add a Documentation directory with tutorials, examples, and explanations.

**Comment by kielgillard** [comment]
A playground would be nice.

**Comment by gfontenot** [comment]
We have a wip [documentation branch](https://github.com/thoughtbot/Argo/tree/documentation) where this is taking place

**Comment by gfontenot** [comment]
Closing this in favor of #92
