### ISSUE TITLE
Have JSONValue conform to JSONDecodable

### ISSUE THREAD

**Issue by gfontenot** [thoughtbot/Argo#63]
If `JSONValue` conforms to `JSONDecodable`, we can cut the number of operators we define in half in favor of using chained parsing operators.

`j <| ["foo", "bar"]` would become `j <| "foo" <| "bar"`

This would also allow us to get rid of `subscript`, as well as `find` probably.

There might be performance implications here.

**Comment by kaishin** [comment]
Thumbs up. The subscript thing is not even intuitive.
