### ISSUE TITLE
Rename `JSONValue` to `Value`?

### ISSUE THREAD

**Issue by gfontenot** [thoughtbot/Argo#64]
Aeson uses `Value` for the name of its enum value. Maybe we should follow suit?

**Comment by kaishin** [comment]
Thumbs down from me. `Value.value` doesn't have a good sound to it.

**Comment by gfontenot** [comment]
We're already getting rid of the `value` method regardless.

**Comment by kaishin** [comment]
My bad, I even +1'ed that PR.

**Comment by gfontenot** [comment]
No worries, we're moving fast right now.

As per my comment in https://github.com/thoughtbot/Argo/pull/59#issuecomment-75770486, I think we should probably leave this enum named `JSON`.
