### ISSUE TITLE
How to deal with root level Array?

### ISSUE THREAD

**Issue by atljeremy** [thoughtbot/Argo#74]
Something like this, that doesn't come wrapped in a root Dictionary with a key to pull it out of...

```json
[
    {
        "id": 12345,
        "foo": "bar"
    },
    {
        "id": 23456,
        "foo": "bar"
    },
    {
        "id": 34567,
        "foo": "bar"
    },
]

**Comment by tonyd256** [comment]
If each one of those objects in the array has a model that conforms to JSONDecodable then it's not hard. You can use `mapDecode` after you get the `JSONValue` back from `JSONValue.parse`

**Comment by tonyd256** [comment]
That is if you're using Argo 3.x or 4.x ... If you are on master then it will be different.

**Comment by clayellis** [comment]
@tonyd256 How would you do that today? `JSONValue` isn't available anymore it seems.

**Comment by gfontenot** [comment]
Noted this in #17 but I'll drop it in here as well:

`JSONValue` was renamed `JSON` at some point (possibly pre-1.0?). The way you'd want to decode an array of objects now is to use the `decodeArray` helper function:

```
import Curry // Curry.framework: https://github.com/thoughtbot/Curry
import Argo

struct Foo {
  let id: Int
  let foo: String
}

extension Foo: Decodable {
  static func decode(json: JSON) -> Decoded<Foo> {
    return curry(Foo.init)
      <^> json <| "id"
      <*> json <| "foo"
  }
}

let foos: [Foo]? = decodeArray(json).value
