### ISSUE TITLE
Regression in Argo v0.4.2 - crashes Swift 1.2 app

### ISSUE THREAD

**Issue by iancanderson** [thoughtbot/Argo#76]
Installed via carthage, added Argo and Runes frameworks, etc. Build succeeds fine, but get this error when running the app (without using Argo in the code at all):

```
dyld: Symbol not found: _globalinit_33_06E7F1D906492AE070936A9B58CBAE1C_func2
  Referenced from: /Users/ian/Library/Developer/CoreSimulator/Devices/7F24576E-DDA0-4DAC-95A7-F63A5DF54BD1/data/Containers/Bundle/Application/D42A6048-A58E-44CC-909F-F0C40EE06D14/Headquarters.app/Frameworks/Argo.framework/Argo
  Expected in: /Users/ian/Library/Developer/CoreSimulator/Devices/7F24576E-DDA0-4DAC-95A7-F63A5DF54BD1/data/Containers/Bundle/Application/D42A6048-A58E-44CC-909F-F0C40EE06D14/Headquarters.app/Frameworks/libswiftCore.dylib
 in /Users/ian/Library/Developer/CoreSimulator/Devices/7F24576E-DDA0-4DAC-95A7-F63A5DF54BD1/data/Containers/Bundle/Application/D42A6048-A58E-44CC-909F-F0C40EE06D14/Headquarters.app/Frameworks/Argo.framework/Argo
```

**Comment by iancanderson** [comment]
Important note - downgraded to v0.4.1, and app doesn't crash anymore

**Comment by iancanderson** [comment]
Just realized I am on the "old" beta of XCode 6.3 (6D520o). Going to update to latest 6.3 and try again

**Comment by iancanderson** [comment]
Sorry for the goose chase folks. Installed newest xcode (Version 6.3 (6D532l)) and crashed, as expected with v0.4.1. Updated to Argo v0.4.2 and it's working fine :+1:

**Comment by gfontenot** [comment]
I'm blown away that the 0.4.2 binary loaded at all in Beta 1. I built that specifically with Beta 2 and would have expected a compiler error. Glad it worked itself out though!

**Comment by iancanderson** [comment]
I know, weird! 

![http://replygif.net/i/1066.gif](http://replygif.net/i/1066.gif)
