### ISSUE TITLE
How do you handle swift reserved words in the JSON?

### ISSUE THREAD

**Issue by dougbeal** [thoughtbot/Argo#86]
For Example, what if I have this:
```    
"thumbnails": {
     "default": {
      "url": "a"
     },
     "medium": {
      "url": "b"
     },
     "high": {
      "url": "c"
     }
    },
```
I can't define a struct with a property of default.

**Comment by tonyd256** [comment]
The key in the JSON is detatched from what you name your property on your model. You can name your property `defaultURL` and then use `"default"` when decoding:

```swift
statuc func decode(j: JSONValue) -> Thumbnail? {
  return Thumbnail.create
    <^> j <| "default"
    <*> ...
```

**Comment by tonyd256** [comment]
Closing for now but continue the convo if you're still having trouble.
